syntax = "proto3";

package pb;

option go_package = "github.com/gcc798/microservice-kit/application/sys-rpc/pb";




message PingReq {}
message PingResp { string message = 1; }
message Ack { string msg = 1; }
message IdReq { int64 id = 1; }
message BatchIdsReq { repeated int64 ids = 1; }

message PageInfo {
  int64 total = 1;
  int64 size = 2;
  int64 current = 3;
  int64 pages = 4;
}




message Dict {
  int64 id = 1;
  int64 parent_id = 2;
  string dict_type = 3;
  string dict_label = 4;
  string dict_value = 5;
  int64 sort = 6;
  bool is_default = 7;
  int32 status = 8;
  string remark = 9;
  int64 create_by = 10;
  int64 update_by = 11;
  string created_time = 12;
  string updated_time = 13;
}

message DictPageReq {
  int64 page_num = 1;
  int64 page_size = 2;
  string dict_type = 3;
  string dict_label = 4;
  int32 status = 5;
}

message DictCreateReq {
  int64 parent_id = 1;
  string dict_type = 2;
  string dict_label = 3;
  string dict_value = 4;
  int64 sort = 5;
  bool is_default = 6;
  int32 status = 7;
  string remark = 8;
  int64 create_by = 9;
  int64 update_by = 10;
}

message DictUpdateReq {
  int64 id = 1;
  int64 parent_id = 2;
  string dict_type = 3;
  string dict_label = 4;
  string dict_value = 5;
  int64 sort = 6;
  bool is_default = 7;
  int32 status = 8;
  string remark = 9;
  int64 update_by = 10;
}

message DictTypeQueryReq { string dict_type = 1; int64 parent_id = 2; }
message DictLabelQueryReq { string dict_type = 1; string dict_value = 2; }
message DictLabelResp { string label = 1; }
message DictPageResp { repeated Dict records = 1; PageInfo page = 2; }
message DictListResp { repeated Dict records = 1; }





message Config {
  int64 id = 1;
  string name = 2;
  string code = 3;
  string data_json = 4;
  string remark = 5;
  int64 create_by = 6;
  string created_time = 7;
  int64 update_by = 8;
  string updated_time = 9;
}

message ConfigPageReq {
  int64 page_num = 1;
  int64 page_size = 2;
  string name = 3;
  string code = 4;
}

message ConfigCreateReq {
  string name = 1;
  string code = 2;
  string data_json = 3;
  string remark = 4;
  int64 create_by = 5;
  int64 update_by = 6;
}

message ConfigUpdateReq {
  int64 id = 1;
  string name = 2;
  string code = 3;
  string data_json = 4;
  string remark = 5;
  int64 update_by = 6;
}

message ConfigCodeQueryReq { string code = 1; }
message ConfigDataResp { string code = 1; string data_json = 2; }
message ConfigPageResp { repeated Config records = 1; PageInfo page = 2; }
message ConfigListResp { repeated Config records = 1; }





message LoginLog {
  int64 id = 1;
  string user_name = 2;
  string ipaddr = 3;
  string login_location = 4;
  string browser = 5;
  string os = 6;
  int32 status = 7;
  string msg = 8;
  string login_time = 9;
  string client_id = 10;
}

message LoginLogPageReq {
  int64 page_num = 1;
  int64 page_size = 2;
  string user_name = 3;
  string ipaddr = 4;
  int32 status = 5;
  string start_time = 6;
  string end_time = 7;
}

message LoginLogReq {
  string user_name = 1;
  string ipaddr = 2;
  string login_location = 3;
  string browser = 4;
  string os = 5;
  int32 status = 6;
  string msg = 7;
  string client_id = 8;
}

message LoginLogUpdateReq {
  int64 id = 1;
  string user_name = 2;
  string ipaddr = 3;
  string login_location = 4;
  string browser = 5;
  string os = 6;
  int32 status = 7;
  string msg = 8;
  string client_id = 9;
}

message LogCleanReq { int64 days = 1; }
message LoginLogPageResp { repeated LoginLog records = 1; PageInfo page = 2; }

message OperLog {
  int64 id = 1;
  string title = 2;
  string business_type = 3;
  string method = 4;
  string request_method = 5;
  string device_type = 6;
  string oper_name = 7;
  string oper_url = 8;
  string oper_ip = 9;
  string oper_location = 10;
  string oper_param = 11;
  string json_result = 12;
  string status = 13;
  string error_msg = 14;
  string oper_time = 15;
  int64 cost_time = 16;
  string user_agent = 17;
}

message OperLogPageReq {
  int64 page_num = 1;
  int64 page_size = 2;
  string title = 3;
  string oper_name = 4;
  string business_type = 5;
  string status = 6;
  string start_time = 7;
  string end_time = 8;
}

message OperLogReq {
  string title = 1;
  string business_type = 2;
  string method = 3;
  string request_method = 4;
  string device_type = 5;
  string oper_name = 6;
  string oper_url = 7;
  string oper_ip = 8;
  string oper_location = 9;
  string oper_param = 10;
  string json_result = 11;
  string status = 12;
  string error_msg = 13;
  int64 cost_time = 14;
  string user_agent = 15;
}

message OperLogUpdateReq {
  int64 id = 1;
  string title = 2;
  string business_type = 3;
  string method = 4;
  string request_method = 5;
  string device_type = 6;
  string oper_name = 7;
  string oper_url = 8;
  string oper_ip = 9;
  string oper_location = 10;
  string oper_param = 11;
  string json_result = 12;
  string status = 13;
  string error_msg = 14;
  int64 cost_time = 15;
  string user_agent = 16;
}

message OperLogPageResp { repeated OperLog records = 1; PageInfo page = 2; }

service SysService {
  rpc Ping(PingReq) returns (PingResp);

  rpc DictCreate(DictCreateReq) returns (Ack);
  rpc DictPage(DictPageReq) returns (DictPageResp);
  rpc DictBatchDelete(BatchIdsReq) returns (Ack);
  rpc DictType(DictTypeQueryReq) returns (DictListResp);
  rpc DictLabel(DictLabelQueryReq) returns (DictLabelResp);
  rpc DictUpdate(DictUpdateReq) returns (Ack);
  rpc DictDetail(IdReq) returns (Dict);
  rpc DictDelete(IdReq) returns (Ack);

  rpc ConfigCreate(ConfigCreateReq) returns (Ack);
  rpc ConfigPage(ConfigPageReq) returns (ConfigPageResp);
  rpc ConfigBatchDelete(BatchIdsReq) returns (Ack);
  rpc ConfigCode(ConfigCodeQueryReq) returns (ConfigListResp);
  rpc ConfigData(ConfigCodeQueryReq) returns (ConfigDataResp);
  rpc ConfigUpdate(ConfigUpdateReq) returns (Ack);
  rpc ConfigDetail(IdReq) returns (Config);
  rpc ConfigDelete(IdReq) returns (Ack);

  rpc LoginLogCreate(LoginLogReq) returns (Ack);
  rpc LoginLogPage(LoginLogPageReq) returns (LoginLogPageResp);
  rpc LoginLogBatchDelete(BatchIdsReq) returns (Ack);
  rpc LoginLogClean(LogCleanReq) returns (Ack);
  rpc LoginLogUpdate(LoginLogUpdateReq) returns (Ack);
  rpc LoginLogDetail(IdReq) returns (LoginLog);
  rpc LoginLogDelete(IdReq) returns (Ack);

  rpc OperLogCreate(OperLogReq) returns (Ack);
  rpc OperLogPage(OperLogPageReq) returns (OperLogPageResp);
  rpc OperLogBatchDelete(BatchIdsReq) returns (Ack);
  rpc OperLogClean(LogCleanReq) returns (Ack);
  rpc OperLogUpdate(OperLogUpdateReq) returns (Ack);
  rpc OperLogDetail(IdReq) returns (OperLog);
  rpc OperLogDelete(IdReq) returns (Ack);

}
