// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AttachmentBindReq struct {
	AttachmentId  int64                  `path:"attachmentId"`
	BusinessType  string                 `json:"businessType"`
	BusinessId    string                 `json:"businessId"`
	BusinessField string                 `json:"businessField,optional"`
	IsPublic      bool                   `json:"isPublic,optional"`
	Metadata      map[string]interface{} `json:"metadata,optional"`
	ExpireTime    string                 `json:"expireTime,optional"`
}

type AttachmentBusinessQueryReq struct {
	BusinessType string `form:"businessType"`
	BusinessId   string `form:"businessId"`
}

type AttachmentIdPathReq struct {
	AttachmentId int64 `path:"attachmentId"`
}

type AttachmentPageReq struct {
	PageNum      int64  `json:"pageNum"`
	PageSize     int64  `json:"pageSize"`
	FileName     string `json:"fileName,optional"`
	FileType     string `json:"fileType,optional"`
	BusinessType string `json:"businessType,optional"`
}

type AttachmentUrlQueryReq struct {
	AttachmentId int64 `path:"attachmentId"`
	Expires      int   `form:"expires,optional"`
}

type BatchIdsReq struct {
	Ids []int64 `json:"ids"`
}

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type IdPathReq struct {
	Id int64 `path:"id"`
}

type RoleIdPathReq struct {
	RoleId int64 `path:"roleId"`
}

type StringIdPathReq struct {
	Id string `path:"id"`
}
