// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package {{.pkg}}
{{.imports}}
{{.types}}
{{.delete}}
{{.find}}
{{.insert}}
{{.update}}
{{.extraMethod}}
{{.tableName}}
{{.customized}}
