// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type MMenuApiPermission struct {
	Id           int64         `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`
	MenuId       int64         `gorm:"column:menu_id" json:"menu_id"`
	PermissionId int64         `gorm:"column:permission_id" json:"permission_id"`
	CreateBy     sql.NullInt64 `gorm:"column:create_by" json:"create_by"`
	UpdateBy     sql.NullInt64 `gorm:"column:update_by" json:"update_by"`
	CreatedTime  sql.NullTime  `gorm:"column:created_time" json:"created_time"`
	UpdatedTime  sql.NullTime  `gorm:"column:updated_time" json:"updated_time"`
}

func (m *MMenuApiPermissionModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[MMenuApiPermission](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *MMenuApiPermissionModel) FindOne(ctx context.Context, id int64) (*MMenuApiPermission, error) {
	data, err := gorm.G[MMenuApiPermission](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *MMenuApiPermissionModel) FindOneByMenuIdPermissionId(ctx context.Context, menuId int64, permissionId int64) (*MMenuApiPermission, error) {
	data, err := gorm.G[MMenuApiPermission](m.db).
		Where("menu_id = $1 and permission_id = $2", menuId, permissionId).
		First(ctx)
	return &data, err
}

func (m *MMenuApiPermissionModel) Insert(ctx context.Context, data *MMenuApiPermission) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[MMenuApiPermission](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *MMenuApiPermissionModel) Update(ctx context.Context, data *MMenuApiPermission) error {
	return m.db.WithContext(ctx).
		Model(&MMenuApiPermission{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (MMenuApiPermission) TableName() string {
	return "m_menu_api_permission"
}
