// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type MRoleMenu struct {
	Id int64 `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`

	RoleId int64 `gorm:"column:role_id" json:"role_id"`

	MenuId int64 `gorm:"column:menu_id" json:"menu_id"`

	CreateBy sql.NullInt64 `gorm:"column:create_by" json:"create_by"`

	UpdateBy sql.NullInt64 `gorm:"column:update_by" json:"update_by"`

	CreatedTime sql.NullTime `gorm:"column:created_time" json:"created_time"`

	UpdatedTime sql.NullTime `gorm:"column:updated_time" json:"updated_time"`
}

func (m *MRoleMenuModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[MRoleMenu](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *MRoleMenuModel) FindOne(ctx context.Context, id int64) (*MRoleMenu, error) {
	data, err := gorm.G[MRoleMenu](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *MRoleMenuModel) Insert(ctx context.Context, data *MRoleMenu) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[MRoleMenu](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *MRoleMenuModel) Update(ctx context.Context, data *MRoleMenu) error {
	return m.db.WithContext(ctx).
		Model(&MRoleMenu{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (MRoleMenu) TableName() string {
	return "m_role_menu"
}
