// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type MRoleApiPermission struct {
	Id int64 `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`

	RoleId int64 `gorm:"column:role_id" json:"role_id"`

	PermissionId int64 `gorm:"column:permission_id" json:"permission_id"`

	Source int64 `gorm:"column:source" json:"source"`

	CreateBy sql.NullInt64 `gorm:"column:create_by" json:"create_by"`

	UpdateBy sql.NullInt64 `gorm:"column:update_by" json:"update_by"`

	CreatedTime sql.NullTime `gorm:"column:created_time" json:"created_time"`

	UpdatedTime sql.NullTime `gorm:"column:updated_time" json:"updated_time"`
}

func (m *MRoleApiPermissionModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[MRoleApiPermission](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *MRoleApiPermissionModel) FindOne(ctx context.Context, id int64) (*MRoleApiPermission, error) {
	data, err := gorm.G[MRoleApiPermission](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *MRoleApiPermissionModel) FindOneByRoleIdPermissionIdSource(ctx context.Context, roleId int64, permissionId int64, source int64) (*MRoleApiPermission, error) {
	data, err := gorm.G[MRoleApiPermission](m.db).
		Where("role_id = $1 and permission_id = $2 and source = $3", roleId, permissionId, source).
		First(ctx)
	return &data, err
}

func (m *MRoleApiPermissionModel) Insert(ctx context.Context, data *MRoleApiPermission) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[MRoleApiPermission](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *MRoleApiPermissionModel) Update(ctx context.Context, data *MRoleApiPermission) error {
	return m.db.WithContext(ctx).
		Model(&MRoleApiPermission{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (MRoleApiPermission) TableName() string {
	return "m_role_api_permission"
}
