// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type MUserApiPermission struct {
	Id           int64         `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`
	UserId       int64         `gorm:"column:user_id" json:"user_id"`
	PermissionId int64         `gorm:"column:permission_id" json:"permission_id"`
	Source       int64         `gorm:"column:source" json:"source"`
	CreateBy     sql.NullInt64 `gorm:"column:create_by" json:"create_by"`
	UpdateBy     sql.NullInt64 `gorm:"column:update_by" json:"update_by"`
	CreatedTime  sql.NullTime  `gorm:"column:created_time" json:"created_time"`
	UpdatedTime  sql.NullTime  `gorm:"column:updated_time" json:"updated_time"`
}

func (m *MUserApiPermissionModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[MUserApiPermission](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *MUserApiPermissionModel) FindOne(ctx context.Context, id int64) (*MUserApiPermission, error) {
	data, err := gorm.G[MUserApiPermission](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *MUserApiPermissionModel) FindOneByUserIdPermissionIdSource(ctx context.Context, userId int64, permissionId int64, source int64) (*MUserApiPermission, error) {
	data, err := gorm.G[MUserApiPermission](m.db).
		Where("user_id = $1 and permission_id = $2 and source = $3", userId, permissionId, source).
		First(ctx)
	return &data, err
}

func (m *MUserApiPermissionModel) Insert(ctx context.Context, data *MUserApiPermission) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[MUserApiPermission](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *MUserApiPermissionModel) Update(ctx context.Context, data *MUserApiPermission) error {
	return m.db.WithContext(ctx).
		Model(&MUserApiPermission{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (MUserApiPermission) TableName() string {
	return "m_user_api_permission"
}
