// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type SApiPermission struct {
	Id          int64          `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`
	ParentId    int64          `gorm:"column:parent_id" json:"parent_id"`
	Module      string         `gorm:"column:module" json:"module"`
	Code        string         `gorm:"column:code" json:"code"`
	Name        string         `gorm:"column:name" json:"name"`
	NodeType    int64          `gorm:"column:node_type" json:"node_type"`
	Action      string         `gorm:"column:action" json:"action"`
	Method      sql.NullString `gorm:"column:method" json:"method"`
	Path        sql.NullString `gorm:"column:path" json:"path"`
	Sort        int64          `gorm:"column:sort" json:"sort"`
	Status      int64          `gorm:"column:status" json:"status"`
	Remark      sql.NullString `gorm:"column:remark" json:"remark"`
	CreateBy    sql.NullInt64  `gorm:"column:create_by" json:"create_by"`
	UpdateBy    sql.NullInt64  `gorm:"column:update_by" json:"update_by"`
	CreatedTime sql.NullTime   `gorm:"column:created_time" json:"created_time"`
	UpdatedTime sql.NullTime   `gorm:"column:updated_time" json:"updated_time"`
}

func (m *SApiPermissionModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[SApiPermission](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *SApiPermissionModel) FindOne(ctx context.Context, id int64) (*SApiPermission, error) {
	data, err := gorm.G[SApiPermission](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *SApiPermissionModel) FindOneByCode(ctx context.Context, code string) (*SApiPermission, error) {
	data, err := gorm.G[SApiPermission](m.db).
		Where("code = $1", code).
		First(ctx)
	return &data, err
}

func (m *SApiPermissionModel) Insert(ctx context.Context, data *SApiPermission) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[SApiPermission](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *SApiPermissionModel) Update(ctx context.Context, data *SApiPermission) error {
	return m.db.WithContext(ctx).
		Model(&SApiPermission{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (SApiPermission) TableName() string {
	return "s_api_permission"
}
