// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type SAuthClient struct {
	ClientId string `gorm:"column:client_id;primaryKey;autoIncrement:false" json:"client_id"`

	GrantType sql.NullString `gorm:"column:grant_type" json:"grant_type"`

	DeviceType sql.NullString `gorm:"column:device_type" json:"device_type"`

	Status int64 `gorm:"column:status" json:"status"`

	Timeout int64 `gorm:"column:timeout" json:"timeout"`

	ActiveTimeout int64 `gorm:"column:active_timeout" json:"active_timeout"`

	Remark sql.NullString `gorm:"column:remark" json:"remark"`

	CreateBy sql.NullInt64 `gorm:"column:create_by" json:"create_by"`

	CreatedTime sql.NullTime `gorm:"column:created_time" json:"created_time"`

	UpdateBy sql.NullInt64 `gorm:"column:update_by" json:"update_by"`

	UpdatedTime sql.NullTime `gorm:"column:updated_time" json:"updated_time"`
}

func (m *SAuthClientModel) Delete(ctx context.Context, clientId string) error {
	_, err := gorm.G[SAuthClient](m.db).
		Where("client_id = ?", clientId).
		Delete(ctx)
	return err
}

func (m *SAuthClientModel) FindOne(ctx context.Context, clientId string) (*SAuthClient, error) {
	data, err := gorm.G[SAuthClient](m.db).
		Where("client_id = ?", clientId).
		First(ctx)
	return &data, err
}

func (m *SAuthClientModel) Insert(ctx context.Context, data *SAuthClient) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[SAuthClient](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *SAuthClientModel) Update(ctx context.Context, data *SAuthClient) error {
	return m.db.WithContext(ctx).
		Model(&SAuthClient{}).
		Where("client_id = ?", data.ClientId).
		Select("*").
		Omit("client_id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (SAuthClient) TableName() string {
	return "s_auth_client"
}
