// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type SMenu struct {
	Id          int64          `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`
	MenuName    string         `gorm:"column:menu_name" json:"menu_name"`
	ParentId    int64          `gorm:"column:parent_id" json:"parent_id"`
	Sort        int64          `gorm:"column:sort" json:"sort"`
	Path        sql.NullString `gorm:"column:path" json:"path"`
	Component   sql.NullString `gorm:"column:component" json:"component"`
	Query       sql.NullString `gorm:"column:query" json:"query"`
	IsFrame     int64          `gorm:"column:is_frame" json:"is_frame"`
	IsCache     int64          `gorm:"column:is_cache" json:"is_cache"`
	MenuType    int64          `gorm:"column:menu_type" json:"menu_type"`
	Visible     int64          `gorm:"column:visible" json:"visible"`
	Status      int64          `gorm:"column:status" json:"status"`
	Perms       sql.NullString `gorm:"column:perms" json:"perms"`
	Icon        sql.NullString `gorm:"column:icon" json:"icon"`
	Remark      sql.NullString `gorm:"column:remark" json:"remark"`
	CreateBy    sql.NullInt64  `gorm:"column:create_by" json:"create_by"`
	UpdateBy    sql.NullInt64  `gorm:"column:update_by" json:"update_by"`
	CreatedTime sql.NullTime   `gorm:"column:created_time" json:"created_time"`
	UpdatedTime sql.NullTime   `gorm:"column:updated_time" json:"updated_time"`
}

func (m *SMenuModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[SMenu](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *SMenuModel) FindOne(ctx context.Context, id int64) (*SMenu, error) {
	data, err := gorm.G[SMenu](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *SMenuModel) Insert(ctx context.Context, data *SMenu) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[SMenu](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *SMenuModel) Update(ctx context.Context, data *SMenu) error {
	return m.db.WithContext(ctx).
		Model(&SMenu{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (SMenu) TableName() string {
	return "s_menu"
}
