// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type SOrg struct {
	Id          int64          `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`
	ParentId    int64          `gorm:"column:parent_id" json:"parent_id"`
	Ancestors   sql.NullString `gorm:"column:ancestors" json:"ancestors"`
	OrgName     string         `gorm:"column:org_name" json:"org_name"`
	OrgCode     sql.NullString `gorm:"column:org_code" json:"org_code"`
	OrgType     string         `gorm:"column:org_type" json:"org_type"`
	Leader      sql.NullString `gorm:"column:leader" json:"leader"`
	Phone       sql.NullString `gorm:"column:phone" json:"phone"`
	Email       sql.NullString `gorm:"column:email" json:"email"`
	Status      int64          `gorm:"column:status" json:"status"`
	Sort        int64          `gorm:"column:sort" json:"sort"`
	Remark      sql.NullString `gorm:"column:remark" json:"remark"`
	CreateBy    sql.NullInt64  `gorm:"column:create_by" json:"create_by"`
	UpdateBy    sql.NullInt64  `gorm:"column:update_by" json:"update_by"`
	CreatedTime sql.NullTime   `gorm:"column:created_time" json:"created_time"`
	UpdatedTime sql.NullTime   `gorm:"column:updated_time" json:"updated_time"`
}

func (m *SOrgModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[SOrg](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *SOrgModel) FindOne(ctx context.Context, id int64) (*SOrg, error) {
	data, err := gorm.G[SOrg](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *SOrgModel) FindOneByOrgCode(ctx context.Context, orgCode sql.NullString) (*SOrg, error) {
	data, err := gorm.G[SOrg](m.db).
		Where("org_code = $1", orgCode).
		First(ctx)
	return &data, err
}

func (m *SOrgModel) Insert(ctx context.Context, data *SOrg) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[SOrg](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *SOrgModel) Update(ctx context.Context, data *SOrg) error {
	return m.db.WithContext(ctx).
		Model(&SOrg{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (SOrg) TableName() string {
	return "s_org"
}
