// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type SRole struct {
	Id int64 `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`

	RoleKey string `gorm:"column:role_key" json:"role_key"`

	RoleName string `gorm:"column:role_name" json:"role_name"`

	Sort int64 `gorm:"column:sort" json:"sort"`

	Status int64 `gorm:"column:status" json:"status"`

	DataScope int64 `gorm:"column:data_scope" json:"data_scope"`

	IsSystem bool `gorm:"column:is_system" json:"is_system"`

	Remark sql.NullString `gorm:"column:remark" json:"remark"`

	CreateBy sql.NullInt64 `gorm:"column:create_by" json:"create_by"`

	UpdateBy sql.NullInt64 `gorm:"column:update_by" json:"update_by"`

	CreatedTime sql.NullTime `gorm:"column:created_time" json:"created_time"`

	UpdatedTime sql.NullTime `gorm:"column:updated_time" json:"updated_time"`
}

func (m *SRoleModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[SRole](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *SRoleModel) FindOne(ctx context.Context, id int64) (*SRole, error) {
	data, err := gorm.G[SRole](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *SRoleModel) FindOneByRoleKey(ctx context.Context, roleKey string) (*SRole, error) {
	data, err := gorm.G[SRole](m.db).
		Where("role_key = $1", roleKey).
		First(ctx)
	return &data, err
}

func (m *SRoleModel) Insert(ctx context.Context, data *SRole) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[SRole](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *SRoleModel) Update(ctx context.Context, data *SRole) error {
	return m.db.WithContext(ctx).
		Model(&SRole{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (SRole) TableName() string {
	return "s_role"
}
