// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type SUser struct {
	Id int64 `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`

	UserName string `gorm:"column:user_name" json:"user_name"`

	NickName sql.NullString `gorm:"column:nick_name" json:"nick_name"`

	UserType int64 `gorm:"column:user_type" json:"user_type"`

	OrgId int64 `gorm:"column:org_id" json:"org_id"`

	Email sql.NullString `gorm:"column:email" json:"email"`

	Phonenumber sql.NullString `gorm:"column:phonenumber" json:"phonenumber"`

	Sex int64 `gorm:"column:sex" json:"sex"`

	Avatar sql.NullString `gorm:"column:avatar" json:"avatar"`

	Password sql.NullString `gorm:"column:password" json:"password"`

	Status int64 `gorm:"column:status" json:"status"`

	Sort int64 `gorm:"column:sort" json:"sort"`

	LoginIp sql.NullString `gorm:"column:login_ip" json:"login_ip"`

	LoginDate sql.NullInt64 `gorm:"column:login_date" json:"login_date"`

	OpenId sql.NullString `gorm:"column:open_id" json:"open_id"`

	UnionId sql.NullString `gorm:"column:union_id" json:"union_id"`

	Remark sql.NullString `gorm:"column:remark" json:"remark"`

	CreateBy sql.NullInt64 `gorm:"column:create_by" json:"create_by"`

	UpdateBy sql.NullInt64 `gorm:"column:update_by" json:"update_by"`

	CreatedTime sql.NullTime `gorm:"column:created_time" json:"created_time"`

	UpdatedTime sql.NullTime `gorm:"column:updated_time" json:"updated_time"`
}

func (m *SUserModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[SUser](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *SUserModel) FindOne(ctx context.Context, id int64) (*SUser, error) {
	data, err := gorm.G[SUser](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *SUserModel) FindOneByEmail(ctx context.Context, email sql.NullString) (*SUser, error) {
	data, err := gorm.G[SUser](m.db).
		Where("email = $1", email).
		First(ctx)
	return &data, err
}

func (m *SUserModel) FindOneByOpenId(ctx context.Context, openId sql.NullString) (*SUser, error) {
	data, err := gorm.G[SUser](m.db).
		Where("open_id = $1", openId).
		First(ctx)
	return &data, err
}

func (m *SUserModel) FindOneByPhonenumber(ctx context.Context, phonenumber sql.NullString) (*SUser, error) {
	data, err := gorm.G[SUser](m.db).
		Where("phonenumber = $1", phonenumber).
		First(ctx)
	return &data, err
}

func (m *SUserModel) FindOneByUnionId(ctx context.Context, unionId sql.NullString) (*SUser, error) {
	data, err := gorm.G[SUser](m.db).
		Where("union_id = $1", unionId).
		First(ctx)
	return &data, err
}

func (m *SUserModel) FindOneByUserName(ctx context.Context, userName string) (*SUser, error) {
	data, err := gorm.G[SUser](m.db).
		Where("user_name = $1", userName).
		First(ctx)
	return &data, err
}

func (m *SUserModel) Insert(ctx context.Context, data *SUser) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[SUser](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *SUserModel) Update(ctx context.Context, data *SUser) error {
	return m.db.WithContext(ctx).
		Model(&SUser{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (SUser) TableName() string {
	return "s_user"
}
