// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: sys.proto

package sysservice

import (
	"context"

	"github.com/gcc798/microservice-kit/application/sys-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Ack                = pb.Ack
	BatchIdsReq        = pb.BatchIdsReq
	Config             = pb.Config
	ConfigCodeQueryReq = pb.ConfigCodeQueryReq
	ConfigCreateReq    = pb.ConfigCreateReq
	ConfigDataResp     = pb.ConfigDataResp
	ConfigListResp     = pb.ConfigListResp
	ConfigPageReq      = pb.ConfigPageReq
	ConfigPageResp     = pb.ConfigPageResp
	ConfigUpdateReq    = pb.ConfigUpdateReq
	Dict               = pb.Dict
	DictCreateReq      = pb.DictCreateReq
	DictLabelQueryReq  = pb.DictLabelQueryReq
	DictLabelResp      = pb.DictLabelResp
	DictListResp       = pb.DictListResp
	DictPageReq        = pb.DictPageReq
	DictPageResp       = pb.DictPageResp
	DictTypeQueryReq   = pb.DictTypeQueryReq
	DictUpdateReq      = pb.DictUpdateReq
	IdReq              = pb.IdReq
	LogCleanReq        = pb.LogCleanReq
	LoginLog           = pb.LoginLog
	LoginLogPageReq    = pb.LoginLogPageReq
	LoginLogPageResp   = pb.LoginLogPageResp
	LoginLogReq        = pb.LoginLogReq
	LoginLogUpdateReq  = pb.LoginLogUpdateReq
	OperLog            = pb.OperLog
	OperLogBatchReq    = pb.OperLogBatchReq
	OperLogPageReq     = pb.OperLogPageReq
	OperLogPageResp    = pb.OperLogPageResp
	OperLogReq         = pb.OperLogReq
	OperLogUpdateReq   = pb.OperLogUpdateReq
	PageInfo           = pb.PageInfo
	PingReq            = pb.PingReq
	PingResp           = pb.PingResp

	SysService interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
		DictCreate(ctx context.Context, in *DictCreateReq, opts ...grpc.CallOption) (*Ack, error)
		DictPage(ctx context.Context, in *DictPageReq, opts ...grpc.CallOption) (*DictPageResp, error)
		DictBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
		DictType(ctx context.Context, in *DictTypeQueryReq, opts ...grpc.CallOption) (*DictListResp, error)
		DictLabel(ctx context.Context, in *DictLabelQueryReq, opts ...grpc.CallOption) (*DictLabelResp, error)
		DictUpdate(ctx context.Context, in *DictUpdateReq, opts ...grpc.CallOption) (*Ack, error)
		DictDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Dict, error)
		DictDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
		ConfigCreate(ctx context.Context, in *ConfigCreateReq, opts ...grpc.CallOption) (*Ack, error)
		ConfigPage(ctx context.Context, in *ConfigPageReq, opts ...grpc.CallOption) (*ConfigPageResp, error)
		ConfigBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
		ConfigCode(ctx context.Context, in *ConfigCodeQueryReq, opts ...grpc.CallOption) (*ConfigListResp, error)
		ConfigData(ctx context.Context, in *ConfigCodeQueryReq, opts ...grpc.CallOption) (*ConfigDataResp, error)
		ConfigUpdate(ctx context.Context, in *ConfigUpdateReq, opts ...grpc.CallOption) (*Ack, error)
		ConfigDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Config, error)
		ConfigDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
		LoginLogCreate(ctx context.Context, in *LoginLogReq, opts ...grpc.CallOption) (*Ack, error)
		LoginLogPage(ctx context.Context, in *LoginLogPageReq, opts ...grpc.CallOption) (*LoginLogPageResp, error)
		LoginLogBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
		LoginLogClean(ctx context.Context, in *LogCleanReq, opts ...grpc.CallOption) (*Ack, error)
		LoginLogUpdate(ctx context.Context, in *LoginLogUpdateReq, opts ...grpc.CallOption) (*Ack, error)
		LoginLogDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*LoginLog, error)
		LoginLogDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
		OperLogCreate(ctx context.Context, in *OperLogReq, opts ...grpc.CallOption) (*Ack, error)
		OperLogBatchCreate(ctx context.Context, in *OperLogBatchReq, opts ...grpc.CallOption) (*Ack, error)
		OperLogPage(ctx context.Context, in *OperLogPageReq, opts ...grpc.CallOption) (*OperLogPageResp, error)
		OperLogBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
		OperLogClean(ctx context.Context, in *LogCleanReq, opts ...grpc.CallOption) (*Ack, error)
		OperLogUpdate(ctx context.Context, in *OperLogUpdateReq, opts ...grpc.CallOption) (*Ack, error)
		OperLogDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*OperLog, error)
		OperLogDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
	}

	defaultSysService struct {
		cli zrpc.Client
	}
)

func NewSysService(cli zrpc.Client) SysService {
	return &defaultSysService{
		cli: cli,
	}
}

func (m *defaultSysService) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultSysService) DictCreate(ctx context.Context, in *DictCreateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.DictCreate(ctx, in, opts...)
}

func (m *defaultSysService) DictPage(ctx context.Context, in *DictPageReq, opts ...grpc.CallOption) (*DictPageResp, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.DictPage(ctx, in, opts...)
}

func (m *defaultSysService) DictBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.DictBatchDelete(ctx, in, opts...)
}

func (m *defaultSysService) DictType(ctx context.Context, in *DictTypeQueryReq, opts ...grpc.CallOption) (*DictListResp, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.DictType(ctx, in, opts...)
}

func (m *defaultSysService) DictLabel(ctx context.Context, in *DictLabelQueryReq, opts ...grpc.CallOption) (*DictLabelResp, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.DictLabel(ctx, in, opts...)
}

func (m *defaultSysService) DictUpdate(ctx context.Context, in *DictUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.DictUpdate(ctx, in, opts...)
}

func (m *defaultSysService) DictDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Dict, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.DictDetail(ctx, in, opts...)
}

func (m *defaultSysService) DictDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.DictDelete(ctx, in, opts...)
}

func (m *defaultSysService) ConfigCreate(ctx context.Context, in *ConfigCreateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.ConfigCreate(ctx, in, opts...)
}

func (m *defaultSysService) ConfigPage(ctx context.Context, in *ConfigPageReq, opts ...grpc.CallOption) (*ConfigPageResp, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.ConfigPage(ctx, in, opts...)
}

func (m *defaultSysService) ConfigBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.ConfigBatchDelete(ctx, in, opts...)
}

func (m *defaultSysService) ConfigCode(ctx context.Context, in *ConfigCodeQueryReq, opts ...grpc.CallOption) (*ConfigListResp, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.ConfigCode(ctx, in, opts...)
}

func (m *defaultSysService) ConfigData(ctx context.Context, in *ConfigCodeQueryReq, opts ...grpc.CallOption) (*ConfigDataResp, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.ConfigData(ctx, in, opts...)
}

func (m *defaultSysService) ConfigUpdate(ctx context.Context, in *ConfigUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.ConfigUpdate(ctx, in, opts...)
}

func (m *defaultSysService) ConfigDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Config, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.ConfigDetail(ctx, in, opts...)
}

func (m *defaultSysService) ConfigDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.ConfigDelete(ctx, in, opts...)
}

func (m *defaultSysService) LoginLogCreate(ctx context.Context, in *LoginLogReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.LoginLogCreate(ctx, in, opts...)
}

func (m *defaultSysService) LoginLogPage(ctx context.Context, in *LoginLogPageReq, opts ...grpc.CallOption) (*LoginLogPageResp, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.LoginLogPage(ctx, in, opts...)
}

func (m *defaultSysService) LoginLogBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.LoginLogBatchDelete(ctx, in, opts...)
}

func (m *defaultSysService) LoginLogClean(ctx context.Context, in *LogCleanReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.LoginLogClean(ctx, in, opts...)
}

func (m *defaultSysService) LoginLogUpdate(ctx context.Context, in *LoginLogUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.LoginLogUpdate(ctx, in, opts...)
}

func (m *defaultSysService) LoginLogDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*LoginLog, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.LoginLogDetail(ctx, in, opts...)
}

func (m *defaultSysService) LoginLogDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.LoginLogDelete(ctx, in, opts...)
}

func (m *defaultSysService) OperLogCreate(ctx context.Context, in *OperLogReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.OperLogCreate(ctx, in, opts...)
}

func (m *defaultSysService) OperLogBatchCreate(ctx context.Context, in *OperLogBatchReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.OperLogBatchCreate(ctx, in, opts...)
}

func (m *defaultSysService) OperLogPage(ctx context.Context, in *OperLogPageReq, opts ...grpc.CallOption) (*OperLogPageResp, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.OperLogPage(ctx, in, opts...)
}

func (m *defaultSysService) OperLogBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.OperLogBatchDelete(ctx, in, opts...)
}

func (m *defaultSysService) OperLogClean(ctx context.Context, in *LogCleanReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.OperLogClean(ctx, in, opts...)
}

func (m *defaultSysService) OperLogUpdate(ctx context.Context, in *OperLogUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.OperLogUpdate(ctx, in, opts...)
}

func (m *defaultSysService) OperLogDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*OperLog, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.OperLogDetail(ctx, in, opts...)
}

func (m *defaultSysService) OperLogDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewSysServiceClient(m.cli.Conn())
	return client.OperLogDelete(ctx, in, opts...)
}
