// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: resource.proto

package resourceservice

import (
	"context"

	"github.com/gcc798/microservice-kit/application/resource-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Ack                        = pb.Ack
	Attachment                 = pb.Attachment
	AttachmentBindReq          = pb.AttachmentBindReq
	AttachmentBusinessQueryReq = pb.AttachmentBusinessQueryReq
	AttachmentDownloadReq      = pb.AttachmentDownloadReq
	AttachmentDownloadResp     = pb.AttachmentDownloadResp
	AttachmentListResp         = pb.AttachmentListResp
	AttachmentPageReq          = pb.AttachmentPageReq
	AttachmentPageResp         = pb.AttachmentPageResp
	AttachmentUploadReq        = pb.AttachmentUploadReq
	AttachmentUrlQueryReq      = pb.AttachmentUrlQueryReq
	AttachmentUrlResp          = pb.AttachmentUrlResp
	IdReq                      = pb.IdReq
	PageInfo                   = pb.PageInfo
	PingReq                    = pb.PingReq
	PingResp                   = pb.PingResp

	ResourceService interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
		AttachmentUploadFile(ctx context.Context, in *AttachmentUploadReq, opts ...grpc.CallOption) (*Attachment, error)
		AttachmentBind(ctx context.Context, in *AttachmentBindReq, opts ...grpc.CallOption) (*Ack, error)
		AttachmentDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Attachment, error)
		AttachmentBusiness(ctx context.Context, in *AttachmentBusinessQueryReq, opts ...grpc.CallOption) (*AttachmentListResp, error)
		AttachmentPage(ctx context.Context, in *AttachmentPageReq, opts ...grpc.CallOption) (*AttachmentPageResp, error)
		AttachmentDownload(ctx context.Context, in *AttachmentDownloadReq, opts ...grpc.CallOption) (*AttachmentDownloadResp, error)
		AttachmentUrl(ctx context.Context, in *AttachmentUrlQueryReq, opts ...grpc.CallOption) (*AttachmentUrlResp, error)
		AttachmentDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
	}

	defaultResourceService struct {
		cli zrpc.Client
	}
)

func NewResourceService(cli zrpc.Client) ResourceService {
	return &defaultResourceService{
		cli: cli,
	}
}

func (m *defaultResourceService) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultResourceService) AttachmentUploadFile(ctx context.Context, in *AttachmentUploadReq, opts ...grpc.CallOption) (*Attachment, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.AttachmentUploadFile(ctx, in, opts...)
}

func (m *defaultResourceService) AttachmentBind(ctx context.Context, in *AttachmentBindReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.AttachmentBind(ctx, in, opts...)
}

func (m *defaultResourceService) AttachmentDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Attachment, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.AttachmentDetail(ctx, in, opts...)
}

func (m *defaultResourceService) AttachmentBusiness(ctx context.Context, in *AttachmentBusinessQueryReq, opts ...grpc.CallOption) (*AttachmentListResp, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.AttachmentBusiness(ctx, in, opts...)
}

func (m *defaultResourceService) AttachmentPage(ctx context.Context, in *AttachmentPageReq, opts ...grpc.CallOption) (*AttachmentPageResp, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.AttachmentPage(ctx, in, opts...)
}

func (m *defaultResourceService) AttachmentDownload(ctx context.Context, in *AttachmentDownloadReq, opts ...grpc.CallOption) (*AttachmentDownloadResp, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.AttachmentDownload(ctx, in, opts...)
}

func (m *defaultResourceService) AttachmentUrl(ctx context.Context, in *AttachmentUrlQueryReq, opts ...grpc.CallOption) (*AttachmentUrlResp, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.AttachmentUrl(ctx, in, opts...)
}

func (m *defaultResourceService) AttachmentDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.AttachmentDelete(ctx, in, opts...)
}
