// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/sys/v1/sys.proto

package sysv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty 表示成功但没有业务返回值。
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_sys_v1_sys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_v1_sys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_sys_v1_sys_proto_rawDescGZIP(), []int{0}
}

// RecordLoginRequest 是登录日志写入请求。
type RecordLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 是登录日志的全局唯一 ID。
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// user_name 是登录用户名。
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// ip_address 是登录来源 IP 地址。
	IpAddress string `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// browser 是客户端浏览器信息。
	Browser string `protobuf:"bytes,4,opt,name=browser,proto3" json:"browser,omitempty"`
	// os 是客户端操作系统信息。
	Os string `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	// status 是登录结果状态，0 表示成功。
	Status int32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	// message 是登录结果说明或失败原因。
	Message string `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	// login_time_unix_milli 是登录时间的 Unix 毫秒时间戳。
	LoginTimeUnixMilli int64 `protobuf:"varint,8,opt,name=login_time_unix_milli,json=loginTimeUnixMilli,proto3" json:"login_time_unix_milli,omitempty"`
	// client_id 是登录客户端 ID。
	ClientId      string `protobuf:"bytes,9,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordLoginRequest) Reset() {
	*x = RecordLoginRequest{}
	mi := &file_api_sys_v1_sys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordLoginRequest) ProtoMessage() {}

func (x *RecordLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_v1_sys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordLoginRequest.ProtoReflect.Descriptor instead.
func (*RecordLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_sys_v1_sys_proto_rawDescGZIP(), []int{1}
}

func (x *RecordLoginRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecordLoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RecordLoginRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RecordLoginRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *RecordLoginRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RecordLoginRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RecordLoginRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecordLoginRequest) GetLoginTimeUnixMilli() int64 {
	if x != nil {
		return x.LoginTimeUnixMilli
	}
	return 0
}

func (x *RecordLoginRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// OperationLog 表示一条待批量写入的操作日志。
type OperationLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 是操作日志的全局唯一 ID。
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// title 是业务模块标题。
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// business_type 是业务操作类型。
	BusinessType string `protobuf:"bytes,3,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	// method 是服务端处理方法名。
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	// request_method 是 HTTP 请求方法。
	RequestMethod string `protobuf:"bytes,5,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	// device_type 是客户端设备类型。
	DeviceType string `protobuf:"bytes,6,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	// operator_name 是操作用户名。
	OperatorName string `protobuf:"bytes,7,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	// url 是被调用的 HTTP URL。
	Url string `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	// ip_address 是操作来源 IP 地址。
	IpAddress string `protobuf:"bytes,9,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// parameters 是请求参数的序列化内容。
	Parameters string `protobuf:"bytes,10,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// status 是操作结果状态。
	Status string `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	// error_message 是失败时的错误信息。
	ErrorMessage string `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// operation_time_unix_milli 是操作时间的 Unix 毫秒时间戳。
	OperationTimeUnixMilli int64 `protobuf:"varint,13,opt,name=operation_time_unix_milli,json=operationTimeUnixMilli,proto3" json:"operation_time_unix_milli,omitempty"`
	// cost_millis 是请求耗时，单位为毫秒。
	CostMillis int64 `protobuf:"varint,14,opt,name=cost_millis,json=costMillis,proto3" json:"cost_millis,omitempty"`
	// user_agent 是客户端 User-Agent。
	UserAgent     string `protobuf:"bytes,15,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLog) Reset() {
	*x = OperationLog{}
	mi := &file_api_sys_v1_sys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLog) ProtoMessage() {}

func (x *OperationLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_v1_sys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLog.ProtoReflect.Descriptor instead.
func (*OperationLog) Descriptor() ([]byte, []int) {
	return file_api_sys_v1_sys_proto_rawDescGZIP(), []int{2}
}

func (x *OperationLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperationLog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OperationLog) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *OperationLog) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OperationLog) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *OperationLog) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *OperationLog) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *OperationLog) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OperationLog) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *OperationLog) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

func (x *OperationLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperationLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *OperationLog) GetOperationTimeUnixMilli() int64 {
	if x != nil {
		return x.OperationTimeUnixMilli
	}
	return 0
}

func (x *OperationLog) GetCostMillis() int64 {
	if x != nil {
		return x.CostMillis
	}
	return 0
}

func (x *OperationLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// RecordOperationsRequest 是操作日志批量写入请求。
type RecordOperationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// logs 是待写入的操作日志列表。
	Logs          []*OperationLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordOperationsRequest) Reset() {
	*x = RecordOperationsRequest{}
	mi := &file_api_sys_v1_sys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordOperationsRequest) ProtoMessage() {}

func (x *RecordOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sys_v1_sys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordOperationsRequest.ProtoReflect.Descriptor instead.
func (*RecordOperationsRequest) Descriptor() ([]byte, []int) {
	return file_api_sys_v1_sys_proto_rawDescGZIP(), []int{3}
}

func (x *RecordOperationsRequest) GetLogs() []*OperationLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_api_sys_v1_sys_proto protoreflect.FileDescriptor

const file_api_sys_v1_sys_proto_rawDesc = "" +
	"\n" +
	"\x14api/sys/v1/sys.proto\x12\x17microservice_kit.sys.v1\"\a\n" +
	"\x05Empty\"\x8c\x02\n" +
	"\x12RecordLoginRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x18\n" +
	"\abrowser\x18\x04 \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x121\n" +
	"\x15login_time_unix_milli\x18\b \x01(\x03R\x12loginTimeUnixMilli\x12\x1b\n" +
	"\tclient_id\x18\t \x01(\tR\bclientId\"\xe7\x03\n" +
	"\fOperationLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rbusiness_type\x18\x03 \x01(\tR\fbusinessType\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12%\n" +
	"\x0erequest_method\x18\x05 \x01(\tR\rrequestMethod\x12\x1f\n" +
	"\vdevice_type\x18\x06 \x01(\tR\n" +
	"deviceType\x12#\n" +
	"\roperator_name\x18\a \x01(\tR\foperatorName\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"ip_address\x18\t \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"parameters\x18\n" +
	" \x01(\tR\n" +
	"parameters\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\x129\n" +
	"\x19operation_time_unix_milli\x18\r \x01(\x03R\x16operationTimeUnixMilli\x12\x1f\n" +
	"\vcost_millis\x18\x0e \x01(\x03R\n" +
	"costMillis\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x0f \x01(\tR\tuserAgent\"T\n" +
	"\x17RecordOperationsRequest\x129\n" +
	"\x04logs\x18\x01 \x03(\v2%.microservice_kit.sys.v1.OperationLogR\x04logs2\xd1\x01\n" +
	"\rSystemService\x12Z\n" +
	"\vRecordLogin\x12+.microservice_kit.sys.v1.RecordLoginRequest\x1a\x1e.microservice_kit.sys.v1.Empty\x12d\n" +
	"\x10RecordOperations\x120.microservice_kit.sys.v1.RecordOperationsRequest\x1a\x1e.microservice_kit.sys.v1.EmptyB>Z<github.com/gcc798/microservice-kit/internal/api/sys/v1;sysv1b\x06proto3"

var (
	file_api_sys_v1_sys_proto_rawDescOnce sync.Once
	file_api_sys_v1_sys_proto_rawDescData []byte
)

func file_api_sys_v1_sys_proto_rawDescGZIP() []byte {
	file_api_sys_v1_sys_proto_rawDescOnce.Do(func() {
		file_api_sys_v1_sys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sys_v1_sys_proto_rawDesc), len(file_api_sys_v1_sys_proto_rawDesc)))
	})
	return file_api_sys_v1_sys_proto_rawDescData
}

var file_api_sys_v1_sys_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_sys_v1_sys_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: microservice_kit.sys.v1.Empty
	(*RecordLoginRequest)(nil),      // 1: microservice_kit.sys.v1.RecordLoginRequest
	(*OperationLog)(nil),            // 2: microservice_kit.sys.v1.OperationLog
	(*RecordOperationsRequest)(nil), // 3: microservice_kit.sys.v1.RecordOperationsRequest
}
var file_api_sys_v1_sys_proto_depIdxs = []int32{
	2, // 0: microservice_kit.sys.v1.RecordOperationsRequest.logs:type_name -> microservice_kit.sys.v1.OperationLog
	1, // 1: microservice_kit.sys.v1.SystemService.RecordLogin:input_type -> microservice_kit.sys.v1.RecordLoginRequest
	3, // 2: microservice_kit.sys.v1.SystemService.RecordOperations:input_type -> microservice_kit.sys.v1.RecordOperationsRequest
	0, // 3: microservice_kit.sys.v1.SystemService.RecordLogin:output_type -> microservice_kit.sys.v1.Empty
	0, // 4: microservice_kit.sys.v1.SystemService.RecordOperations:output_type -> microservice_kit.sys.v1.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_sys_v1_sys_proto_init() }
func file_api_sys_v1_sys_proto_init() {
	if File_api_sys_v1_sys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sys_v1_sys_proto_rawDesc), len(file_api_sys_v1_sys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sys_v1_sys_proto_goTypes,
		DependencyIndexes: file_api_sys_v1_sys_proto_depIdxs,
		MessageInfos:      file_api_sys_v1_sys_proto_msgTypes,
	}.Build()
	File_api_sys_v1_sys_proto = out.File
	file_api_sys_v1_sys_proto_goTypes = nil
	file_api_sys_v1_sys_proto_depIdxs = nil
}
