// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: iam.proto

package server

import (
	"context"

	"github.com/gcc798/microservice-kit/application/iam-rpc/internal/logic/iamservice"
	"github.com/gcc798/microservice-kit/application/iam-rpc/internal/svc"
	"github.com/gcc798/microservice-kit/application/iam-rpc/pb"
)

type IamServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIamServiceServer
}

func NewIamServiceServer(svcCtx *svc.ServiceContext) *IamServiceServer {
	return &IamServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *IamServiceServer) Ping(ctx context.Context, in *pb.PingReq) (*pb.PingResp, error) {
	l := iamservicelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *IamServiceServer) ValidateAccessToken(ctx context.Context, in *pb.ValidateAccessTokenReq) (*pb.ValidateAccessTokenResp, error) {
	l := iamservicelogic.NewValidateAccessTokenLogic(ctx, s.svcCtx)
	return l.ValidateAccessToken(in)
}

func (s *IamServiceServer) CheckPermission(ctx context.Context, in *pb.CheckPermissionReq) (*pb.CheckPermissionResp, error) {
	l := iamservicelogic.NewCheckPermissionLogic(ctx, s.svcCtx)
	return l.CheckPermission(in)
}

func (s *IamServiceServer) AuthLogin(ctx context.Context, in *pb.AuthLoginReq) (*pb.AuthLoginResp, error) {
	l := iamservicelogic.NewAuthLoginLogic(ctx, s.svcCtx)
	return l.AuthLogin(in)
}

func (s *IamServiceServer) UserProfile(ctx context.Context, in *pb.IdReq) (*pb.User, error) {
	l := iamservicelogic.NewUserProfileLogic(ctx, s.svcCtx)
	return l.UserProfile(in)
}

func (s *IamServiceServer) UserAuthContext(ctx context.Context, in *pb.UserAuthContextReq) (*pb.UserAuthContextResp, error) {
	l := iamservicelogic.NewUserAuthContextLogic(ctx, s.svcCtx)
	return l.UserAuthContext(in)
}

func (s *IamServiceServer) UserCreate(ctx context.Context, in *pb.UserCreateReq) (*pb.Ack, error) {
	l := iamservicelogic.NewUserCreateLogic(ctx, s.svcCtx)
	return l.UserCreate(in)
}

func (s *IamServiceServer) UserImport(ctx context.Context, in *pb.UserImportReq) (*pb.Ack, error) {
	l := iamservicelogic.NewUserImportLogic(ctx, s.svcCtx)
	return l.UserImport(in)
}

func (s *IamServiceServer) UserPage(ctx context.Context, in *pb.UserPageReq) (*pb.UserPageResp, error) {
	l := iamservicelogic.NewUserPageLogic(ctx, s.svcCtx)
	return l.UserPage(in)
}

func (s *IamServiceServer) UserBatchDelete(ctx context.Context, in *pb.BatchIdsReq) (*pb.Ack, error) {
	l := iamservicelogic.NewUserBatchDeleteLogic(ctx, s.svcCtx)
	return l.UserBatchDelete(in)
}

func (s *IamServiceServer) UserChangePassword(ctx context.Context, in *pb.UserChangePasswordReq) (*pb.Ack, error) {
	l := iamservicelogic.NewUserChangePasswordLogic(ctx, s.svcCtx)
	return l.UserChangePassword(in)
}

func (s *IamServiceServer) UserUpdate(ctx context.Context, in *pb.UserUpdateReq) (*pb.Ack, error) {
	l := iamservicelogic.NewUserUpdateLogic(ctx, s.svcCtx)
	return l.UserUpdate(in)
}

func (s *IamServiceServer) UserResetPassword(ctx context.Context, in *pb.UserPasswordReq) (*pb.Ack, error) {
	l := iamservicelogic.NewUserResetPasswordLogic(ctx, s.svcCtx)
	return l.UserResetPassword(in)
}

func (s *IamServiceServer) UserDetail(ctx context.Context, in *pb.IdReq) (*pb.User, error) {
	l := iamservicelogic.NewUserDetailLogic(ctx, s.svcCtx)
	return l.UserDetail(in)
}

func (s *IamServiceServer) UserDelete(ctx context.Context, in *pb.IdReq) (*pb.Ack, error) {
	l := iamservicelogic.NewUserDeleteLogic(ctx, s.svcCtx)
	return l.UserDelete(in)
}

func (s *IamServiceServer) RoleCreate(ctx context.Context, in *pb.RoleCreateReq) (*pb.Ack, error) {
	l := iamservicelogic.NewRoleCreateLogic(ctx, s.svcCtx)
	return l.RoleCreate(in)
}

func (s *IamServiceServer) RolePage(ctx context.Context, in *pb.RolePageReq) (*pb.RolePageResp, error) {
	l := iamservicelogic.NewRolePageLogic(ctx, s.svcCtx)
	return l.RolePage(in)
}

func (s *IamServiceServer) RoleAssign(ctx context.Context, in *pb.AssignRoleReq) (*pb.Ack, error) {
	l := iamservicelogic.NewRoleAssignLogic(ctx, s.svcCtx)
	return l.RoleAssign(in)
}

func (s *IamServiceServer) RoleRemove(ctx context.Context, in *pb.RemoveRoleReq) (*pb.Ack, error) {
	l := iamservicelogic.NewRoleRemoveLogic(ctx, s.svcCtx)
	return l.RoleRemove(in)
}

func (s *IamServiceServer) RoleUser(ctx context.Context, in *pb.UserRoleQueryReq) (*pb.RoleListResp, error) {
	l := iamservicelogic.NewRoleUserLogic(ctx, s.svcCtx)
	return l.RoleUser(in)
}

func (s *IamServiceServer) RoleUsers(ctx context.Context, in *pb.RoleUsersReq) (*pb.UserListResp, error) {
	l := iamservicelogic.NewRoleUsersLogic(ctx, s.svcCtx)
	return l.RoleUsers(in)
}

func (s *IamServiceServer) RoleAssignUsers(ctx context.Context, in *pb.RoleUsersReq) (*pb.Ack, error) {
	l := iamservicelogic.NewRoleAssignUsersLogic(ctx, s.svcCtx)
	return l.RoleAssignUsers(in)
}

func (s *IamServiceServer) RoleRemoveUsers(ctx context.Context, in *pb.RoleUsersReq) (*pb.Ack, error) {
	l := iamservicelogic.NewRoleRemoveUsersLogic(ctx, s.svcCtx)
	return l.RoleRemoveUsers(in)
}

func (s *IamServiceServer) RoleMenus(ctx context.Context, in *pb.RoleMenusReq) (*pb.MenuIdsResp, error) {
	l := iamservicelogic.NewRoleMenusLogic(ctx, s.svcCtx)
	return l.RoleMenus(in)
}

func (s *IamServiceServer) RoleAssignMenus(ctx context.Context, in *pb.RoleMenusAssignReq) (*pb.Ack, error) {
	l := iamservicelogic.NewRoleAssignMenusLogic(ctx, s.svcCtx)
	return l.RoleAssignMenus(in)
}

func (s *IamServiceServer) RoleUpdate(ctx context.Context, in *pb.RoleUpdateReq) (*pb.Ack, error) {
	l := iamservicelogic.NewRoleUpdateLogic(ctx, s.svcCtx)
	return l.RoleUpdate(in)
}

func (s *IamServiceServer) RoleDetail(ctx context.Context, in *pb.IdReq) (*pb.Role, error) {
	l := iamservicelogic.NewRoleDetailLogic(ctx, s.svcCtx)
	return l.RoleDetail(in)
}

func (s *IamServiceServer) RoleDelete(ctx context.Context, in *pb.IdReq) (*pb.Ack, error) {
	l := iamservicelogic.NewRoleDeleteLogic(ctx, s.svcCtx)
	return l.RoleDelete(in)
}

func (s *IamServiceServer) ApiPermissionTree(ctx context.Context, in *pb.Empty) (*pb.ApiPermissionListResp, error) {
	l := iamservicelogic.NewApiPermissionTreeLogic(ctx, s.svcCtx)
	return l.ApiPermissionTree(in)
}

func (s *IamServiceServer) ApiPermissionList(ctx context.Context, in *pb.Empty) (*pb.ApiPermissionListResp, error) {
	l := iamservicelogic.NewApiPermissionListLogic(ctx, s.svcCtx)
	return l.ApiPermissionList(in)
}

func (s *IamServiceServer) ApiPermissionCreate(ctx context.Context, in *pb.ApiPermissionSaveReq) (*pb.ApiPermission, error) {
	l := iamservicelogic.NewApiPermissionCreateLogic(ctx, s.svcCtx)
	return l.ApiPermissionCreate(in)
}

func (s *IamServiceServer) ApiPermissionUpdate(ctx context.Context, in *pb.ApiPermissionSaveReq) (*pb.Ack, error) {
	l := iamservicelogic.NewApiPermissionUpdateLogic(ctx, s.svcCtx)
	return l.ApiPermissionUpdate(in)
}

func (s *IamServiceServer) ApiPermissionDelete(ctx context.Context, in *pb.IdReq) (*pb.Ack, error) {
	l := iamservicelogic.NewApiPermissionDeleteLogic(ctx, s.svcCtx)
	return l.ApiPermissionDelete(in)
}

func (s *IamServiceServer) RoleApiPermissions(ctx context.Context, in *pb.IdReq) (*pb.ApiPermissionIdsResp, error) {
	l := iamservicelogic.NewRoleApiPermissionsLogic(ctx, s.svcCtx)
	return l.RoleApiPermissions(in)
}

func (s *IamServiceServer) RoleApiPermissionsAssign(ctx context.Context, in *pb.RoleApiPermissionsReq) (*pb.Ack, error) {
	l := iamservicelogic.NewRoleApiPermissionsAssignLogic(ctx, s.svcCtx)
	return l.RoleApiPermissionsAssign(in)
}

func (s *IamServiceServer) UserApiPermissions(ctx context.Context, in *pb.IdReq) (*pb.ApiPermissionIdsResp, error) {
	l := iamservicelogic.NewUserApiPermissionsLogic(ctx, s.svcCtx)
	return l.UserApiPermissions(in)
}

func (s *IamServiceServer) UserApiPermissionsAssign(ctx context.Context, in *pb.UserApiPermissionsReq) (*pb.Ack, error) {
	l := iamservicelogic.NewUserApiPermissionsAssignLogic(ctx, s.svcCtx)
	return l.UserApiPermissionsAssign(in)
}

func (s *IamServiceServer) OrgCreate(ctx context.Context, in *pb.OrgCreateReq) (*pb.Ack, error) {
	l := iamservicelogic.NewOrgCreateLogic(ctx, s.svcCtx)
	return l.OrgCreate(in)
}

func (s *IamServiceServer) OrgPage(ctx context.Context, in *pb.OrgPageReq) (*pb.OrgPageResp, error) {
	l := iamservicelogic.NewOrgPageLogic(ctx, s.svcCtx)
	return l.OrgPage(in)
}

func (s *IamServiceServer) OrgTree(ctx context.Context, in *pb.Empty) (*pb.OrgTreeResp, error) {
	l := iamservicelogic.NewOrgTreeLogic(ctx, s.svcCtx)
	return l.OrgTree(in)
}

func (s *IamServiceServer) OrgBatchDelete(ctx context.Context, in *pb.BatchIdsReq) (*pb.Ack, error) {
	l := iamservicelogic.NewOrgBatchDeleteLogic(ctx, s.svcCtx)
	return l.OrgBatchDelete(in)
}

func (s *IamServiceServer) OrgUpdate(ctx context.Context, in *pb.OrgUpdateReq) (*pb.Ack, error) {
	l := iamservicelogic.NewOrgUpdateLogic(ctx, s.svcCtx)
	return l.OrgUpdate(in)
}

func (s *IamServiceServer) OrgDetail(ctx context.Context, in *pb.IdReq) (*pb.Org, error) {
	l := iamservicelogic.NewOrgDetailLogic(ctx, s.svcCtx)
	return l.OrgDetail(in)
}

func (s *IamServiceServer) OrgDelete(ctx context.Context, in *pb.IdReq) (*pb.Ack, error) {
	l := iamservicelogic.NewOrgDeleteLogic(ctx, s.svcCtx)
	return l.OrgDelete(in)
}

func (s *IamServiceServer) MenuUserTree(ctx context.Context, in *pb.IdReq) (*pb.MenuListResp, error) {
	l := iamservicelogic.NewMenuUserTreeLogic(ctx, s.svcCtx)
	return l.MenuUserTree(in)
}

func (s *IamServiceServer) MenuTree(ctx context.Context, in *pb.Empty) (*pb.MenuListResp, error) {
	l := iamservicelogic.NewMenuTreeLogic(ctx, s.svcCtx)
	return l.MenuTree(in)
}

func (s *IamServiceServer) MenuList(ctx context.Context, in *pb.Empty) (*pb.MenuListResp, error) {
	l := iamservicelogic.NewMenuListLogic(ctx, s.svcCtx)
	return l.MenuList(in)
}

func (s *IamServiceServer) MenuDetail(ctx context.Context, in *pb.IdReq) (*pb.Menu, error) {
	l := iamservicelogic.NewMenuDetailLogic(ctx, s.svcCtx)
	return l.MenuDetail(in)
}

func (s *IamServiceServer) MenuCreate(ctx context.Context, in *pb.MenuReq) (*pb.Ack, error) {
	l := iamservicelogic.NewMenuCreateLogic(ctx, s.svcCtx)
	return l.MenuCreate(in)
}

func (s *IamServiceServer) MenuUpdate(ctx context.Context, in *pb.MenuReq) (*pb.Ack, error) {
	l := iamservicelogic.NewMenuUpdateLogic(ctx, s.svcCtx)
	return l.MenuUpdate(in)
}

func (s *IamServiceServer) MenuDelete(ctx context.Context, in *pb.IdReq) (*pb.Ack, error) {
	l := iamservicelogic.NewMenuDeleteLogic(ctx, s.svcCtx)
	return l.MenuDelete(in)
}

func (s *IamServiceServer) CaptchaEnabledTypes(ctx context.Context, in *pb.CaptchaReq) (*pb.CaptchaTypesResp, error) {
	l := iamservicelogic.NewCaptchaEnabledTypesLogic(ctx, s.svcCtx)
	return l.CaptchaEnabledTypes(in)
}

func (s *IamServiceServer) CaptchaImage(ctx context.Context, in *pb.CaptchaReq) (*pb.CaptchaDataResp, error) {
	l := iamservicelogic.NewCaptchaImageLogic(ctx, s.svcCtx)
	return l.CaptchaImage(in)
}

func (s *IamServiceServer) CaptchaSms(ctx context.Context, in *pb.CaptchaPhoneReq) (*pb.CaptchaDataResp, error) {
	l := iamservicelogic.NewCaptchaSmsLogic(ctx, s.svcCtx)
	return l.CaptchaSms(in)
}

func (s *IamServiceServer) CaptchaEmail(ctx context.Context, in *pb.CaptchaEmailReq) (*pb.CaptchaDataResp, error) {
	l := iamservicelogic.NewCaptchaEmailLogic(ctx, s.svcCtx)
	return l.CaptchaEmail(in)
}
