// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/resource/v1/resource.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_resource_v1_resource_proto protoreflect.FileDescriptor

const file_api_resource_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/resource/v1/resource.proto\x12\x1cmicroservice_kit.resource.v12\x11\n" +
	"\x0fResourceServiceBHZFgithub.com/gcc798/microservice-kit/internal/api/resource/v1;resourcev1b\x06proto3"

var file_api_resource_v1_resource_proto_goTypes = []any{}
var file_api_resource_v1_resource_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_resource_v1_resource_proto_init() }
func file_api_resource_v1_resource_proto_init() {
	if File_api_resource_v1_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_resource_v1_resource_proto_rawDesc), len(file_api_resource_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_resource_v1_resource_proto_goTypes,
		DependencyIndexes: file_api_resource_v1_resource_proto_depIdxs,
	}.Build()
	File_api_resource_v1_resource_proto = out.File
	file_api_resource_v1_resource_proto_goTypes = nil
	file_api_resource_v1_resource_proto_depIdxs = nil
}
