// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: resource.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Ack) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{1}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{2}
}

func (x *PingResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdReq) Reset() {
	*x = IdReq{}
	mi := &file_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReq) ProtoMessage() {}

func (x *IdReq) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReq.ProtoReflect.Descriptor instead.
func (*IdReq) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{3}
}

func (x *IdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Current       int64                  `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	Pages         int64                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{4}
}

func (x *PageInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageInfo) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *PageInfo) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  int64                  `protobuf:"varint,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileKey       string                 `protobuf:"bytes,3,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileType      string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileExt       string                 `protobuf:"bytes,6,opt,name=file_ext,json=fileExt,proto3" json:"file_ext,omitempty"`
	BusinessType  string                 `protobuf:"bytes,7,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	BusinessId    string                 `protobuf:"bytes,8,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	BusinessField string                 `protobuf:"bytes,9,opt,name=business_field,json=businessField,proto3" json:"business_field,omitempty"`
	IsPublic      bool                   `protobuf:"varint,10,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	AccessUrl     string                 `protobuf:"bytes,11,opt,name=access_url,json=accessUrl,proto3" json:"access_url,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,12,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Status        int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,14,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	CreateBy      int64                  `protobuf:"varint,15,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	CreateTime    string                 `protobuf:"bytes,16,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,17,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{5}
}

func (x *Attachment) GetAttachmentId() int64 {
	if x != nil {
		return x.AttachmentId
	}
	return 0
}

func (x *Attachment) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Attachment) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *Attachment) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Attachment) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Attachment) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

func (x *Attachment) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *Attachment) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *Attachment) GetBusinessField() string {
	if x != nil {
		return x.BusinessField
	}
	return ""
}

func (x *Attachment) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Attachment) GetAccessUrl() string {
	if x != nil {
		return x.AccessUrl
	}
	return ""
}

func (x *Attachment) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *Attachment) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Attachment) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *Attachment) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *Attachment) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Attachment) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type AttachmentPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	BusinessType  string                 `protobuf:"bytes,5,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentPageReq) Reset() {
	*x = AttachmentPageReq{}
	mi := &file_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentPageReq) ProtoMessage() {}

func (x *AttachmentPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentPageReq.ProtoReflect.Descriptor instead.
func (*AttachmentPageReq) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{6}
}

func (x *AttachmentPageReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *AttachmentPageReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AttachmentPageReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AttachmentPageReq) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *AttachmentPageReq) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

type AttachmentUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentUploadReq) Reset() {
	*x = AttachmentUploadReq{}
	mi := &file_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentUploadReq) ProtoMessage() {}

func (x *AttachmentUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentUploadReq.ProtoReflect.Descriptor instead.
func (*AttachmentUploadReq) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{7}
}

func (x *AttachmentUploadReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AttachmentUploadReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AttachmentUploadReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type AttachmentBindReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  int64                  `protobuf:"varint,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	BusinessType  string                 `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	BusinessId    string                 `protobuf:"bytes,3,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	BusinessField string                 `protobuf:"bytes,4,opt,name=business_field,json=businessField,proto3" json:"business_field,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,7,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentBindReq) Reset() {
	*x = AttachmentBindReq{}
	mi := &file_resource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentBindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentBindReq) ProtoMessage() {}

func (x *AttachmentBindReq) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentBindReq.ProtoReflect.Descriptor instead.
func (*AttachmentBindReq) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{8}
}

func (x *AttachmentBindReq) GetAttachmentId() int64 {
	if x != nil {
		return x.AttachmentId
	}
	return 0
}

func (x *AttachmentBindReq) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *AttachmentBindReq) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *AttachmentBindReq) GetBusinessField() string {
	if x != nil {
		return x.BusinessField
	}
	return ""
}

func (x *AttachmentBindReq) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *AttachmentBindReq) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *AttachmentBindReq) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

type AttachmentBusinessQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessType  string                 `protobuf:"bytes,1,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentBusinessQueryReq) Reset() {
	*x = AttachmentBusinessQueryReq{}
	mi := &file_resource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentBusinessQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentBusinessQueryReq) ProtoMessage() {}

func (x *AttachmentBusinessQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentBusinessQueryReq.ProtoReflect.Descriptor instead.
func (*AttachmentBusinessQueryReq) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{9}
}

func (x *AttachmentBusinessQueryReq) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *AttachmentBusinessQueryReq) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

type AttachmentUrlQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  int64                  `protobuf:"varint,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	Expires       int64                  `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentUrlQueryReq) Reset() {
	*x = AttachmentUrlQueryReq{}
	mi := &file_resource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentUrlQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentUrlQueryReq) ProtoMessage() {}

func (x *AttachmentUrlQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentUrlQueryReq.ProtoReflect.Descriptor instead.
func (*AttachmentUrlQueryReq) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{10}
}

func (x *AttachmentUrlQueryReq) GetAttachmentId() int64 {
	if x != nil {
		return x.AttachmentId
	}
	return 0
}

func (x *AttachmentUrlQueryReq) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

type AttachmentUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  int64                  `protobuf:"varint,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Expires       int64                  `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentUrlResp) Reset() {
	*x = AttachmentUrlResp{}
	mi := &file_resource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentUrlResp) ProtoMessage() {}

func (x *AttachmentUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentUrlResp.ProtoReflect.Descriptor instead.
func (*AttachmentUrlResp) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{11}
}

func (x *AttachmentUrlResp) GetAttachmentId() int64 {
	if x != nil {
		return x.AttachmentId
	}
	return 0
}

func (x *AttachmentUrlResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AttachmentUrlResp) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

type AttachmentDownloadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  int64                  `protobuf:"varint,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentDownloadReq) Reset() {
	*x = AttachmentDownloadReq{}
	mi := &file_resource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentDownloadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentDownloadReq) ProtoMessage() {}

func (x *AttachmentDownloadReq) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentDownloadReq.ProtoReflect.Descriptor instead.
func (*AttachmentDownloadReq) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{12}
}

func (x *AttachmentDownloadReq) GetAttachmentId() int64 {
	if x != nil {
		return x.AttachmentId
	}
	return 0
}

type AttachmentDownloadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentDownloadResp) Reset() {
	*x = AttachmentDownloadResp{}
	mi := &file_resource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentDownloadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentDownloadResp) ProtoMessage() {}

func (x *AttachmentDownloadResp) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentDownloadResp.ProtoReflect.Descriptor instead.
func (*AttachmentDownloadResp) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{13}
}

func (x *AttachmentDownloadResp) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AttachmentDownloadResp) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AttachmentDownloadResp) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type AttachmentPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Attachment          `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentPageResp) Reset() {
	*x = AttachmentPageResp{}
	mi := &file_resource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentPageResp) ProtoMessage() {}

func (x *AttachmentPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentPageResp.ProtoReflect.Descriptor instead.
func (*AttachmentPageResp) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{14}
}

func (x *AttachmentPageResp) GetRecords() []*Attachment {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *AttachmentPageResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type AttachmentListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Attachment          `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentListResp) Reset() {
	*x = AttachmentListResp{}
	mi := &file_resource_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentListResp) ProtoMessage() {}

func (x *AttachmentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentListResp.ProtoReflect.Descriptor instead.
func (*AttachmentListResp) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{15}
}

func (x *AttachmentListResp) GetRecords() []*Attachment {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_resource_proto protoreflect.FileDescriptor

const file_resource_proto_rawDesc = "" +
	"\n" +
	"\x0eresource.proto\x12\bresource\"\x17\n" +
	"\x03Ack\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\t\n" +
	"\aPingReq\"$\n" +
	"\bPingResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x17\n" +
	"\x05IdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"d\n" +
	"\bPageInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\x03R\acurrent\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x03R\x05pages\"\xa4\x04\n" +
	"\n" +
	"Attachment\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\x03R\fattachmentId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x19\n" +
	"\bfile_key\x18\x03 \x01(\tR\afileKey\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12\x19\n" +
	"\bfile_ext\x18\x06 \x01(\tR\afileExt\x12#\n" +
	"\rbusiness_type\x18\a \x01(\tR\fbusinessType\x12\x1f\n" +
	"\vbusiness_id\x18\b \x01(\tR\n" +
	"businessId\x12%\n" +
	"\x0ebusiness_field\x18\t \x01(\tR\rbusinessField\x12\x1b\n" +
	"\tis_public\x18\n" +
	" \x01(\bR\bisPublic\x12\x1d\n" +
	"\n" +
	"access_url\x18\v \x01(\tR\taccessUrl\x12#\n" +
	"\rmetadata_json\x18\f \x01(\tR\fmetadataJson\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12\x1f\n" +
	"\vexpire_time\x18\x0e \x01(\tR\n" +
	"expireTime\x12\x1b\n" +
	"\tcreate_by\x18\x0f \x01(\x03R\bcreateBy\x12\x1f\n" +
	"\vcreate_time\x18\x10 \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x11 \x01(\tR\n" +
	"updateTime\"\xaa\x01\n" +
	"\x11AttachmentPageReq\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\x12#\n" +
	"\rbusiness_type\x18\x05 \x01(\tR\fbusinessType\"o\n" +
	"\x13AttachmentUploadReq\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\x88\x02\n" +
	"\x11AttachmentBindReq\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\x03R\fattachmentId\x12#\n" +
	"\rbusiness_type\x18\x02 \x01(\tR\fbusinessType\x12\x1f\n" +
	"\vbusiness_id\x18\x03 \x01(\tR\n" +
	"businessId\x12%\n" +
	"\x0ebusiness_field\x18\x04 \x01(\tR\rbusinessField\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12#\n" +
	"\rmetadata_json\x18\x06 \x01(\tR\fmetadataJson\x12\x1f\n" +
	"\vexpire_time\x18\a \x01(\tR\n" +
	"expireTime\"b\n" +
	"\x1aAttachmentBusinessQueryReq\x12#\n" +
	"\rbusiness_type\x18\x01 \x01(\tR\fbusinessType\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\"V\n" +
	"\x15AttachmentUrlQueryReq\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\x03R\fattachmentId\x12\x18\n" +
	"\aexpires\x18\x02 \x01(\x03R\aexpires\"d\n" +
	"\x11AttachmentUrlResp\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\x03R\fattachmentId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\aexpires\x18\x03 \x01(\x03R\aexpires\"<\n" +
	"\x15AttachmentDownloadReq\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\x03R\fattachmentId\"r\n" +
	"\x16AttachmentDownloadResp\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"l\n" +
	"\x12AttachmentPageResp\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.resource.AttachmentR\arecords\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.resource.PageInfoR\x04page\"D\n" +
	"\x12AttachmentListResp\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.resource.AttachmentR\arecords2\x89\x05\n" +
	"\x0fResourceService\x12-\n" +
	"\x04Ping\x12\x11.resource.PingReq\x1a\x12.resource.PingResp\x12K\n" +
	"\x14AttachmentUploadFile\x12\x1d.resource.AttachmentUploadReq\x1a\x14.resource.Attachment\x12<\n" +
	"\x0eAttachmentBind\x12\x1b.resource.AttachmentBindReq\x1a\r.resource.Ack\x129\n" +
	"\x10AttachmentDetail\x12\x0f.resource.IdReq\x1a\x14.resource.Attachment\x12X\n" +
	"\x12AttachmentBusiness\x12$.resource.AttachmentBusinessQueryReq\x1a\x1c.resource.AttachmentListResp\x12K\n" +
	"\x0eAttachmentPage\x12\x1b.resource.AttachmentPageReq\x1a\x1c.resource.AttachmentPageResp\x12W\n" +
	"\x12AttachmentDownload\x12\x1f.resource.AttachmentDownloadReq\x1a .resource.AttachmentDownloadResp\x12M\n" +
	"\rAttachmentUrl\x12\x1f.resource.AttachmentUrlQueryReq\x1a\x1b.resource.AttachmentUrlResp\x122\n" +
	"\x10AttachmentDelete\x12\x0f.resource.IdReq\x1a\r.resource.AckB@Z>github.com/gcc798/microservice-kit/application/resource-rpc/pbb\x06proto3"

var (
	file_resource_proto_rawDescOnce sync.Once
	file_resource_proto_rawDescData []byte
)

func file_resource_proto_rawDescGZIP() []byte {
	file_resource_proto_rawDescOnce.Do(func() {
		file_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_proto_rawDesc), len(file_resource_proto_rawDesc)))
	})
	return file_resource_proto_rawDescData
}

var file_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_resource_proto_goTypes = []any{
	(*Ack)(nil),                        // 0: resource.Ack
	(*PingReq)(nil),                    // 1: resource.PingReq
	(*PingResp)(nil),                   // 2: resource.PingResp
	(*IdReq)(nil),                      // 3: resource.IdReq
	(*PageInfo)(nil),                   // 4: resource.PageInfo
	(*Attachment)(nil),                 // 5: resource.Attachment
	(*AttachmentPageReq)(nil),          // 6: resource.AttachmentPageReq
	(*AttachmentUploadReq)(nil),        // 7: resource.AttachmentUploadReq
	(*AttachmentBindReq)(nil),          // 8: resource.AttachmentBindReq
	(*AttachmentBusinessQueryReq)(nil), // 9: resource.AttachmentBusinessQueryReq
	(*AttachmentUrlQueryReq)(nil),      // 10: resource.AttachmentUrlQueryReq
	(*AttachmentUrlResp)(nil),          // 11: resource.AttachmentUrlResp
	(*AttachmentDownloadReq)(nil),      // 12: resource.AttachmentDownloadReq
	(*AttachmentDownloadResp)(nil),     // 13: resource.AttachmentDownloadResp
	(*AttachmentPageResp)(nil),         // 14: resource.AttachmentPageResp
	(*AttachmentListResp)(nil),         // 15: resource.AttachmentListResp
}
var file_resource_proto_depIdxs = []int32{
	5,  // 0: resource.AttachmentPageResp.records:type_name -> resource.Attachment
	4,  // 1: resource.AttachmentPageResp.page:type_name -> resource.PageInfo
	5,  // 2: resource.AttachmentListResp.records:type_name -> resource.Attachment
	1,  // 3: resource.ResourceService.Ping:input_type -> resource.PingReq
	7,  // 4: resource.ResourceService.AttachmentUploadFile:input_type -> resource.AttachmentUploadReq
	8,  // 5: resource.ResourceService.AttachmentBind:input_type -> resource.AttachmentBindReq
	3,  // 6: resource.ResourceService.AttachmentDetail:input_type -> resource.IdReq
	9,  // 7: resource.ResourceService.AttachmentBusiness:input_type -> resource.AttachmentBusinessQueryReq
	6,  // 8: resource.ResourceService.AttachmentPage:input_type -> resource.AttachmentPageReq
	12, // 9: resource.ResourceService.AttachmentDownload:input_type -> resource.AttachmentDownloadReq
	10, // 10: resource.ResourceService.AttachmentUrl:input_type -> resource.AttachmentUrlQueryReq
	3,  // 11: resource.ResourceService.AttachmentDelete:input_type -> resource.IdReq
	2,  // 12: resource.ResourceService.Ping:output_type -> resource.PingResp
	5,  // 13: resource.ResourceService.AttachmentUploadFile:output_type -> resource.Attachment
	0,  // 14: resource.ResourceService.AttachmentBind:output_type -> resource.Ack
	5,  // 15: resource.ResourceService.AttachmentDetail:output_type -> resource.Attachment
	15, // 16: resource.ResourceService.AttachmentBusiness:output_type -> resource.AttachmentListResp
	14, // 17: resource.ResourceService.AttachmentPage:output_type -> resource.AttachmentPageResp
	13, // 18: resource.ResourceService.AttachmentDownload:output_type -> resource.AttachmentDownloadResp
	11, // 19: resource.ResourceService.AttachmentUrl:output_type -> resource.AttachmentUrlResp
	0,  // 20: resource.ResourceService.AttachmentDelete:output_type -> resource.Ack
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_resource_proto_init() }
func file_resource_proto_init() {
	if File_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_proto_rawDesc), len(file_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_proto_goTypes,
		DependencyIndexes: file_resource_proto_depIdxs,
		MessageInfos:      file_resource_proto_msgTypes,
	}.Build()
	File_resource_proto = out.File
	file_resource_proto_goTypes = nil
	file_resource_proto_depIdxs = nil
}
