// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: resource.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceService_Ping_FullMethodName                 = "/resource.ResourceService/Ping"
	ResourceService_AttachmentUploadFile_FullMethodName = "/resource.ResourceService/AttachmentUploadFile"
	ResourceService_AttachmentBind_FullMethodName       = "/resource.ResourceService/AttachmentBind"
	ResourceService_AttachmentDetail_FullMethodName     = "/resource.ResourceService/AttachmentDetail"
	ResourceService_AttachmentBusiness_FullMethodName   = "/resource.ResourceService/AttachmentBusiness"
	ResourceService_AttachmentPage_FullMethodName       = "/resource.ResourceService/AttachmentPage"
	ResourceService_AttachmentDownload_FullMethodName   = "/resource.ResourceService/AttachmentDownload"
	ResourceService_AttachmentUrl_FullMethodName        = "/resource.ResourceService/AttachmentUrl"
	ResourceService_AttachmentDelete_FullMethodName     = "/resource.ResourceService/AttachmentDelete"
)

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceServiceClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	AttachmentUploadFile(ctx context.Context, in *AttachmentUploadReq, opts ...grpc.CallOption) (*Attachment, error)
	AttachmentBind(ctx context.Context, in *AttachmentBindReq, opts ...grpc.CallOption) (*Ack, error)
	AttachmentDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Attachment, error)
	AttachmentBusiness(ctx context.Context, in *AttachmentBusinessQueryReq, opts ...grpc.CallOption) (*AttachmentListResp, error)
	AttachmentPage(ctx context.Context, in *AttachmentPageReq, opts ...grpc.CallOption) (*AttachmentPageResp, error)
	AttachmentDownload(ctx context.Context, in *AttachmentDownloadReq, opts ...grpc.CallOption) (*AttachmentDownloadResp, error)
	AttachmentUrl(ctx context.Context, in *AttachmentUrlQueryReq, opts ...grpc.CallOption) (*AttachmentUrlResp, error)
	AttachmentDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, ResourceService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) AttachmentUploadFile(ctx context.Context, in *AttachmentUploadReq, opts ...grpc.CallOption) (*Attachment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attachment)
	err := c.cc.Invoke(ctx, ResourceService_AttachmentUploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) AttachmentBind(ctx context.Context, in *AttachmentBindReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ResourceService_AttachmentBind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) AttachmentDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Attachment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attachment)
	err := c.cc.Invoke(ctx, ResourceService_AttachmentDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) AttachmentBusiness(ctx context.Context, in *AttachmentBusinessQueryReq, opts ...grpc.CallOption) (*AttachmentListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachmentListResp)
	err := c.cc.Invoke(ctx, ResourceService_AttachmentBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) AttachmentPage(ctx context.Context, in *AttachmentPageReq, opts ...grpc.CallOption) (*AttachmentPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachmentPageResp)
	err := c.cc.Invoke(ctx, ResourceService_AttachmentPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) AttachmentDownload(ctx context.Context, in *AttachmentDownloadReq, opts ...grpc.CallOption) (*AttachmentDownloadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachmentDownloadResp)
	err := c.cc.Invoke(ctx, ResourceService_AttachmentDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) AttachmentUrl(ctx context.Context, in *AttachmentUrlQueryReq, opts ...grpc.CallOption) (*AttachmentUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachmentUrlResp)
	err := c.cc.Invoke(ctx, ResourceService_AttachmentUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) AttachmentDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ResourceService_AttachmentDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
// All implementations must embed UnimplementedResourceServiceServer
// for forward compatibility.
type ResourceServiceServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	AttachmentUploadFile(context.Context, *AttachmentUploadReq) (*Attachment, error)
	AttachmentBind(context.Context, *AttachmentBindReq) (*Ack, error)
	AttachmentDetail(context.Context, *IdReq) (*Attachment, error)
	AttachmentBusiness(context.Context, *AttachmentBusinessQueryReq) (*AttachmentListResp, error)
	AttachmentPage(context.Context, *AttachmentPageReq) (*AttachmentPageResp, error)
	AttachmentDownload(context.Context, *AttachmentDownloadReq) (*AttachmentDownloadResp, error)
	AttachmentUrl(context.Context, *AttachmentUrlQueryReq) (*AttachmentUrlResp, error)
	AttachmentDelete(context.Context, *IdReq) (*Ack, error)
	mustEmbedUnimplementedResourceServiceServer()
}

// UnimplementedResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceServiceServer struct{}

func (UnimplementedResourceServiceServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedResourceServiceServer) AttachmentUploadFile(context.Context, *AttachmentUploadReq) (*Attachment, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachmentUploadFile not implemented")
}
func (UnimplementedResourceServiceServer) AttachmentBind(context.Context, *AttachmentBindReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachmentBind not implemented")
}
func (UnimplementedResourceServiceServer) AttachmentDetail(context.Context, *IdReq) (*Attachment, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachmentDetail not implemented")
}
func (UnimplementedResourceServiceServer) AttachmentBusiness(context.Context, *AttachmentBusinessQueryReq) (*AttachmentListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachmentBusiness not implemented")
}
func (UnimplementedResourceServiceServer) AttachmentPage(context.Context, *AttachmentPageReq) (*AttachmentPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachmentPage not implemented")
}
func (UnimplementedResourceServiceServer) AttachmentDownload(context.Context, *AttachmentDownloadReq) (*AttachmentDownloadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachmentDownload not implemented")
}
func (UnimplementedResourceServiceServer) AttachmentUrl(context.Context, *AttachmentUrlQueryReq) (*AttachmentUrlResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachmentUrl not implemented")
}
func (UnimplementedResourceServiceServer) AttachmentDelete(context.Context, *IdReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachmentDelete not implemented")
}
func (UnimplementedResourceServiceServer) mustEmbedUnimplementedResourceServiceServer() {}
func (UnimplementedResourceServiceServer) testEmbeddedByValue()                         {}

// UnsafeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServiceServer will
// result in compilation errors.
type UnsafeResourceServiceServer interface {
	mustEmbedUnimplementedResourceServiceServer()
}

func RegisterResourceServiceServer(s grpc.ServiceRegistrar, srv ResourceServiceServer) {
	// If the following call panics, it indicates UnimplementedResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceService_ServiceDesc, srv)
}

func _ResourceService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_AttachmentUploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).AttachmentUploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_AttachmentUploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).AttachmentUploadFile(ctx, req.(*AttachmentUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_AttachmentBind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentBindReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).AttachmentBind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_AttachmentBind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).AttachmentBind(ctx, req.(*AttachmentBindReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_AttachmentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).AttachmentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_AttachmentDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).AttachmentDetail(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_AttachmentBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentBusinessQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).AttachmentBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_AttachmentBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).AttachmentBusiness(ctx, req.(*AttachmentBusinessQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_AttachmentPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).AttachmentPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_AttachmentPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).AttachmentPage(ctx, req.(*AttachmentPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_AttachmentDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentDownloadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).AttachmentDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_AttachmentDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).AttachmentDownload(ctx, req.(*AttachmentDownloadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_AttachmentUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentUrlQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).AttachmentUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_AttachmentUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).AttachmentUrl(ctx, req.(*AttachmentUrlQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_AttachmentDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).AttachmentDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_AttachmentDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).AttachmentDelete(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceService_ServiceDesc is the grpc.ServiceDesc for ResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resource.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ResourceService_Ping_Handler,
		},
		{
			MethodName: "AttachmentUploadFile",
			Handler:    _ResourceService_AttachmentUploadFile_Handler,
		},
		{
			MethodName: "AttachmentBind",
			Handler:    _ResourceService_AttachmentBind_Handler,
		},
		{
			MethodName: "AttachmentDetail",
			Handler:    _ResourceService_AttachmentDetail_Handler,
		},
		{
			MethodName: "AttachmentBusiness",
			Handler:    _ResourceService_AttachmentBusiness_Handler,
		},
		{
			MethodName: "AttachmentPage",
			Handler:    _ResourceService_AttachmentPage_Handler,
		},
		{
			MethodName: "AttachmentDownload",
			Handler:    _ResourceService_AttachmentDownload_Handler,
		},
		{
			MethodName: "AttachmentUrl",
			Handler:    _ResourceService_AttachmentUrl_Handler,
		},
		{
			MethodName: "AttachmentDelete",
			Handler:    _ResourceService_AttachmentDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource.proto",
}
