// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: iam.proto

package iamservice

import (
	"context"

	"github.com/gcc798/microservice-kit/application/iam-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Ack                     = pb.Ack
	ApiPermission           = pb.ApiPermission
	ApiPermissionIdsResp    = pb.ApiPermissionIdsResp
	ApiPermissionListResp   = pb.ApiPermissionListResp
	ApiPermissionSaveReq    = pb.ApiPermissionSaveReq
	AssignRoleReq           = pb.AssignRoleReq
	AuthLoginReq            = pb.AuthLoginReq
	AuthLoginResp           = pb.AuthLoginResp
	BatchIdsReq             = pb.BatchIdsReq
	CaptchaDataResp         = pb.CaptchaDataResp
	CaptchaEmailReq         = pb.CaptchaEmailReq
	CaptchaPhoneReq         = pb.CaptchaPhoneReq
	CaptchaReq              = pb.CaptchaReq
	CaptchaTypesResp        = pb.CaptchaTypesResp
	CheckPermissionReq      = pb.CheckPermissionReq
	CheckPermissionResp     = pb.CheckPermissionResp
	Empty                   = pb.Empty
	IdReq                   = pb.IdReq
	Menu                    = pb.Menu
	MenuIdsResp             = pb.MenuIdsResp
	MenuListResp            = pb.MenuListResp
	MenuReq                 = pb.MenuReq
	Org                     = pb.Org
	OrgCreateReq            = pb.OrgCreateReq
	OrgPageReq              = pb.OrgPageReq
	OrgPageResp             = pb.OrgPageResp
	OrgTreeResp             = pb.OrgTreeResp
	OrgUpdateReq            = pb.OrgUpdateReq
	PageInfo                = pb.PageInfo
	PingReq                 = pb.PingReq
	PingResp                = pb.PingResp
	RemoveRoleReq           = pb.RemoveRoleReq
	Role                    = pb.Role
	RoleApiPermissionsReq   = pb.RoleApiPermissionsReq
	RoleCreateReq           = pb.RoleCreateReq
	RoleListResp            = pb.RoleListResp
	RoleMenusAssignReq      = pb.RoleMenusAssignReq
	RoleMenusReq            = pb.RoleMenusReq
	RolePageReq             = pb.RolePageReq
	RolePageResp            = pb.RolePageResp
	RoleUpdateReq           = pb.RoleUpdateReq
	RoleUsersReq            = pb.RoleUsersReq
	User                    = pb.User
	UserApiPermissionsReq   = pb.UserApiPermissionsReq
	UserAuthContextReq      = pb.UserAuthContextReq
	UserAuthContextResp     = pb.UserAuthContextResp
	UserChangePasswordReq   = pb.UserChangePasswordReq
	UserCreateReq           = pb.UserCreateReq
	UserImportReq           = pb.UserImportReq
	UserInfo                = pb.UserInfo
	UserListResp            = pb.UserListResp
	UserPageReq             = pb.UserPageReq
	UserPageResp            = pb.UserPageResp
	UserPasswordReq         = pb.UserPasswordReq
	UserRoleQueryReq        = pb.UserRoleQueryReq
	UserUpdateReq           = pb.UserUpdateReq
	ValidateAccessTokenReq  = pb.ValidateAccessTokenReq
	ValidateAccessTokenResp = pb.ValidateAccessTokenResp

	IamService interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
		ValidateAccessToken(ctx context.Context, in *ValidateAccessTokenReq, opts ...grpc.CallOption) (*ValidateAccessTokenResp, error)
		CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error)
		AuthLogin(ctx context.Context, in *AuthLoginReq, opts ...grpc.CallOption) (*AuthLoginResp, error)
		UserProfile(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*User, error)
		UserAuthContext(ctx context.Context, in *UserAuthContextReq, opts ...grpc.CallOption) (*UserAuthContextResp, error)
		UserCreate(ctx context.Context, in *UserCreateReq, opts ...grpc.CallOption) (*Ack, error)
		UserImport(ctx context.Context, in *UserImportReq, opts ...grpc.CallOption) (*Ack, error)
		UserPage(ctx context.Context, in *UserPageReq, opts ...grpc.CallOption) (*UserPageResp, error)
		UserBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
		UserChangePassword(ctx context.Context, in *UserChangePasswordReq, opts ...grpc.CallOption) (*Ack, error)
		UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*Ack, error)
		UserResetPassword(ctx context.Context, in *UserPasswordReq, opts ...grpc.CallOption) (*Ack, error)
		UserDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*User, error)
		UserDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
		RoleCreate(ctx context.Context, in *RoleCreateReq, opts ...grpc.CallOption) (*Ack, error)
		RolePage(ctx context.Context, in *RolePageReq, opts ...grpc.CallOption) (*RolePageResp, error)
		RoleAssign(ctx context.Context, in *AssignRoleReq, opts ...grpc.CallOption) (*Ack, error)
		RoleRemove(ctx context.Context, in *RemoveRoleReq, opts ...grpc.CallOption) (*Ack, error)
		RoleUser(ctx context.Context, in *UserRoleQueryReq, opts ...grpc.CallOption) (*RoleListResp, error)
		RoleUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*UserListResp, error)
		RoleAssignUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*Ack, error)
		RoleRemoveUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*Ack, error)
		RoleMenus(ctx context.Context, in *RoleMenusReq, opts ...grpc.CallOption) (*MenuIdsResp, error)
		RoleAssignMenus(ctx context.Context, in *RoleMenusAssignReq, opts ...grpc.CallOption) (*Ack, error)
		RoleUpdate(ctx context.Context, in *RoleUpdateReq, opts ...grpc.CallOption) (*Ack, error)
		RoleDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Role, error)
		RoleDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
		ApiPermissionTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApiPermissionListResp, error)
		ApiPermissionList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApiPermissionListResp, error)
		ApiPermissionCreate(ctx context.Context, in *ApiPermissionSaveReq, opts ...grpc.CallOption) (*ApiPermission, error)
		ApiPermissionUpdate(ctx context.Context, in *ApiPermissionSaveReq, opts ...grpc.CallOption) (*Ack, error)
		ApiPermissionDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
		RoleApiPermissions(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ApiPermissionIdsResp, error)
		RoleApiPermissionsAssign(ctx context.Context, in *RoleApiPermissionsReq, opts ...grpc.CallOption) (*Ack, error)
		UserApiPermissions(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ApiPermissionIdsResp, error)
		UserApiPermissionsAssign(ctx context.Context, in *UserApiPermissionsReq, opts ...grpc.CallOption) (*Ack, error)
		OrgCreate(ctx context.Context, in *OrgCreateReq, opts ...grpc.CallOption) (*Ack, error)
		OrgPage(ctx context.Context, in *OrgPageReq, opts ...grpc.CallOption) (*OrgPageResp, error)
		OrgTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrgTreeResp, error)
		OrgBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
		OrgUpdate(ctx context.Context, in *OrgUpdateReq, opts ...grpc.CallOption) (*Ack, error)
		OrgDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Org, error)
		OrgDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
		MenuUserTree(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*MenuListResp, error)
		MenuTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResp, error)
		MenuList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResp, error)
		MenuDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Menu, error)
		MenuCreate(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*Ack, error)
		MenuUpdate(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*Ack, error)
		MenuDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
		CaptchaEnabledTypes(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*CaptchaTypesResp, error)
		CaptchaImage(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*CaptchaDataResp, error)
		CaptchaSms(ctx context.Context, in *CaptchaPhoneReq, opts ...grpc.CallOption) (*CaptchaDataResp, error)
		CaptchaEmail(ctx context.Context, in *CaptchaEmailReq, opts ...grpc.CallOption) (*CaptchaDataResp, error)
	}

	defaultIamService struct {
		cli zrpc.Client
	}
)

func NewIamService(cli zrpc.Client) IamService {
	return &defaultIamService{
		cli: cli,
	}
}

func (m *defaultIamService) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultIamService) ValidateAccessToken(ctx context.Context, in *ValidateAccessTokenReq, opts ...grpc.CallOption) (*ValidateAccessTokenResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.ValidateAccessToken(ctx, in, opts...)
}

func (m *defaultIamService) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.CheckPermission(ctx, in, opts...)
}

func (m *defaultIamService) AuthLogin(ctx context.Context, in *AuthLoginReq, opts ...grpc.CallOption) (*AuthLoginResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.AuthLogin(ctx, in, opts...)
}

func (m *defaultIamService) UserProfile(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*User, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserProfile(ctx, in, opts...)
}

func (m *defaultIamService) UserAuthContext(ctx context.Context, in *UserAuthContextReq, opts ...grpc.CallOption) (*UserAuthContextResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserAuthContext(ctx, in, opts...)
}

func (m *defaultIamService) UserCreate(ctx context.Context, in *UserCreateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserCreate(ctx, in, opts...)
}

func (m *defaultIamService) UserImport(ctx context.Context, in *UserImportReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserImport(ctx, in, opts...)
}

func (m *defaultIamService) UserPage(ctx context.Context, in *UserPageReq, opts ...grpc.CallOption) (*UserPageResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserPage(ctx, in, opts...)
}

func (m *defaultIamService) UserBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserBatchDelete(ctx, in, opts...)
}

func (m *defaultIamService) UserChangePassword(ctx context.Context, in *UserChangePasswordReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserChangePassword(ctx, in, opts...)
}

func (m *defaultIamService) UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserUpdate(ctx, in, opts...)
}

func (m *defaultIamService) UserResetPassword(ctx context.Context, in *UserPasswordReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserResetPassword(ctx, in, opts...)
}

func (m *defaultIamService) UserDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*User, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserDetail(ctx, in, opts...)
}

func (m *defaultIamService) UserDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserDelete(ctx, in, opts...)
}

func (m *defaultIamService) RoleCreate(ctx context.Context, in *RoleCreateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleCreate(ctx, in, opts...)
}

func (m *defaultIamService) RolePage(ctx context.Context, in *RolePageReq, opts ...grpc.CallOption) (*RolePageResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RolePage(ctx, in, opts...)
}

func (m *defaultIamService) RoleAssign(ctx context.Context, in *AssignRoleReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleAssign(ctx, in, opts...)
}

func (m *defaultIamService) RoleRemove(ctx context.Context, in *RemoveRoleReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleRemove(ctx, in, opts...)
}

func (m *defaultIamService) RoleUser(ctx context.Context, in *UserRoleQueryReq, opts ...grpc.CallOption) (*RoleListResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleUser(ctx, in, opts...)
}

func (m *defaultIamService) RoleUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleUsers(ctx, in, opts...)
}

func (m *defaultIamService) RoleAssignUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleAssignUsers(ctx, in, opts...)
}

func (m *defaultIamService) RoleRemoveUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleRemoveUsers(ctx, in, opts...)
}

func (m *defaultIamService) RoleMenus(ctx context.Context, in *RoleMenusReq, opts ...grpc.CallOption) (*MenuIdsResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleMenus(ctx, in, opts...)
}

func (m *defaultIamService) RoleAssignMenus(ctx context.Context, in *RoleMenusAssignReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleAssignMenus(ctx, in, opts...)
}

func (m *defaultIamService) RoleUpdate(ctx context.Context, in *RoleUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleUpdate(ctx, in, opts...)
}

func (m *defaultIamService) RoleDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Role, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleDetail(ctx, in, opts...)
}

func (m *defaultIamService) RoleDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleDelete(ctx, in, opts...)
}

func (m *defaultIamService) ApiPermissionTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApiPermissionListResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.ApiPermissionTree(ctx, in, opts...)
}

func (m *defaultIamService) ApiPermissionList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApiPermissionListResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.ApiPermissionList(ctx, in, opts...)
}

func (m *defaultIamService) ApiPermissionCreate(ctx context.Context, in *ApiPermissionSaveReq, opts ...grpc.CallOption) (*ApiPermission, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.ApiPermissionCreate(ctx, in, opts...)
}

func (m *defaultIamService) ApiPermissionUpdate(ctx context.Context, in *ApiPermissionSaveReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.ApiPermissionUpdate(ctx, in, opts...)
}

func (m *defaultIamService) ApiPermissionDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.ApiPermissionDelete(ctx, in, opts...)
}

func (m *defaultIamService) RoleApiPermissions(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ApiPermissionIdsResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleApiPermissions(ctx, in, opts...)
}

func (m *defaultIamService) RoleApiPermissionsAssign(ctx context.Context, in *RoleApiPermissionsReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.RoleApiPermissionsAssign(ctx, in, opts...)
}

func (m *defaultIamService) UserApiPermissions(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ApiPermissionIdsResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserApiPermissions(ctx, in, opts...)
}

func (m *defaultIamService) UserApiPermissionsAssign(ctx context.Context, in *UserApiPermissionsReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.UserApiPermissionsAssign(ctx, in, opts...)
}

func (m *defaultIamService) OrgCreate(ctx context.Context, in *OrgCreateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.OrgCreate(ctx, in, opts...)
}

func (m *defaultIamService) OrgPage(ctx context.Context, in *OrgPageReq, opts ...grpc.CallOption) (*OrgPageResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.OrgPage(ctx, in, opts...)
}

func (m *defaultIamService) OrgTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrgTreeResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.OrgTree(ctx, in, opts...)
}

func (m *defaultIamService) OrgBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.OrgBatchDelete(ctx, in, opts...)
}

func (m *defaultIamService) OrgUpdate(ctx context.Context, in *OrgUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.OrgUpdate(ctx, in, opts...)
}

func (m *defaultIamService) OrgDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Org, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.OrgDetail(ctx, in, opts...)
}

func (m *defaultIamService) OrgDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.OrgDelete(ctx, in, opts...)
}

func (m *defaultIamService) MenuUserTree(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*MenuListResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.MenuUserTree(ctx, in, opts...)
}

func (m *defaultIamService) MenuTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.MenuTree(ctx, in, opts...)
}

func (m *defaultIamService) MenuList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.MenuList(ctx, in, opts...)
}

func (m *defaultIamService) MenuDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Menu, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.MenuDetail(ctx, in, opts...)
}

func (m *defaultIamService) MenuCreate(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.MenuCreate(ctx, in, opts...)
}

func (m *defaultIamService) MenuUpdate(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.MenuUpdate(ctx, in, opts...)
}

func (m *defaultIamService) MenuDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.MenuDelete(ctx, in, opts...)
}

func (m *defaultIamService) CaptchaEnabledTypes(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*CaptchaTypesResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.CaptchaEnabledTypes(ctx, in, opts...)
}

func (m *defaultIamService) CaptchaImage(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*CaptchaDataResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.CaptchaImage(ctx, in, opts...)
}

func (m *defaultIamService) CaptchaSms(ctx context.Context, in *CaptchaPhoneReq, opts ...grpc.CallOption) (*CaptchaDataResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.CaptchaSms(ctx, in, opts...)
}

func (m *defaultIamService) CaptchaEmail(ctx context.Context, in *CaptchaEmailReq, opts ...grpc.CallOption) (*CaptchaDataResp, error) {
	client := pb.NewIamServiceClient(m.cli.Conn())
	return client.CaptchaEmail(ctx, in, opts...)
}
