// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	attachment "github.com/gcc798/microservice-kit/application/resource-api/internal/handler/attachment"
	health "github.com/gcc798/microservice-kit/application/resource-api/internal/handler/health"
	"github.com/gcc798/microservice-kit/application/resource-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/attachment/:attachmentId",
				Handler: attachment.AttachmentDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/attachment/:attachmentId",
				Handler: attachment.AttachmentDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/attachment/:attachmentId/bind",
				Handler: attachment.AttachmentBindHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/attachment/:attachmentId/download",
				Handler: attachment.AttachmentDownloadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/attachment/:attachmentId/url",
				Handler: attachment.AttachmentUrlHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/attachment/business",
				Handler: attachment.AttachmentBusinessHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/attachment/page",
				Handler: attachment.AttachmentPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/attachment/upload-file",
				Handler: attachment.AttachmentUploadFileHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/live",
				Handler: health.HealthLiveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/ready",
				Handler: health.HealthReadyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/startup",
				Handler: health.HealthStartupHandler(serverCtx),
			},
		},
	)
}
