// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type ApiPermissionAssignReq struct {
	PermissionIds []int64 `json:"permissionIds"`
}

type ApiPermissionSaveReq struct {
	ParentId int64  `json:"parentId,optional"`
	Module   string `json:"module"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	NodeType int32  `json:"nodeType"`
	Action   string `json:"action"`
	Method   string `json:"method,optional"`
	Path     string `json:"path,optional"`
	Sort     int64  `json:"sort,optional"`
	Status   int32  `json:"status"`
	Remark   string `json:"remark,optional"`
}

type ApiPermissionUpdateReq struct {
	Id       int64  `path:"id"`
	ParentId int64  `json:"parentId,optional"`
	Module   string `json:"module"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	NodeType int32  `json:"nodeType"`
	Action   string `json:"action"`
	Method   string `json:"method,optional"`
	Path     string `json:"path,optional"`
	Sort     int64  `json:"sort,optional"`
	Status   int32  `json:"status"`
	Remark   string `json:"remark,optional"`
}

type AssignRoleReq struct {
	UserId int64 `json:"userId"`
	RoleId int64 `json:"roleId"`
}

type AttachmentIdPathReq struct {
	AttachmentId int64 `path:"attachmentId"`
}

type BatchIdsReq struct {
	Ids []int64 `json:"ids"`
}

type CaptchaEmailReq struct {
	Email string `json:"email"`
}

type CaptchaPhoneReq struct {
	Phone string `json:"phone"`
}

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type IdPathReq struct {
	Id int64 `path:"id"`
}

type LoginReq struct {
	ClientId    string `json:"clientId"`
	GrantType   string `json:"grantType"`
	Username    string `json:"username,optional"`
	Password    string `json:"password,optional"`
	Code        string `json:"code,optional"`
	SmsCode     string `json:"smsCode,optional"`
	Phonenumber string `json:"phonenumber,optional"`
	Email       string `json:"email,optional"`
	WxCode      string `json:"wxCode,optional"`
	Appid       string `json:"appid,optional"`
	Uuid        string `json:"uuid,optional"`
}

type MenuReq struct {
	Id        int64  `json:"id,optional"`
	MenuName  string `json:"menuName,optional"`
	ParentId  int64  `json:"parentId,optional"`
	Sort      int64  `json:"sort,optional"`
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Query     string `json:"query,optional"`
	IsFrame   int32  `json:"isFrame,optional"`
	IsCache   int32  `json:"isCache,optional"`
	MenuType  int32  `json:"menuType,optional"`
	Visible   int32  `json:"visible,optional"`
	Status    int32  `json:"status,optional"`
	Perms     string `json:"perms,optional"`
	Icon      string `json:"icon,optional"`
	Remark    string `json:"remark,optional"`
}

type MenuUpdateReq struct {
	Id        int64  `path:"id"`
	MenuName  string `json:"menuName,optional"`
	ParentId  int64  `json:"parentId,optional"`
	Sort      int64  `json:"sort,optional"`
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Query     string `json:"query,optional"`
	IsFrame   int32  `json:"isFrame,optional"`
	IsCache   int32  `json:"isCache,optional"`
	MenuType  int32  `json:"menuType,optional"`
	Visible   int32  `json:"visible,optional"`
	Status    int32  `json:"status,optional"`
	Perms     string `json:"perms,optional"`
	Icon      string `json:"icon,optional"`
	Remark    string `json:"remark,optional"`
}

type OrgCreateReq struct {
	ParentId int64  `json:"parentId,optional"`
	OrgName  string `json:"orgName"`
	OrgCode  string `json:"orgCode"`
	OrgType  string `json:"orgType,optional"`
	Leader   string `json:"leader,optional"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Status   int32  `json:"status,optional"`
	Sort     int64  `json:"sort,optional"`
	Remark   string `json:"remark,optional"`
}

type OrgPageReq struct {
	PageNum  int64  `json:"pageNum,optional"`
	PageSize int64  `json:"pageSize,optional"`
	OrgName  string `json:"orgName,optional"`
	OrgCode  string `json:"orgCode,optional"`
	Status   int32  `json:"status,optional"`
	ParentId int64  `json:"parentId,optional"`
}

type OrgUpdateReq struct {
	Id       int64  `path:"id"`
	ParentId int64  `json:"parentId,optional"`
	OrgName  string `json:"orgName,optional"`
	OrgCode  string `json:"orgCode,optional"`
	OrgType  string `json:"orgType,optional"`
	Leader   string `json:"leader,optional"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Status   int32  `json:"status,optional"`
	Sort     int64  `json:"sort,optional"`
	Remark   string `json:"remark,optional"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
	ClientId     string `json:"clientId"`
}

type RemoveRoleReq struct {
	UserId int64 `form:"userId"`
	RoleId int64 `form:"roleId"`
}

type ResourceSmsCodeReq struct {
	Phone       string `form:"phone,optional"`
	Phonenumber string `form:"phonenumber,optional"`
}

type RoleApiPermissionsAssignReq struct {
	RoleId        int64   `path:"roleId"`
	PermissionIds []int64 `json:"permissionIds"`
}

type RoleApiPermissionsPathReq struct {
	RoleId int64 `path:"roleId"`
}

type RoleCreateReq struct {
	RoleKey   string `json:"roleKey"`
	RoleName  string `json:"roleName"`
	Sort      int64  `json:"sort,optional"`
	Status    int32  `json:"status,optional"`
	DataScope int32  `json:"dataScope,optional"`
	Remark    string `json:"remark,optional"`
}

type RoleIdPathReq struct {
	RoleId int64 `path:"roleId"`
}

type RoleMenusAssignReq struct {
	RoleId  int64   `path:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type RoleMenusPathReq struct {
	RoleId int64 `path:"roleId"`
}

type RolePageReq struct {
	PageNum  int64  `json:"pageNum,optional"`
	PageSize int64  `json:"pageSize,optional"`
	RoleName string `json:"roleName,optional"`
	Status   int32  `json:"status,optional"`
}

type RoleUpdateReq struct {
	RoleId    int64  `path:"roleId"`
	RoleName  string `json:"roleName"`
	Sort      int64  `json:"sort,optional"`
	Status    int32  `json:"status,optional"`
	DataScope int32  `json:"dataScope,optional"`
	Remark    string `json:"remark,optional"`
}

type RoleUsersPathReq struct {
	RoleId int64 `path:"roleId"`
}

type RoleUsersReq struct {
	RoleId  int64   `path:"roleId"`
	UserIds []int64 `json:"userIds"`
}

type StringIdPathReq struct {
	Id string `path:"id"`
}

type UserApiPermissionsAssignReq struct {
	Id            int64   `path:"id"`
	PermissionIds []int64 `json:"permissionIds"`
}

type UserApiPermissionsPathReq struct {
	Id int64 `path:"id"`
}

type UserChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type UserCreateReq struct {
	UserName    string `json:"userName"`
	NickName    string `json:"nickName"`
	Password    string `json:"password"`
	UserType    int32  `json:"userType,optional"`
	Email       string `json:"email,optional"`
	Phonenumber string `json:"phonenumber,optional"`
	Sex         int32  `json:"sex,optional"`
	Avatar      string `json:"avatar,optional"`
	Status      int32  `json:"status,optional"`
	Remark      string `json:"remark,optional"`
}

type UserImportReq struct {
	Users []UserCreateReq `json:"users"`
}

type UserPageReq struct {
	PageNum     int64  `json:"pageNum,optional"`
	PageSize    int64  `json:"pageSize,optional"`
	Username    string `json:"username,optional"`
	Phonenumber string `json:"phonenumber,optional"`
	Status      int32  `json:"status,optional"`
}

type UserPasswordPathReq struct {
	Id          int64  `path:"id"`
	NewPassword string `json:"newPassword"`
}

type UserRoleQueryReq struct {
	UserId int64 `form:"userId"`
}

type UserUpdateReq struct {
	Id          int64  `path:"id"`
	UserName    string `json:"userName,optional"`
	NickName    string `json:"nickName,optional"`
	UserType    int32  `json:"userType,optional"`
	Email       string `json:"email,optional"`
	Phonenumber string `json:"phonenumber,optional"`
	Sex         int32  `json:"sex,optional"`
	Avatar      string `json:"avatar,optional"`
	Status      int32  `json:"status,optional"`
	Remark      string `json:"remark,optional"`
}
