// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: resource.proto

package server

import (
	"context"

	"github.com/gcc798/microservice-kit/application/resource-rpc/internal/logic/resourceservice"
	"github.com/gcc798/microservice-kit/application/resource-rpc/internal/svc"
	"github.com/gcc798/microservice-kit/application/resource-rpc/pb"
)

type ResourceServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedResourceServiceServer
}

func NewResourceServiceServer(svcCtx *svc.ServiceContext) *ResourceServiceServer {
	return &ResourceServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ResourceServiceServer) Ping(ctx context.Context, in *pb.PingReq) (*pb.PingResp, error) {
	l := resourceservicelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *ResourceServiceServer) AttachmentUploadFile(ctx context.Context, in *pb.AttachmentUploadReq) (*pb.Attachment, error) {
	l := resourceservicelogic.NewAttachmentUploadFileLogic(ctx, s.svcCtx)
	return l.AttachmentUploadFile(in)
}

func (s *ResourceServiceServer) AttachmentBind(ctx context.Context, in *pb.AttachmentBindReq) (*pb.Ack, error) {
	l := resourceservicelogic.NewAttachmentBindLogic(ctx, s.svcCtx)
	return l.AttachmentBind(in)
}

func (s *ResourceServiceServer) AttachmentDetail(ctx context.Context, in *pb.IdReq) (*pb.Attachment, error) {
	l := resourceservicelogic.NewAttachmentDetailLogic(ctx, s.svcCtx)
	return l.AttachmentDetail(in)
}

func (s *ResourceServiceServer) AttachmentBusiness(ctx context.Context, in *pb.AttachmentBusinessQueryReq) (*pb.AttachmentListResp, error) {
	l := resourceservicelogic.NewAttachmentBusinessLogic(ctx, s.svcCtx)
	return l.AttachmentBusiness(in)
}

func (s *ResourceServiceServer) AttachmentPage(ctx context.Context, in *pb.AttachmentPageReq) (*pb.AttachmentPageResp, error) {
	l := resourceservicelogic.NewAttachmentPageLogic(ctx, s.svcCtx)
	return l.AttachmentPage(in)
}

func (s *ResourceServiceServer) AttachmentDownload(ctx context.Context, in *pb.AttachmentDownloadReq) (*pb.AttachmentDownloadResp, error) {
	l := resourceservicelogic.NewAttachmentDownloadLogic(ctx, s.svcCtx)
	return l.AttachmentDownload(in)
}

func (s *ResourceServiceServer) AttachmentUrl(ctx context.Context, in *pb.AttachmentUrlQueryReq) (*pb.AttachmentUrlResp, error) {
	l := resourceservicelogic.NewAttachmentUrlLogic(ctx, s.svcCtx)
	return l.AttachmentUrl(in)
}

func (s *ResourceServiceServer) AttachmentDelete(ctx context.Context, in *pb.IdReq) (*pb.Ack, error) {
	l := resourceservicelogic.NewAttachmentDeleteLogic(ctx, s.svcCtx)
	return l.AttachmentDelete(in)
}
