// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: iam.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IamService_Ping_FullMethodName                     = "/iam.IamService/Ping"
	IamService_ValidateAccessToken_FullMethodName      = "/iam.IamService/ValidateAccessToken"
	IamService_CheckPermission_FullMethodName          = "/iam.IamService/CheckPermission"
	IamService_AuthLogin_FullMethodName                = "/iam.IamService/AuthLogin"
	IamService_UserProfile_FullMethodName              = "/iam.IamService/UserProfile"
	IamService_UserAuthContext_FullMethodName          = "/iam.IamService/UserAuthContext"
	IamService_UserCreate_FullMethodName               = "/iam.IamService/UserCreate"
	IamService_UserImport_FullMethodName               = "/iam.IamService/UserImport"
	IamService_UserPage_FullMethodName                 = "/iam.IamService/UserPage"
	IamService_UserBatchDelete_FullMethodName          = "/iam.IamService/UserBatchDelete"
	IamService_UserChangePassword_FullMethodName       = "/iam.IamService/UserChangePassword"
	IamService_UserUpdate_FullMethodName               = "/iam.IamService/UserUpdate"
	IamService_UserResetPassword_FullMethodName        = "/iam.IamService/UserResetPassword"
	IamService_UserDetail_FullMethodName               = "/iam.IamService/UserDetail"
	IamService_UserDelete_FullMethodName               = "/iam.IamService/UserDelete"
	IamService_RoleCreate_FullMethodName               = "/iam.IamService/RoleCreate"
	IamService_RolePage_FullMethodName                 = "/iam.IamService/RolePage"
	IamService_RoleAssign_FullMethodName               = "/iam.IamService/RoleAssign"
	IamService_RoleRemove_FullMethodName               = "/iam.IamService/RoleRemove"
	IamService_RoleUser_FullMethodName                 = "/iam.IamService/RoleUser"
	IamService_RoleUsers_FullMethodName                = "/iam.IamService/RoleUsers"
	IamService_RoleAssignUsers_FullMethodName          = "/iam.IamService/RoleAssignUsers"
	IamService_RoleRemoveUsers_FullMethodName          = "/iam.IamService/RoleRemoveUsers"
	IamService_RoleMenus_FullMethodName                = "/iam.IamService/RoleMenus"
	IamService_RoleAssignMenus_FullMethodName          = "/iam.IamService/RoleAssignMenus"
	IamService_RoleUpdate_FullMethodName               = "/iam.IamService/RoleUpdate"
	IamService_RoleDetail_FullMethodName               = "/iam.IamService/RoleDetail"
	IamService_RoleDelete_FullMethodName               = "/iam.IamService/RoleDelete"
	IamService_ApiPermissionTree_FullMethodName        = "/iam.IamService/ApiPermissionTree"
	IamService_ApiPermissionList_FullMethodName        = "/iam.IamService/ApiPermissionList"
	IamService_ApiPermissionCreate_FullMethodName      = "/iam.IamService/ApiPermissionCreate"
	IamService_ApiPermissionUpdate_FullMethodName      = "/iam.IamService/ApiPermissionUpdate"
	IamService_ApiPermissionDelete_FullMethodName      = "/iam.IamService/ApiPermissionDelete"
	IamService_RoleApiPermissions_FullMethodName       = "/iam.IamService/RoleApiPermissions"
	IamService_RoleApiPermissionsAssign_FullMethodName = "/iam.IamService/RoleApiPermissionsAssign"
	IamService_UserApiPermissions_FullMethodName       = "/iam.IamService/UserApiPermissions"
	IamService_UserApiPermissionsAssign_FullMethodName = "/iam.IamService/UserApiPermissionsAssign"
	IamService_OrgCreate_FullMethodName                = "/iam.IamService/OrgCreate"
	IamService_OrgPage_FullMethodName                  = "/iam.IamService/OrgPage"
	IamService_OrgTree_FullMethodName                  = "/iam.IamService/OrgTree"
	IamService_OrgBatchDelete_FullMethodName           = "/iam.IamService/OrgBatchDelete"
	IamService_OrgUpdate_FullMethodName                = "/iam.IamService/OrgUpdate"
	IamService_OrgDetail_FullMethodName                = "/iam.IamService/OrgDetail"
	IamService_OrgDelete_FullMethodName                = "/iam.IamService/OrgDelete"
	IamService_MenuUserTree_FullMethodName             = "/iam.IamService/MenuUserTree"
	IamService_MenuTree_FullMethodName                 = "/iam.IamService/MenuTree"
	IamService_MenuList_FullMethodName                 = "/iam.IamService/MenuList"
	IamService_MenuDetail_FullMethodName               = "/iam.IamService/MenuDetail"
	IamService_MenuCreate_FullMethodName               = "/iam.IamService/MenuCreate"
	IamService_MenuUpdate_FullMethodName               = "/iam.IamService/MenuUpdate"
	IamService_MenuDelete_FullMethodName               = "/iam.IamService/MenuDelete"
	IamService_CaptchaEnabledTypes_FullMethodName      = "/iam.IamService/CaptchaEnabledTypes"
	IamService_CaptchaImage_FullMethodName             = "/iam.IamService/CaptchaImage"
	IamService_CaptchaSms_FullMethodName               = "/iam.IamService/CaptchaSms"
	IamService_CaptchaEmail_FullMethodName             = "/iam.IamService/CaptchaEmail"
)

// IamServiceClient is the client API for IamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IamServiceClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	ValidateAccessToken(ctx context.Context, in *ValidateAccessTokenReq, opts ...grpc.CallOption) (*ValidateAccessTokenResp, error)
	CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error)
	AuthLogin(ctx context.Context, in *AuthLoginReq, opts ...grpc.CallOption) (*AuthLoginResp, error)
	UserProfile(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*User, error)
	UserAuthContext(ctx context.Context, in *UserAuthContextReq, opts ...grpc.CallOption) (*UserAuthContextResp, error)
	UserCreate(ctx context.Context, in *UserCreateReq, opts ...grpc.CallOption) (*Ack, error)
	UserImport(ctx context.Context, in *UserImportReq, opts ...grpc.CallOption) (*Ack, error)
	UserPage(ctx context.Context, in *UserPageReq, opts ...grpc.CallOption) (*UserPageResp, error)
	UserBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
	UserChangePassword(ctx context.Context, in *UserChangePasswordReq, opts ...grpc.CallOption) (*Ack, error)
	UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*Ack, error)
	UserResetPassword(ctx context.Context, in *UserPasswordReq, opts ...grpc.CallOption) (*Ack, error)
	UserDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*User, error)
	UserDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
	RoleCreate(ctx context.Context, in *RoleCreateReq, opts ...grpc.CallOption) (*Ack, error)
	RolePage(ctx context.Context, in *RolePageReq, opts ...grpc.CallOption) (*RolePageResp, error)
	RoleAssign(ctx context.Context, in *AssignRoleReq, opts ...grpc.CallOption) (*Ack, error)
	RoleRemove(ctx context.Context, in *RemoveRoleReq, opts ...grpc.CallOption) (*Ack, error)
	RoleUser(ctx context.Context, in *UserRoleQueryReq, opts ...grpc.CallOption) (*RoleListResp, error)
	RoleUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*UserListResp, error)
	RoleAssignUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*Ack, error)
	RoleRemoveUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*Ack, error)
	RoleMenus(ctx context.Context, in *RoleMenusReq, opts ...grpc.CallOption) (*MenuIdsResp, error)
	RoleAssignMenus(ctx context.Context, in *RoleMenusAssignReq, opts ...grpc.CallOption) (*Ack, error)
	RoleUpdate(ctx context.Context, in *RoleUpdateReq, opts ...grpc.CallOption) (*Ack, error)
	RoleDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Role, error)
	RoleDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
	ApiPermissionTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApiPermissionListResp, error)
	ApiPermissionList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApiPermissionListResp, error)
	ApiPermissionCreate(ctx context.Context, in *ApiPermissionSaveReq, opts ...grpc.CallOption) (*ApiPermission, error)
	ApiPermissionUpdate(ctx context.Context, in *ApiPermissionSaveReq, opts ...grpc.CallOption) (*Ack, error)
	ApiPermissionDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
	RoleApiPermissions(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ApiPermissionIdsResp, error)
	RoleApiPermissionsAssign(ctx context.Context, in *RoleApiPermissionsReq, opts ...grpc.CallOption) (*Ack, error)
	UserApiPermissions(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ApiPermissionIdsResp, error)
	UserApiPermissionsAssign(ctx context.Context, in *UserApiPermissionsReq, opts ...grpc.CallOption) (*Ack, error)
	OrgCreate(ctx context.Context, in *OrgCreateReq, opts ...grpc.CallOption) (*Ack, error)
	OrgPage(ctx context.Context, in *OrgPageReq, opts ...grpc.CallOption) (*OrgPageResp, error)
	OrgTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrgTreeResp, error)
	OrgBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
	OrgUpdate(ctx context.Context, in *OrgUpdateReq, opts ...grpc.CallOption) (*Ack, error)
	OrgDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Org, error)
	OrgDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
	MenuUserTree(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*MenuListResp, error)
	MenuTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResp, error)
	MenuList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResp, error)
	MenuDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Menu, error)
	MenuCreate(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*Ack, error)
	MenuUpdate(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*Ack, error)
	MenuDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
	CaptchaEnabledTypes(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*CaptchaTypesResp, error)
	CaptchaImage(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*CaptchaDataResp, error)
	CaptchaSms(ctx context.Context, in *CaptchaPhoneReq, opts ...grpc.CallOption) (*CaptchaDataResp, error)
	CaptchaEmail(ctx context.Context, in *CaptchaEmailReq, opts ...grpc.CallOption) (*CaptchaDataResp, error)
}

type iamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIamServiceClient(cc grpc.ClientConnInterface) IamServiceClient {
	return &iamServiceClient{cc}
}

func (c *iamServiceClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, IamService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) ValidateAccessToken(ctx context.Context, in *ValidateAccessTokenReq, opts ...grpc.CallOption) (*ValidateAccessTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAccessTokenResp)
	err := c.cc.Invoke(ctx, IamService_ValidateAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionResp)
	err := c.cc.Invoke(ctx, IamService_CheckPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) AuthLogin(ctx context.Context, in *AuthLoginReq, opts ...grpc.CallOption) (*AuthLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthLoginResp)
	err := c.cc.Invoke(ctx, IamService_AuthLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserProfile(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, IamService_UserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserAuthContext(ctx context.Context, in *UserAuthContextReq, opts ...grpc.CallOption) (*UserAuthContextResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAuthContextResp)
	err := c.cc.Invoke(ctx, IamService_UserAuthContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserCreate(ctx context.Context, in *UserCreateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_UserCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserImport(ctx context.Context, in *UserImportReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_UserImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserPage(ctx context.Context, in *UserPageReq, opts ...grpc.CallOption) (*UserPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPageResp)
	err := c.cc.Invoke(ctx, IamService_UserPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_UserBatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserChangePassword(ctx context.Context, in *UserChangePasswordReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_UserChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_UserUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserResetPassword(ctx context.Context, in *UserPasswordReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_UserResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, IamService_UserDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_UserDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleCreate(ctx context.Context, in *RoleCreateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_RoleCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RolePage(ctx context.Context, in *RolePageReq, opts ...grpc.CallOption) (*RolePageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolePageResp)
	err := c.cc.Invoke(ctx, IamService_RolePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleAssign(ctx context.Context, in *AssignRoleReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_RoleAssign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleRemove(ctx context.Context, in *RemoveRoleReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_RoleRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleUser(ctx context.Context, in *UserRoleQueryReq, opts ...grpc.CallOption) (*RoleListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleListResp)
	err := c.cc.Invoke(ctx, IamService_RoleUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*UserListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListResp)
	err := c.cc.Invoke(ctx, IamService_RoleUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleAssignUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_RoleAssignUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleRemoveUsers(ctx context.Context, in *RoleUsersReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_RoleRemoveUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleMenus(ctx context.Context, in *RoleMenusReq, opts ...grpc.CallOption) (*MenuIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuIdsResp)
	err := c.cc.Invoke(ctx, IamService_RoleMenus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleAssignMenus(ctx context.Context, in *RoleMenusAssignReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_RoleAssignMenus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleUpdate(ctx context.Context, in *RoleUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_RoleUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Role, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Role)
	err := c.cc.Invoke(ctx, IamService_RoleDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_RoleDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) ApiPermissionTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApiPermissionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiPermissionListResp)
	err := c.cc.Invoke(ctx, IamService_ApiPermissionTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) ApiPermissionList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApiPermissionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiPermissionListResp)
	err := c.cc.Invoke(ctx, IamService_ApiPermissionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) ApiPermissionCreate(ctx context.Context, in *ApiPermissionSaveReq, opts ...grpc.CallOption) (*ApiPermission, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiPermission)
	err := c.cc.Invoke(ctx, IamService_ApiPermissionCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) ApiPermissionUpdate(ctx context.Context, in *ApiPermissionSaveReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_ApiPermissionUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) ApiPermissionDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_ApiPermissionDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleApiPermissions(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ApiPermissionIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiPermissionIdsResp)
	err := c.cc.Invoke(ctx, IamService_RoleApiPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) RoleApiPermissionsAssign(ctx context.Context, in *RoleApiPermissionsReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_RoleApiPermissionsAssign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserApiPermissions(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ApiPermissionIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiPermissionIdsResp)
	err := c.cc.Invoke(ctx, IamService_UserApiPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) UserApiPermissionsAssign(ctx context.Context, in *UserApiPermissionsReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_UserApiPermissionsAssign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) OrgCreate(ctx context.Context, in *OrgCreateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_OrgCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) OrgPage(ctx context.Context, in *OrgPageReq, opts ...grpc.CallOption) (*OrgPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgPageResp)
	err := c.cc.Invoke(ctx, IamService_OrgPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) OrgTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrgTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgTreeResp)
	err := c.cc.Invoke(ctx, IamService_OrgTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) OrgBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_OrgBatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) OrgUpdate(ctx context.Context, in *OrgUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_OrgUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) OrgDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Org, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Org)
	err := c.cc.Invoke(ctx, IamService_OrgDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) OrgDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_OrgDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) MenuUserTree(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*MenuListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuListResp)
	err := c.cc.Invoke(ctx, IamService_MenuUserTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) MenuTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuListResp)
	err := c.cc.Invoke(ctx, IamService_MenuTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) MenuList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuListResp)
	err := c.cc.Invoke(ctx, IamService_MenuList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) MenuDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Menu, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Menu)
	err := c.cc.Invoke(ctx, IamService_MenuDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) MenuCreate(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_MenuCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) MenuUpdate(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_MenuUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) MenuDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IamService_MenuDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) CaptchaEnabledTypes(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*CaptchaTypesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptchaTypesResp)
	err := c.cc.Invoke(ctx, IamService_CaptchaEnabledTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) CaptchaImage(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*CaptchaDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptchaDataResp)
	err := c.cc.Invoke(ctx, IamService_CaptchaImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) CaptchaSms(ctx context.Context, in *CaptchaPhoneReq, opts ...grpc.CallOption) (*CaptchaDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptchaDataResp)
	err := c.cc.Invoke(ctx, IamService_CaptchaSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) CaptchaEmail(ctx context.Context, in *CaptchaEmailReq, opts ...grpc.CallOption) (*CaptchaDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptchaDataResp)
	err := c.cc.Invoke(ctx, IamService_CaptchaEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IamServiceServer is the server API for IamService service.
// All implementations must embed UnimplementedIamServiceServer
// for forward compatibility.
type IamServiceServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	ValidateAccessToken(context.Context, *ValidateAccessTokenReq) (*ValidateAccessTokenResp, error)
	CheckPermission(context.Context, *CheckPermissionReq) (*CheckPermissionResp, error)
	AuthLogin(context.Context, *AuthLoginReq) (*AuthLoginResp, error)
	UserProfile(context.Context, *IdReq) (*User, error)
	UserAuthContext(context.Context, *UserAuthContextReq) (*UserAuthContextResp, error)
	UserCreate(context.Context, *UserCreateReq) (*Ack, error)
	UserImport(context.Context, *UserImportReq) (*Ack, error)
	UserPage(context.Context, *UserPageReq) (*UserPageResp, error)
	UserBatchDelete(context.Context, *BatchIdsReq) (*Ack, error)
	UserChangePassword(context.Context, *UserChangePasswordReq) (*Ack, error)
	UserUpdate(context.Context, *UserUpdateReq) (*Ack, error)
	UserResetPassword(context.Context, *UserPasswordReq) (*Ack, error)
	UserDetail(context.Context, *IdReq) (*User, error)
	UserDelete(context.Context, *IdReq) (*Ack, error)
	RoleCreate(context.Context, *RoleCreateReq) (*Ack, error)
	RolePage(context.Context, *RolePageReq) (*RolePageResp, error)
	RoleAssign(context.Context, *AssignRoleReq) (*Ack, error)
	RoleRemove(context.Context, *RemoveRoleReq) (*Ack, error)
	RoleUser(context.Context, *UserRoleQueryReq) (*RoleListResp, error)
	RoleUsers(context.Context, *RoleUsersReq) (*UserListResp, error)
	RoleAssignUsers(context.Context, *RoleUsersReq) (*Ack, error)
	RoleRemoveUsers(context.Context, *RoleUsersReq) (*Ack, error)
	RoleMenus(context.Context, *RoleMenusReq) (*MenuIdsResp, error)
	RoleAssignMenus(context.Context, *RoleMenusAssignReq) (*Ack, error)
	RoleUpdate(context.Context, *RoleUpdateReq) (*Ack, error)
	RoleDetail(context.Context, *IdReq) (*Role, error)
	RoleDelete(context.Context, *IdReq) (*Ack, error)
	ApiPermissionTree(context.Context, *Empty) (*ApiPermissionListResp, error)
	ApiPermissionList(context.Context, *Empty) (*ApiPermissionListResp, error)
	ApiPermissionCreate(context.Context, *ApiPermissionSaveReq) (*ApiPermission, error)
	ApiPermissionUpdate(context.Context, *ApiPermissionSaveReq) (*Ack, error)
	ApiPermissionDelete(context.Context, *IdReq) (*Ack, error)
	RoleApiPermissions(context.Context, *IdReq) (*ApiPermissionIdsResp, error)
	RoleApiPermissionsAssign(context.Context, *RoleApiPermissionsReq) (*Ack, error)
	UserApiPermissions(context.Context, *IdReq) (*ApiPermissionIdsResp, error)
	UserApiPermissionsAssign(context.Context, *UserApiPermissionsReq) (*Ack, error)
	OrgCreate(context.Context, *OrgCreateReq) (*Ack, error)
	OrgPage(context.Context, *OrgPageReq) (*OrgPageResp, error)
	OrgTree(context.Context, *Empty) (*OrgTreeResp, error)
	OrgBatchDelete(context.Context, *BatchIdsReq) (*Ack, error)
	OrgUpdate(context.Context, *OrgUpdateReq) (*Ack, error)
	OrgDetail(context.Context, *IdReq) (*Org, error)
	OrgDelete(context.Context, *IdReq) (*Ack, error)
	MenuUserTree(context.Context, *IdReq) (*MenuListResp, error)
	MenuTree(context.Context, *Empty) (*MenuListResp, error)
	MenuList(context.Context, *Empty) (*MenuListResp, error)
	MenuDetail(context.Context, *IdReq) (*Menu, error)
	MenuCreate(context.Context, *MenuReq) (*Ack, error)
	MenuUpdate(context.Context, *MenuReq) (*Ack, error)
	MenuDelete(context.Context, *IdReq) (*Ack, error)
	CaptchaEnabledTypes(context.Context, *CaptchaReq) (*CaptchaTypesResp, error)
	CaptchaImage(context.Context, *CaptchaReq) (*CaptchaDataResp, error)
	CaptchaSms(context.Context, *CaptchaPhoneReq) (*CaptchaDataResp, error)
	CaptchaEmail(context.Context, *CaptchaEmailReq) (*CaptchaDataResp, error)
	mustEmbedUnimplementedIamServiceServer()
}

// UnimplementedIamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIamServiceServer struct{}

func (UnimplementedIamServiceServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedIamServiceServer) ValidateAccessToken(context.Context, *ValidateAccessTokenReq) (*ValidateAccessTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAccessToken not implemented")
}
func (UnimplementedIamServiceServer) CheckPermission(context.Context, *CheckPermissionReq) (*CheckPermissionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPermission not implemented")
}
func (UnimplementedIamServiceServer) AuthLogin(context.Context, *AuthLoginReq) (*AuthLoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthLogin not implemented")
}
func (UnimplementedIamServiceServer) UserProfile(context.Context, *IdReq) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method UserProfile not implemented")
}
func (UnimplementedIamServiceServer) UserAuthContext(context.Context, *UserAuthContextReq) (*UserAuthContextResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserAuthContext not implemented")
}
func (UnimplementedIamServiceServer) UserCreate(context.Context, *UserCreateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCreate not implemented")
}
func (UnimplementedIamServiceServer) UserImport(context.Context, *UserImportReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UserImport not implemented")
}
func (UnimplementedIamServiceServer) UserPage(context.Context, *UserPageReq) (*UserPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserPage not implemented")
}
func (UnimplementedIamServiceServer) UserBatchDelete(context.Context, *BatchIdsReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UserBatchDelete not implemented")
}
func (UnimplementedIamServiceServer) UserChangePassword(context.Context, *UserChangePasswordReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UserChangePassword not implemented")
}
func (UnimplementedIamServiceServer) UserUpdate(context.Context, *UserUpdateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UserUpdate not implemented")
}
func (UnimplementedIamServiceServer) UserResetPassword(context.Context, *UserPasswordReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UserResetPassword not implemented")
}
func (UnimplementedIamServiceServer) UserDetail(context.Context, *IdReq) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method UserDetail not implemented")
}
func (UnimplementedIamServiceServer) UserDelete(context.Context, *IdReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UserDelete not implemented")
}
func (UnimplementedIamServiceServer) RoleCreate(context.Context, *RoleCreateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleCreate not implemented")
}
func (UnimplementedIamServiceServer) RolePage(context.Context, *RolePageReq) (*RolePageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RolePage not implemented")
}
func (UnimplementedIamServiceServer) RoleAssign(context.Context, *AssignRoleReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleAssign not implemented")
}
func (UnimplementedIamServiceServer) RoleRemove(context.Context, *RemoveRoleReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleRemove not implemented")
}
func (UnimplementedIamServiceServer) RoleUser(context.Context, *UserRoleQueryReq) (*RoleListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleUser not implemented")
}
func (UnimplementedIamServiceServer) RoleUsers(context.Context, *RoleUsersReq) (*UserListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleUsers not implemented")
}
func (UnimplementedIamServiceServer) RoleAssignUsers(context.Context, *RoleUsersReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleAssignUsers not implemented")
}
func (UnimplementedIamServiceServer) RoleRemoveUsers(context.Context, *RoleUsersReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleRemoveUsers not implemented")
}
func (UnimplementedIamServiceServer) RoleMenus(context.Context, *RoleMenusReq) (*MenuIdsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleMenus not implemented")
}
func (UnimplementedIamServiceServer) RoleAssignMenus(context.Context, *RoleMenusAssignReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleAssignMenus not implemented")
}
func (UnimplementedIamServiceServer) RoleUpdate(context.Context, *RoleUpdateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleUpdate not implemented")
}
func (UnimplementedIamServiceServer) RoleDetail(context.Context, *IdReq) (*Role, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleDetail not implemented")
}
func (UnimplementedIamServiceServer) RoleDelete(context.Context, *IdReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleDelete not implemented")
}
func (UnimplementedIamServiceServer) ApiPermissionTree(context.Context, *Empty) (*ApiPermissionListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApiPermissionTree not implemented")
}
func (UnimplementedIamServiceServer) ApiPermissionList(context.Context, *Empty) (*ApiPermissionListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApiPermissionList not implemented")
}
func (UnimplementedIamServiceServer) ApiPermissionCreate(context.Context, *ApiPermissionSaveReq) (*ApiPermission, error) {
	return nil, status.Error(codes.Unimplemented, "method ApiPermissionCreate not implemented")
}
func (UnimplementedIamServiceServer) ApiPermissionUpdate(context.Context, *ApiPermissionSaveReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ApiPermissionUpdate not implemented")
}
func (UnimplementedIamServiceServer) ApiPermissionDelete(context.Context, *IdReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ApiPermissionDelete not implemented")
}
func (UnimplementedIamServiceServer) RoleApiPermissions(context.Context, *IdReq) (*ApiPermissionIdsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleApiPermissions not implemented")
}
func (UnimplementedIamServiceServer) RoleApiPermissionsAssign(context.Context, *RoleApiPermissionsReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleApiPermissionsAssign not implemented")
}
func (UnimplementedIamServiceServer) UserApiPermissions(context.Context, *IdReq) (*ApiPermissionIdsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserApiPermissions not implemented")
}
func (UnimplementedIamServiceServer) UserApiPermissionsAssign(context.Context, *UserApiPermissionsReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UserApiPermissionsAssign not implemented")
}
func (UnimplementedIamServiceServer) OrgCreate(context.Context, *OrgCreateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgCreate not implemented")
}
func (UnimplementedIamServiceServer) OrgPage(context.Context, *OrgPageReq) (*OrgPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgPage not implemented")
}
func (UnimplementedIamServiceServer) OrgTree(context.Context, *Empty) (*OrgTreeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgTree not implemented")
}
func (UnimplementedIamServiceServer) OrgBatchDelete(context.Context, *BatchIdsReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgBatchDelete not implemented")
}
func (UnimplementedIamServiceServer) OrgUpdate(context.Context, *OrgUpdateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgUpdate not implemented")
}
func (UnimplementedIamServiceServer) OrgDetail(context.Context, *IdReq) (*Org, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgDetail not implemented")
}
func (UnimplementedIamServiceServer) OrgDelete(context.Context, *IdReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgDelete not implemented")
}
func (UnimplementedIamServiceServer) MenuUserTree(context.Context, *IdReq) (*MenuListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuUserTree not implemented")
}
func (UnimplementedIamServiceServer) MenuTree(context.Context, *Empty) (*MenuListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuTree not implemented")
}
func (UnimplementedIamServiceServer) MenuList(context.Context, *Empty) (*MenuListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuList not implemented")
}
func (UnimplementedIamServiceServer) MenuDetail(context.Context, *IdReq) (*Menu, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuDetail not implemented")
}
func (UnimplementedIamServiceServer) MenuCreate(context.Context, *MenuReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuCreate not implemented")
}
func (UnimplementedIamServiceServer) MenuUpdate(context.Context, *MenuReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuUpdate not implemented")
}
func (UnimplementedIamServiceServer) MenuDelete(context.Context, *IdReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuDelete not implemented")
}
func (UnimplementedIamServiceServer) CaptchaEnabledTypes(context.Context, *CaptchaReq) (*CaptchaTypesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptchaEnabledTypes not implemented")
}
func (UnimplementedIamServiceServer) CaptchaImage(context.Context, *CaptchaReq) (*CaptchaDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptchaImage not implemented")
}
func (UnimplementedIamServiceServer) CaptchaSms(context.Context, *CaptchaPhoneReq) (*CaptchaDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptchaSms not implemented")
}
func (UnimplementedIamServiceServer) CaptchaEmail(context.Context, *CaptchaEmailReq) (*CaptchaDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptchaEmail not implemented")
}
func (UnimplementedIamServiceServer) mustEmbedUnimplementedIamServiceServer() {}
func (UnimplementedIamServiceServer) testEmbeddedByValue()                    {}

// UnsafeIamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IamServiceServer will
// result in compilation errors.
type UnsafeIamServiceServer interface {
	mustEmbedUnimplementedIamServiceServer()
}

func RegisterIamServiceServer(s grpc.ServiceRegistrar, srv IamServiceServer) {
	// If the following call panics, it indicates UnimplementedIamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IamService_ServiceDesc, srv)
}

func _IamService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_ValidateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAccessTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).ValidateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_ValidateAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).ValidateAccessToken(ctx, req.(*ValidateAccessTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_CheckPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).CheckPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_CheckPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).CheckPermission(ctx, req.(*CheckPermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_AuthLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).AuthLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_AuthLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).AuthLogin(ctx, req.(*AuthLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserProfile(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserAuthContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuthContextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserAuthContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserAuthContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserAuthContext(ctx, req.(*UserAuthContextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserCreate(ctx, req.(*UserCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserImportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserImport(ctx, req.(*UserImportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserPage(ctx, req.(*UserPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserBatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserBatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserBatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserBatchDelete(ctx, req.(*BatchIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChangePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserChangePassword(ctx, req.(*UserChangePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserUpdate(ctx, req.(*UserUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserResetPassword(ctx, req.(*UserPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserDetail(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserDelete(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleCreate(ctx, req.(*RoleCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RolePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolePageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RolePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RolePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RolePage(ctx, req.(*RolePageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleAssign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleAssign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleAssign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleAssign(ctx, req.(*AssignRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleRemove(ctx, req.(*RemoveRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRoleQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleUser(ctx, req.(*UserRoleQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleUsers(ctx, req.(*RoleUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleAssignUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleAssignUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleAssignUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleAssignUsers(ctx, req.(*RoleUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleRemoveUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleRemoveUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleRemoveUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleRemoveUsers(ctx, req.(*RoleUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleMenusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleMenus(ctx, req.(*RoleMenusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleAssignMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleMenusAssignReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleAssignMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleAssignMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleAssignMenus(ctx, req.(*RoleMenusAssignReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleUpdate(ctx, req.(*RoleUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleDetail(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleDelete(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_ApiPermissionTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).ApiPermissionTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_ApiPermissionTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).ApiPermissionTree(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_ApiPermissionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).ApiPermissionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_ApiPermissionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).ApiPermissionList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_ApiPermissionCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiPermissionSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).ApiPermissionCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_ApiPermissionCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).ApiPermissionCreate(ctx, req.(*ApiPermissionSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_ApiPermissionUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiPermissionSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).ApiPermissionUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_ApiPermissionUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).ApiPermissionUpdate(ctx, req.(*ApiPermissionSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_ApiPermissionDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).ApiPermissionDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_ApiPermissionDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).ApiPermissionDelete(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleApiPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleApiPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleApiPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleApiPermissions(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_RoleApiPermissionsAssign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleApiPermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).RoleApiPermissionsAssign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_RoleApiPermissionsAssign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).RoleApiPermissionsAssign(ctx, req.(*RoleApiPermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserApiPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserApiPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserApiPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserApiPermissions(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_UserApiPermissionsAssign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserApiPermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).UserApiPermissionsAssign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_UserApiPermissionsAssign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).UserApiPermissionsAssign(ctx, req.(*UserApiPermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_OrgCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).OrgCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_OrgCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).OrgCreate(ctx, req.(*OrgCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_OrgPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).OrgPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_OrgPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).OrgPage(ctx, req.(*OrgPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_OrgTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).OrgTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_OrgTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).OrgTree(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_OrgBatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).OrgBatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_OrgBatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).OrgBatchDelete(ctx, req.(*BatchIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_OrgUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).OrgUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_OrgUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).OrgUpdate(ctx, req.(*OrgUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_OrgDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).OrgDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_OrgDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).OrgDetail(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_OrgDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).OrgDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_OrgDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).OrgDelete(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_MenuUserTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).MenuUserTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_MenuUserTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).MenuUserTree(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_MenuTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).MenuTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_MenuTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).MenuTree(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_MenuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).MenuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_MenuList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).MenuList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_MenuDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).MenuDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_MenuDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).MenuDetail(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_MenuCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).MenuCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_MenuCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).MenuCreate(ctx, req.(*MenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_MenuUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).MenuUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_MenuUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).MenuUpdate(ctx, req.(*MenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_MenuDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).MenuDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_MenuDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).MenuDelete(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_CaptchaEnabledTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptchaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).CaptchaEnabledTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_CaptchaEnabledTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).CaptchaEnabledTypes(ctx, req.(*CaptchaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_CaptchaImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptchaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).CaptchaImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_CaptchaImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).CaptchaImage(ctx, req.(*CaptchaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_CaptchaSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptchaPhoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).CaptchaSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_CaptchaSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).CaptchaSms(ctx, req.(*CaptchaPhoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_CaptchaEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptchaEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).CaptchaEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_CaptchaEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).CaptchaEmail(ctx, req.(*CaptchaEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IamService_ServiceDesc is the grpc.ServiceDesc for IamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.IamService",
	HandlerType: (*IamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _IamService_Ping_Handler,
		},
		{
			MethodName: "ValidateAccessToken",
			Handler:    _IamService_ValidateAccessToken_Handler,
		},
		{
			MethodName: "CheckPermission",
			Handler:    _IamService_CheckPermission_Handler,
		},
		{
			MethodName: "AuthLogin",
			Handler:    _IamService_AuthLogin_Handler,
		},
		{
			MethodName: "UserProfile",
			Handler:    _IamService_UserProfile_Handler,
		},
		{
			MethodName: "UserAuthContext",
			Handler:    _IamService_UserAuthContext_Handler,
		},
		{
			MethodName: "UserCreate",
			Handler:    _IamService_UserCreate_Handler,
		},
		{
			MethodName: "UserImport",
			Handler:    _IamService_UserImport_Handler,
		},
		{
			MethodName: "UserPage",
			Handler:    _IamService_UserPage_Handler,
		},
		{
			MethodName: "UserBatchDelete",
			Handler:    _IamService_UserBatchDelete_Handler,
		},
		{
			MethodName: "UserChangePassword",
			Handler:    _IamService_UserChangePassword_Handler,
		},
		{
			MethodName: "UserUpdate",
			Handler:    _IamService_UserUpdate_Handler,
		},
		{
			MethodName: "UserResetPassword",
			Handler:    _IamService_UserResetPassword_Handler,
		},
		{
			MethodName: "UserDetail",
			Handler:    _IamService_UserDetail_Handler,
		},
		{
			MethodName: "UserDelete",
			Handler:    _IamService_UserDelete_Handler,
		},
		{
			MethodName: "RoleCreate",
			Handler:    _IamService_RoleCreate_Handler,
		},
		{
			MethodName: "RolePage",
			Handler:    _IamService_RolePage_Handler,
		},
		{
			MethodName: "RoleAssign",
			Handler:    _IamService_RoleAssign_Handler,
		},
		{
			MethodName: "RoleRemove",
			Handler:    _IamService_RoleRemove_Handler,
		},
		{
			MethodName: "RoleUser",
			Handler:    _IamService_RoleUser_Handler,
		},
		{
			MethodName: "RoleUsers",
			Handler:    _IamService_RoleUsers_Handler,
		},
		{
			MethodName: "RoleAssignUsers",
			Handler:    _IamService_RoleAssignUsers_Handler,
		},
		{
			MethodName: "RoleRemoveUsers",
			Handler:    _IamService_RoleRemoveUsers_Handler,
		},
		{
			MethodName: "RoleMenus",
			Handler:    _IamService_RoleMenus_Handler,
		},
		{
			MethodName: "RoleAssignMenus",
			Handler:    _IamService_RoleAssignMenus_Handler,
		},
		{
			MethodName: "RoleUpdate",
			Handler:    _IamService_RoleUpdate_Handler,
		},
		{
			MethodName: "RoleDetail",
			Handler:    _IamService_RoleDetail_Handler,
		},
		{
			MethodName: "RoleDelete",
			Handler:    _IamService_RoleDelete_Handler,
		},
		{
			MethodName: "ApiPermissionTree",
			Handler:    _IamService_ApiPermissionTree_Handler,
		},
		{
			MethodName: "ApiPermissionList",
			Handler:    _IamService_ApiPermissionList_Handler,
		},
		{
			MethodName: "ApiPermissionCreate",
			Handler:    _IamService_ApiPermissionCreate_Handler,
		},
		{
			MethodName: "ApiPermissionUpdate",
			Handler:    _IamService_ApiPermissionUpdate_Handler,
		},
		{
			MethodName: "ApiPermissionDelete",
			Handler:    _IamService_ApiPermissionDelete_Handler,
		},
		{
			MethodName: "RoleApiPermissions",
			Handler:    _IamService_RoleApiPermissions_Handler,
		},
		{
			MethodName: "RoleApiPermissionsAssign",
			Handler:    _IamService_RoleApiPermissionsAssign_Handler,
		},
		{
			MethodName: "UserApiPermissions",
			Handler:    _IamService_UserApiPermissions_Handler,
		},
		{
			MethodName: "UserApiPermissionsAssign",
			Handler:    _IamService_UserApiPermissionsAssign_Handler,
		},
		{
			MethodName: "OrgCreate",
			Handler:    _IamService_OrgCreate_Handler,
		},
		{
			MethodName: "OrgPage",
			Handler:    _IamService_OrgPage_Handler,
		},
		{
			MethodName: "OrgTree",
			Handler:    _IamService_OrgTree_Handler,
		},
		{
			MethodName: "OrgBatchDelete",
			Handler:    _IamService_OrgBatchDelete_Handler,
		},
		{
			MethodName: "OrgUpdate",
			Handler:    _IamService_OrgUpdate_Handler,
		},
		{
			MethodName: "OrgDetail",
			Handler:    _IamService_OrgDetail_Handler,
		},
		{
			MethodName: "OrgDelete",
			Handler:    _IamService_OrgDelete_Handler,
		},
		{
			MethodName: "MenuUserTree",
			Handler:    _IamService_MenuUserTree_Handler,
		},
		{
			MethodName: "MenuTree",
			Handler:    _IamService_MenuTree_Handler,
		},
		{
			MethodName: "MenuList",
			Handler:    _IamService_MenuList_Handler,
		},
		{
			MethodName: "MenuDetail",
			Handler:    _IamService_MenuDetail_Handler,
		},
		{
			MethodName: "MenuCreate",
			Handler:    _IamService_MenuCreate_Handler,
		},
		{
			MethodName: "MenuUpdate",
			Handler:    _IamService_MenuUpdate_Handler,
		},
		{
			MethodName: "MenuDelete",
			Handler:    _IamService_MenuDelete_Handler,
		},
		{
			MethodName: "CaptchaEnabledTypes",
			Handler:    _IamService_CaptchaEnabledTypes_Handler,
		},
		{
			MethodName: "CaptchaImage",
			Handler:    _IamService_CaptchaImage_Handler,
		},
		{
			MethodName: "CaptchaSms",
			Handler:    _IamService_CaptchaSms_Handler,
		},
		{
			MethodName: "CaptchaEmail",
			Handler:    _IamService_CaptchaEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam.proto",
}
