// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AttachmentIdPathReq struct {
	AttachmentId int64 `path:"attachmentId"`
}

type BatchIdsReq struct {
	Ids []int64 `json:"ids"`
}

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type ConfigCodeQueryReq struct {
	Code string `form:"code"`
}

type ConfigCreateReq struct {
	Name     string      `json:"name"`
	Code     string      `json:"code"`
	Data     interface{} `json:"data,optional"`
	Remark   string      `json:"remark,optional"`
	CreateBy int64       `json:"createBy"`
	UpdateBy int64       `json:"updateBy"`
}

type ConfigPageReq struct {
	PageNum  int64  `json:"pageNum,optional"`
	PageSize int64  `json:"pageSize,optional"`
	Name     string `json:"name,optional"`
	Code     string `json:"code,optional"`
}

type ConfigUpdateReq struct {
	Id       int64       `path:"id"`
	Name     string      `json:"name"`
	Code     string      `json:"code"`
	Data     interface{} `json:"data,optional"`
	Remark   string      `json:"remark,optional"`
	UpdateBy int64       `json:"updateBy"`
}

type DictCreateReq struct {
	ParentId  int64  `json:"parentId,optional"`
	DictType  string `json:"dictType"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	Sort      int64  `json:"sort,optional"`
	IsDefault bool   `json:"isDefault,optional"`
	Status    int32  `json:"status,optional"`
	Remark    string `json:"remark,optional"`
	CreateBy  int64  `json:"createBy,optional"`
	UpdateBy  int64  `json:"updateBy,optional"`
}

type DictLabelQueryReq struct {
	DictType  string `form:"dictType"`
	DictValue string `form:"dictValue"`
}

type DictPageReq struct {
	PageNum   int64  `json:"pageNum,optional"`
	PageSize  int64  `json:"pageSize,optional"`
	DictType  string `json:"dictType,optional"`
	DictLabel string `json:"dictLabel,optional"`
	Status    int32  `json:"status,optional"`
}

type DictTypeQueryReq struct {
	DictType string `form:"dictType"`
	ParentId int64  `form:"parentId,optional"`
}

type DictUpdateReq struct {
	Id        int64  `path:"id"`
	ParentId  int64  `json:"parentId,optional"`
	DictType  string `json:"dictType"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	Sort      int64  `json:"sort,optional"`
	IsDefault bool   `json:"isDefault,optional"`
	Status    int32  `json:"status,optional"`
	Remark    string `json:"remark,optional"`
	UpdateBy  int64  `json:"updateBy,optional"`
}

type IdPathReq struct {
	Id int64 `path:"id"`
}

type LogCleanReq struct {
	Days int64 `json:"days"`
}

type LoginLogPageReq struct {
	PageNum   int64  `json:"pageNum,optional"`
	PageSize  int64  `json:"pageSize,optional"`
	UserName  string `json:"userName,optional"`
	Ipaddr    string `json:"ipaddr,optional"`
	Status    int32  `json:"status,optional"`
	StartTime string `json:"startTime,optional"`
	EndTime   string `json:"endTime,optional"`
}

type LoginLogReq struct {
	UserName      string `json:"userName"`
	Ipaddr        string `json:"ipaddr,optional"`
	LoginLocation string `json:"loginLocation,optional"`
	Browser       string `json:"browser,optional"`
	Os            string `json:"os,optional"`
	Status        int32  `json:"status,optional"`
	Msg           string `json:"msg,optional"`
	ClientId      string `json:"clientId,optional"`
}

type LoginLogUpdateReq struct {
	Id            int64  `json:"id"`
	UserName      string `json:"userName,optional"`
	Ipaddr        string `json:"ipaddr,optional"`
	LoginLocation string `json:"loginLocation,optional"`
	Browser       string `json:"browser,optional"`
	Os            string `json:"os,optional"`
	Status        int32  `json:"status,optional"`
	Msg           string `json:"msg,optional"`
	ClientId      string `json:"clientId,optional"`
}

type OperLogPageReq struct {
	PageNum      int64  `json:"pageNum,optional"`
	PageSize     int64  `json:"pageSize,optional"`
	Title        string `json:"title,optional"`
	OperName     string `json:"operName,optional"`
	BusinessType string `json:"businessType,optional"`
	Status       string `json:"status,optional"`
	StartTime    string `json:"startTime,optional"`
	EndTime      string `json:"endTime,optional"`
}

type OperLogReq struct {
	Title         string `json:"title"`
	BusinessType  string `json:"businessType,optional"`
	Method        string `json:"method,optional"`
	RequestMethod string `json:"requestMethod,optional"`
	DeviceType    string `json:"deviceType,optional"`
	OperName      string `json:"operName,optional"`
	OperUrl       string `json:"operUrl,optional"`
	OperIp        string `json:"operIp,optional"`
	OperLocation  string `json:"operLocation,optional"`
	OperParam     string `json:"operParam,optional"`
	JsonResult    string `json:"jsonResult,optional"`
	Status        string `json:"status,optional"`
	ErrorMsg      string `json:"errorMsg,optional"`
	CostTime      int64  `json:"costTime,optional"`
	UserAgent     string `json:"userAgent,optional"`
}

type OperLogUpdateReq struct {
	Id            int64  `json:"id"`
	Title         string `json:"title,optional"`
	BusinessType  string `json:"businessType,optional"`
	Method        string `json:"method,optional"`
	RequestMethod string `json:"requestMethod,optional"`
	DeviceType    string `json:"deviceType,optional"`
	OperName      string `json:"operName,optional"`
	OperUrl       string `json:"operUrl,optional"`
	OperIp        string `json:"operIp,optional"`
	OperLocation  string `json:"operLocation,optional"`
	OperParam     string `json:"operParam,optional"`
	JsonResult    string `json:"jsonResult,optional"`
	Status        string `json:"status,optional"`
	ErrorMsg      string `json:"errorMsg,optional"`
	CostTime      int64  `json:"costTime,optional"`
	UserAgent     string `json:"userAgent,optional"`
}

type RoleIdPathReq struct {
	RoleId int64 `path:"roleId"`
}

type StringIdPathReq struct {
	Id string `path:"id"`
}
