// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type SConfig struct {
	Id int64 `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`

	Name string `gorm:"column:name" json:"name"`

	Code string `gorm:"column:code" json:"code"`

	Data string `gorm:"column:data" json:"data"`

	Remark sql.NullString `gorm:"column:remark" json:"remark"`

	CreateBy sql.NullInt64 `gorm:"column:create_by" json:"create_by"`

	CreatedTime sql.NullTime `gorm:"column:created_time" json:"created_time"`

	UpdateBy sql.NullInt64 `gorm:"column:update_by" json:"update_by"`

	UpdatedTime sql.NullTime `gorm:"column:updated_time" json:"updated_time"`
}

func (m *SConfigModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[SConfig](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *SConfigModel) FindOne(ctx context.Context, id int64) (*SConfig, error) {
	data, err := gorm.G[SConfig](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *SConfigModel) FindOneByCode(ctx context.Context, code string) (*SConfig, error) {
	data, err := gorm.G[SConfig](m.db).
		Where("code = $1", code).
		First(ctx)
	return &data, err
}

func (m *SConfigModel) Insert(ctx context.Context, data *SConfig) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[SConfig](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *SConfigModel) Update(ctx context.Context, data *SConfig) error {
	return m.db.WithContext(ctx).
		Model(&SConfig{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (SConfig) TableName() string {
	return "s_config"
}
