// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type SLoginLog struct {
	Id            int64          `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`
	UserName      sql.NullString `gorm:"column:user_name" json:"user_name"`
	Ipaddr        sql.NullString `gorm:"column:ipaddr" json:"ipaddr"`
	LoginLocation sql.NullString `gorm:"column:login_location" json:"login_location"`
	Browser       sql.NullString `gorm:"column:browser" json:"browser"`
	Os            sql.NullString `gorm:"column:os" json:"os"`
	Status        int64          `gorm:"column:status" json:"status"`
	Msg           sql.NullString `gorm:"column:msg" json:"msg"`
	LoginTime     sql.NullTime   `gorm:"column:login_time" json:"login_time"`
	ClientId      sql.NullString `gorm:"column:client_id" json:"client_id"`
}

func (m *SLoginLogModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[SLoginLog](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *SLoginLogModel) FindOne(ctx context.Context, id int64) (*SLoginLog, error) {
	data, err := gorm.G[SLoginLog](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *SLoginLogModel) Insert(ctx context.Context, data *SLoginLog) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[SLoginLog](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *SLoginLogModel) Update(ctx context.Context, data *SLoginLog) error {
	return m.db.WithContext(ctx).
		Model(&SLoginLog{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (SLoginLog) TableName() string {
	return "s_login_log"
}
