// Code generated by goctl with the repository GORM templates. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

type SOperLog struct {
	Id int64 `gorm:"column:id;primaryKey;autoIncrement:false" autogen:"int64" json:"id"`

	Title sql.NullString `gorm:"column:title" json:"title"`

	BusinessType sql.NullString `gorm:"column:business_type" json:"business_type"`

	Method sql.NullString `gorm:"column:method" json:"method"`

	RequestMethod sql.NullString `gorm:"column:request_method" json:"request_method"`

	DeviceType sql.NullString `gorm:"column:device_type" json:"device_type"`

	OperName sql.NullString `gorm:"column:oper_name" json:"oper_name"`

	OperUrl sql.NullString `gorm:"column:oper_url" json:"oper_url"`

	OperIp sql.NullString `gorm:"column:oper_ip" json:"oper_ip"`

	OperLocation sql.NullString `gorm:"column:oper_location" json:"oper_location"`

	OperParam sql.NullString `gorm:"column:oper_param" json:"oper_param"`

	JsonResult sql.NullString `gorm:"column:json_result" json:"json_result"`

	Status sql.NullString `gorm:"column:status" json:"status"`

	ErrorMsg sql.NullString `gorm:"column:error_msg" json:"error_msg"`

	OperTime sql.NullTime `gorm:"column:oper_time" json:"oper_time"`

	CostTime sql.NullInt64 `gorm:"column:cost_time" json:"cost_time"`

	UserAgent sql.NullString `gorm:"column:user_agent" json:"user_agent"`
}

func (m *SOperLogModel) Delete(ctx context.Context, id int64) error {
	_, err := gorm.G[SOperLog](m.db).
		Where("id = ?", id).
		Delete(ctx)
	return err
}

func (m *SOperLogModel) FindOne(ctx context.Context, id int64) (*SOperLog, error) {
	data, err := gorm.G[SOperLog](m.db).
		Where("id = ?", id).
		First(ctx)
	return &data, err
}

func (m *SOperLogModel) Insert(ctx context.Context, data *SOperLog) (sql.Result, error) {
	result := gorm.WithResult()
	err := gorm.G[SOperLog](m.db, result).Create(ctx, data)
	return result.Result, err
}

func (m *SOperLogModel) Update(ctx context.Context, data *SOperLog) error {
	return m.db.WithContext(ctx).
		Model(&SOperLog{}).
		Where("id = ?", data.Id).
		Select("*").
		Omit("id", "create_at", "created_at", "create_time", "update_at", "updated_at", "update_time").
		Updates(data).Error
}

func (SOperLog) TableName() string {
	return "s_oper_log"
}
