// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: realtime.proto

package realtimeservice

import (
	"context"

	"github.com/gcc798/microservice-kit/application/realtime/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PublishToUsersReq  = pb.PublishToUsersReq
	PublishToUsersResp = pb.PublishToUsersResp

	RealtimeService interface {
		PublishToUsers(ctx context.Context, in *PublishToUsersReq, opts ...grpc.CallOption) (*PublishToUsersResp, error)
	}

	defaultRealtimeService struct {
		cli zrpc.Client
	}
)

func NewRealtimeService(cli zrpc.Client) RealtimeService {
	return &defaultRealtimeService{
		cli: cli,
	}
}

func (m *defaultRealtimeService) PublishToUsers(ctx context.Context, in *PublishToUsersReq, opts ...grpc.CallOption) (*PublishToUsersResp, error) {
	client := pb.NewRealtimeServiceClient(m.cli.Conn())
	return client.PublishToUsers(ctx, in, opts...)
}
