// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	config "github.com/gcc798/microservice-kit/application/sys-api/internal/handler/config"
	dict "github.com/gcc798/microservice-kit/application/sys-api/internal/handler/dict"
	health "github.com/gcc798/microservice-kit/application/sys-api/internal/handler/health"
	loginlog "github.com/gcc798/microservice-kit/application/sys-api/internal/handler/loginlog"
	operlog "github.com/gcc798/microservice-kit/application/sys-api/internal/handler/operlog"
	"github.com/gcc798/microservice-kit/application/sys-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/config",
				Handler: config.ConfigCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/config/:id",
				Handler: config.ConfigUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/:id",
				Handler: config.ConfigDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/config/:id",
				Handler: config.ConfigDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/config/batch",
				Handler: config.ConfigBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/code",
				Handler: config.ConfigCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/data",
				Handler: config.ConfigDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/config/page",
				Handler: config.ConfigPageHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/dict",
				Handler: dict.DictCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/dict/:id",
				Handler: dict.DictUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/dict/:id",
				Handler: dict.DictDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/dict/:id",
				Handler: dict.DictDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/dict/batch",
				Handler: dict.DictBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/dict/label",
				Handler: dict.DictLabelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/dict/page",
				Handler: dict.DictPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/dict/type",
				Handler: dict.DictTypeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/live",
				Handler: health.HealthLiveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/ready",
				Handler: health.HealthReadyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/startup",
				Handler: health.HealthStartupHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/loginLog",
				Handler: loginlog.LoginLogCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/loginLog/:id",
				Handler: loginlog.LoginLogUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/loginLog/:id",
				Handler: loginlog.LoginLogDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/loginLog/:id",
				Handler: loginlog.LoginLogDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/loginLog/batch",
				Handler: loginlog.LoginLogBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/loginLog/clean",
				Handler: loginlog.LoginLogCleanHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/loginLog/page",
				Handler: loginlog.LoginLogPageHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/operLog",
				Handler: operlog.OperLogCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/operLog/:id",
				Handler: operlog.OperLogUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/operLog/:id",
				Handler: operlog.OperLogDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/operLog/:id",
				Handler: operlog.OperLogDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/operLog/batch",
				Handler: operlog.OperLogBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/operLog/clean",
				Handler: operlog.OperLogCleanHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/operLog/page",
				Handler: operlog.OperLogPageHandler(serverCtx),
			},
		},
	)
}
