// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: sys.proto

package server

import (
	"context"

	"github.com/gcc798/microservice-kit/application/sys-rpc/internal/logic/sysservice"
	"github.com/gcc798/microservice-kit/application/sys-rpc/internal/svc"
	"github.com/gcc798/microservice-kit/application/sys-rpc/pb"
)

type SysServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSysServiceServer
}

func NewSysServiceServer(svcCtx *svc.ServiceContext) *SysServiceServer {
	return &SysServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SysServiceServer) Ping(ctx context.Context, in *pb.PingReq) (*pb.PingResp, error) {
	l := sysservicelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *SysServiceServer) DictCreate(ctx context.Context, in *pb.DictCreateReq) (*pb.Ack, error) {
	l := sysservicelogic.NewDictCreateLogic(ctx, s.svcCtx)
	return l.DictCreate(in)
}

func (s *SysServiceServer) DictPage(ctx context.Context, in *pb.DictPageReq) (*pb.DictPageResp, error) {
	l := sysservicelogic.NewDictPageLogic(ctx, s.svcCtx)
	return l.DictPage(in)
}

func (s *SysServiceServer) DictBatchDelete(ctx context.Context, in *pb.BatchIdsReq) (*pb.Ack, error) {
	l := sysservicelogic.NewDictBatchDeleteLogic(ctx, s.svcCtx)
	return l.DictBatchDelete(in)
}

func (s *SysServiceServer) DictType(ctx context.Context, in *pb.DictTypeQueryReq) (*pb.DictListResp, error) {
	l := sysservicelogic.NewDictTypeLogic(ctx, s.svcCtx)
	return l.DictType(in)
}

func (s *SysServiceServer) DictLabel(ctx context.Context, in *pb.DictLabelQueryReq) (*pb.DictLabelResp, error) {
	l := sysservicelogic.NewDictLabelLogic(ctx, s.svcCtx)
	return l.DictLabel(in)
}

func (s *SysServiceServer) DictUpdate(ctx context.Context, in *pb.DictUpdateReq) (*pb.Ack, error) {
	l := sysservicelogic.NewDictUpdateLogic(ctx, s.svcCtx)
	return l.DictUpdate(in)
}

func (s *SysServiceServer) DictDetail(ctx context.Context, in *pb.IdReq) (*pb.Dict, error) {
	l := sysservicelogic.NewDictDetailLogic(ctx, s.svcCtx)
	return l.DictDetail(in)
}

func (s *SysServiceServer) DictDelete(ctx context.Context, in *pb.IdReq) (*pb.Ack, error) {
	l := sysservicelogic.NewDictDeleteLogic(ctx, s.svcCtx)
	return l.DictDelete(in)
}

func (s *SysServiceServer) ConfigCreate(ctx context.Context, in *pb.ConfigCreateReq) (*pb.Ack, error) {
	l := sysservicelogic.NewConfigCreateLogic(ctx, s.svcCtx)
	return l.ConfigCreate(in)
}

func (s *SysServiceServer) ConfigPage(ctx context.Context, in *pb.ConfigPageReq) (*pb.ConfigPageResp, error) {
	l := sysservicelogic.NewConfigPageLogic(ctx, s.svcCtx)
	return l.ConfigPage(in)
}

func (s *SysServiceServer) ConfigBatchDelete(ctx context.Context, in *pb.BatchIdsReq) (*pb.Ack, error) {
	l := sysservicelogic.NewConfigBatchDeleteLogic(ctx, s.svcCtx)
	return l.ConfigBatchDelete(in)
}

func (s *SysServiceServer) ConfigCode(ctx context.Context, in *pb.ConfigCodeQueryReq) (*pb.ConfigListResp, error) {
	l := sysservicelogic.NewConfigCodeLogic(ctx, s.svcCtx)
	return l.ConfigCode(in)
}

func (s *SysServiceServer) ConfigData(ctx context.Context, in *pb.ConfigCodeQueryReq) (*pb.ConfigDataResp, error) {
	l := sysservicelogic.NewConfigDataLogic(ctx, s.svcCtx)
	return l.ConfigData(in)
}

func (s *SysServiceServer) ConfigUpdate(ctx context.Context, in *pb.ConfigUpdateReq) (*pb.Ack, error) {
	l := sysservicelogic.NewConfigUpdateLogic(ctx, s.svcCtx)
	return l.ConfigUpdate(in)
}

func (s *SysServiceServer) ConfigDetail(ctx context.Context, in *pb.IdReq) (*pb.Config, error) {
	l := sysservicelogic.NewConfigDetailLogic(ctx, s.svcCtx)
	return l.ConfigDetail(in)
}

func (s *SysServiceServer) ConfigDelete(ctx context.Context, in *pb.IdReq) (*pb.Ack, error) {
	l := sysservicelogic.NewConfigDeleteLogic(ctx, s.svcCtx)
	return l.ConfigDelete(in)
}

func (s *SysServiceServer) LoginLogCreate(ctx context.Context, in *pb.LoginLogReq) (*pb.Ack, error) {
	l := sysservicelogic.NewLoginLogCreateLogic(ctx, s.svcCtx)
	return l.LoginLogCreate(in)
}

func (s *SysServiceServer) LoginLogPage(ctx context.Context, in *pb.LoginLogPageReq) (*pb.LoginLogPageResp, error) {
	l := sysservicelogic.NewLoginLogPageLogic(ctx, s.svcCtx)
	return l.LoginLogPage(in)
}

func (s *SysServiceServer) LoginLogBatchDelete(ctx context.Context, in *pb.BatchIdsReq) (*pb.Ack, error) {
	l := sysservicelogic.NewLoginLogBatchDeleteLogic(ctx, s.svcCtx)
	return l.LoginLogBatchDelete(in)
}

func (s *SysServiceServer) LoginLogClean(ctx context.Context, in *pb.LogCleanReq) (*pb.Ack, error) {
	l := sysservicelogic.NewLoginLogCleanLogic(ctx, s.svcCtx)
	return l.LoginLogClean(in)
}

func (s *SysServiceServer) LoginLogUpdate(ctx context.Context, in *pb.LoginLogUpdateReq) (*pb.Ack, error) {
	l := sysservicelogic.NewLoginLogUpdateLogic(ctx, s.svcCtx)
	return l.LoginLogUpdate(in)
}

func (s *SysServiceServer) LoginLogDetail(ctx context.Context, in *pb.IdReq) (*pb.LoginLog, error) {
	l := sysservicelogic.NewLoginLogDetailLogic(ctx, s.svcCtx)
	return l.LoginLogDetail(in)
}

func (s *SysServiceServer) LoginLogDelete(ctx context.Context, in *pb.IdReq) (*pb.Ack, error) {
	l := sysservicelogic.NewLoginLogDeleteLogic(ctx, s.svcCtx)
	return l.LoginLogDelete(in)
}

func (s *SysServiceServer) OperLogCreate(ctx context.Context, in *pb.OperLogReq) (*pb.Ack, error) {
	l := sysservicelogic.NewOperLogCreateLogic(ctx, s.svcCtx)
	return l.OperLogCreate(in)
}

func (s *SysServiceServer) OperLogPage(ctx context.Context, in *pb.OperLogPageReq) (*pb.OperLogPageResp, error) {
	l := sysservicelogic.NewOperLogPageLogic(ctx, s.svcCtx)
	return l.OperLogPage(in)
}

func (s *SysServiceServer) OperLogBatchDelete(ctx context.Context, in *pb.BatchIdsReq) (*pb.Ack, error) {
	l := sysservicelogic.NewOperLogBatchDeleteLogic(ctx, s.svcCtx)
	return l.OperLogBatchDelete(in)
}

func (s *SysServiceServer) OperLogClean(ctx context.Context, in *pb.LogCleanReq) (*pb.Ack, error) {
	l := sysservicelogic.NewOperLogCleanLogic(ctx, s.svcCtx)
	return l.OperLogClean(in)
}

func (s *SysServiceServer) OperLogUpdate(ctx context.Context, in *pb.OperLogUpdateReq) (*pb.Ack, error) {
	l := sysservicelogic.NewOperLogUpdateLogic(ctx, s.svcCtx)
	return l.OperLogUpdate(in)
}

func (s *SysServiceServer) OperLogDetail(ctx context.Context, in *pb.IdReq) (*pb.OperLog, error) {
	l := sysservicelogic.NewOperLogDetailLogic(ctx, s.svcCtx)
	return l.OperLogDetail(in)
}

func (s *SysServiceServer) OperLogDelete(ctx context.Context, in *pb.IdReq) (*pb.Ack, error) {
	l := sysservicelogic.NewOperLogDeleteLogic(ctx, s.svcCtx)
	return l.OperLogDelete(in)
}
