// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: sys.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_sys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{0}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_sys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{1}
}

func (x *PingResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_sys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdReq) Reset() {
	*x = IdReq{}
	mi := &file_sys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReq) ProtoMessage() {}

func (x *IdReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReq.ProtoReflect.Descriptor instead.
func (*IdReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{3}
}

func (x *IdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BatchIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIdsReq) Reset() {
	*x = BatchIdsReq{}
	mi := &file_sys_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIdsReq) ProtoMessage() {}

func (x *BatchIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIdsReq.ProtoReflect.Descriptor instead.
func (*BatchIdsReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{4}
}

func (x *BatchIdsReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Current       int64                  `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	Pages         int64                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_sys_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{5}
}

func (x *PageInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageInfo) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *PageInfo) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type Dict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	DictType      string                 `protobuf:"bytes,3,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	DictLabel     string                 `protobuf:"bytes,4,opt,name=dict_label,json=dictLabel,proto3" json:"dict_label,omitempty"`
	DictValue     string                 `protobuf:"bytes,5,opt,name=dict_value,json=dictValue,proto3" json:"dict_value,omitempty"`
	Sort          int64                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateBy      int64                  `protobuf:"varint,10,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,11,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	CreatedTime   string                 `protobuf:"bytes,12,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime   string                 `protobuf:"bytes,13,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dict) Reset() {
	*x = Dict{}
	mi := &file_sys_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dict) ProtoMessage() {}

func (x *Dict) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dict.ProtoReflect.Descriptor instead.
func (*Dict) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{6}
}

func (x *Dict) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dict) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Dict) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *Dict) GetDictLabel() string {
	if x != nil {
		return x.DictLabel
	}
	return ""
}

func (x *Dict) GetDictValue() string {
	if x != nil {
		return x.DictValue
	}
	return ""
}

func (x *Dict) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Dict) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Dict) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Dict) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Dict) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *Dict) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *Dict) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *Dict) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

type DictPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	DictType      string                 `protobuf:"bytes,3,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	DictLabel     string                 `protobuf:"bytes,4,opt,name=dict_label,json=dictLabel,proto3" json:"dict_label,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictPageReq) Reset() {
	*x = DictPageReq{}
	mi := &file_sys_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictPageReq) ProtoMessage() {}

func (x *DictPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictPageReq.ProtoReflect.Descriptor instead.
func (*DictPageReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{7}
}

func (x *DictPageReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *DictPageReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DictPageReq) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictPageReq) GetDictLabel() string {
	if x != nil {
		return x.DictLabel
	}
	return ""
}

func (x *DictPageReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DictCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      int64                  `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	DictType      string                 `protobuf:"bytes,2,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	DictLabel     string                 `protobuf:"bytes,3,opt,name=dict_label,json=dictLabel,proto3" json:"dict_label,omitempty"`
	DictValue     string                 `protobuf:"bytes,4,opt,name=dict_value,json=dictValue,proto3" json:"dict_value,omitempty"`
	Sort          int64                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	IsDefault     bool                   `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateBy      int64                  `protobuf:"varint,9,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,10,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictCreateReq) Reset() {
	*x = DictCreateReq{}
	mi := &file_sys_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictCreateReq) ProtoMessage() {}

func (x *DictCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictCreateReq.ProtoReflect.Descriptor instead.
func (*DictCreateReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{8}
}

func (x *DictCreateReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DictCreateReq) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictCreateReq) GetDictLabel() string {
	if x != nil {
		return x.DictLabel
	}
	return ""
}

func (x *DictCreateReq) GetDictValue() string {
	if x != nil {
		return x.DictValue
	}
	return ""
}

func (x *DictCreateReq) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *DictCreateReq) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *DictCreateReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DictCreateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *DictCreateReq) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *DictCreateReq) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

type DictUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	DictType      string                 `protobuf:"bytes,3,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	DictLabel     string                 `protobuf:"bytes,4,opt,name=dict_label,json=dictLabel,proto3" json:"dict_label,omitempty"`
	DictValue     string                 `protobuf:"bytes,5,opt,name=dict_value,json=dictValue,proto3" json:"dict_value,omitempty"`
	Sort          int64                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,10,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictUpdateReq) Reset() {
	*x = DictUpdateReq{}
	mi := &file_sys_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictUpdateReq) ProtoMessage() {}

func (x *DictUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictUpdateReq.ProtoReflect.Descriptor instead.
func (*DictUpdateReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{9}
}

func (x *DictUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DictUpdateReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DictUpdateReq) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictUpdateReq) GetDictLabel() string {
	if x != nil {
		return x.DictLabel
	}
	return ""
}

func (x *DictUpdateReq) GetDictValue() string {
	if x != nil {
		return x.DictValue
	}
	return ""
}

func (x *DictUpdateReq) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *DictUpdateReq) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *DictUpdateReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DictUpdateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *DictUpdateReq) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

type DictTypeQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictType      string                 `protobuf:"bytes,1,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictTypeQueryReq) Reset() {
	*x = DictTypeQueryReq{}
	mi := &file_sys_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictTypeQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictTypeQueryReq) ProtoMessage() {}

func (x *DictTypeQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictTypeQueryReq.ProtoReflect.Descriptor instead.
func (*DictTypeQueryReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{10}
}

func (x *DictTypeQueryReq) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictTypeQueryReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type DictLabelQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictType      string                 `protobuf:"bytes,1,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	DictValue     string                 `protobuf:"bytes,2,opt,name=dict_value,json=dictValue,proto3" json:"dict_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictLabelQueryReq) Reset() {
	*x = DictLabelQueryReq{}
	mi := &file_sys_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictLabelQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictLabelQueryReq) ProtoMessage() {}

func (x *DictLabelQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictLabelQueryReq.ProtoReflect.Descriptor instead.
func (*DictLabelQueryReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{11}
}

func (x *DictLabelQueryReq) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictLabelQueryReq) GetDictValue() string {
	if x != nil {
		return x.DictValue
	}
	return ""
}

type DictLabelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictLabelResp) Reset() {
	*x = DictLabelResp{}
	mi := &file_sys_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictLabelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictLabelResp) ProtoMessage() {}

func (x *DictLabelResp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictLabelResp.ProtoReflect.Descriptor instead.
func (*DictLabelResp) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{12}
}

func (x *DictLabelResp) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type DictPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Dict                `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictPageResp) Reset() {
	*x = DictPageResp{}
	mi := &file_sys_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictPageResp) ProtoMessage() {}

func (x *DictPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictPageResp.ProtoReflect.Descriptor instead.
func (*DictPageResp) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{13}
}

func (x *DictPageResp) GetRecords() []*Dict {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *DictPageResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type DictListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Dict                `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictListResp) Reset() {
	*x = DictListResp{}
	mi := &file_sys_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictListResp) ProtoMessage() {}

func (x *DictListResp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictListResp.ProtoReflect.Descriptor instead.
func (*DictListResp) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{14}
}

func (x *DictListResp) GetRecords() []*Dict {
	if x != nil {
		return x.Records
	}
	return nil
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	DataJson      string                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateBy      int64                  `protobuf:"varint,6,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	CreatedTime   string                 `protobuf:"bytes,7,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,8,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	UpdatedTime   string                 `protobuf:"bytes,9,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_sys_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{15}
}

func (x *Config) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Config) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *Config) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Config) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *Config) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *Config) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *Config) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

type ConfigPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPageReq) Reset() {
	*x = ConfigPageReq{}
	mi := &file_sys_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPageReq) ProtoMessage() {}

func (x *ConfigPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPageReq.ProtoReflect.Descriptor instead.
func (*ConfigPageReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigPageReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ConfigPageReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ConfigPageReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigPageReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ConfigCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	DataJson      string                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateBy      int64                  `protobuf:"varint,5,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,6,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigCreateReq) Reset() {
	*x = ConfigCreateReq{}
	mi := &file_sys_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigCreateReq) ProtoMessage() {}

func (x *ConfigCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigCreateReq.ProtoReflect.Descriptor instead.
func (*ConfigCreateReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{17}
}

func (x *ConfigCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigCreateReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ConfigCreateReq) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *ConfigCreateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ConfigCreateReq) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *ConfigCreateReq) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

type ConfigUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	DataJson      string                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,6,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdateReq) Reset() {
	*x = ConfigUpdateReq{}
	mi := &file_sys_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdateReq) ProtoMessage() {}

func (x *ConfigUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdateReq.ProtoReflect.Descriptor instead.
func (*ConfigUpdateReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{18}
}

func (x *ConfigUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigUpdateReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ConfigUpdateReq) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *ConfigUpdateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ConfigUpdateReq) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

type ConfigCodeQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigCodeQueryReq) Reset() {
	*x = ConfigCodeQueryReq{}
	mi := &file_sys_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigCodeQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigCodeQueryReq) ProtoMessage() {}

func (x *ConfigCodeQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigCodeQueryReq.ProtoReflect.Descriptor instead.
func (*ConfigCodeQueryReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{19}
}

func (x *ConfigCodeQueryReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ConfigDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	DataJson      string                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigDataResp) Reset() {
	*x = ConfigDataResp{}
	mi := &file_sys_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDataResp) ProtoMessage() {}

func (x *ConfigDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDataResp.ProtoReflect.Descriptor instead.
func (*ConfigDataResp) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{20}
}

func (x *ConfigDataResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ConfigDataResp) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type ConfigPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Config              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPageResp) Reset() {
	*x = ConfigPageResp{}
	mi := &file_sys_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPageResp) ProtoMessage() {}

func (x *ConfigPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPageResp.ProtoReflect.Descriptor instead.
func (*ConfigPageResp) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{21}
}

func (x *ConfigPageResp) GetRecords() []*Config {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ConfigPageResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type ConfigListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Config              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigListResp) Reset() {
	*x = ConfigListResp{}
	mi := &file_sys_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigListResp) ProtoMessage() {}

func (x *ConfigListResp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigListResp.ProtoReflect.Descriptor instead.
func (*ConfigListResp) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{22}
}

func (x *ConfigListResp) GetRecords() []*Config {
	if x != nil {
		return x.Records
	}
	return nil
}

type LoginLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Ipaddr        string                 `protobuf:"bytes,3,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	LoginLocation string                 `protobuf:"bytes,4,opt,name=login_location,json=loginLocation,proto3" json:"login_location,omitempty"`
	Browser       string                 `protobuf:"bytes,5,opt,name=browser,proto3" json:"browser,omitempty"`
	Os            string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	LoginTime     string                 `protobuf:"bytes,9,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`
	ClientId      string                 `protobuf:"bytes,10,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLog) Reset() {
	*x = LoginLog{}
	mi := &file_sys_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLog) ProtoMessage() {}

func (x *LoginLog) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLog.ProtoReflect.Descriptor instead.
func (*LoginLog) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{23}
}

func (x *LoginLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginLog) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginLog) GetIpaddr() string {
	if x != nil {
		return x.Ipaddr
	}
	return ""
}

func (x *LoginLog) GetLoginLocation() string {
	if x != nil {
		return x.LoginLocation
	}
	return ""
}

func (x *LoginLog) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *LoginLog) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *LoginLog) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LoginLog) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginLog) GetLoginTime() string {
	if x != nil {
		return x.LoginTime
	}
	return ""
}

func (x *LoginLog) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type LoginLogPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Ipaddr        string                 `protobuf:"bytes,4,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	StartTime     string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLogPageReq) Reset() {
	*x = LoginLogPageReq{}
	mi := &file_sys_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLogPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLogPageReq) ProtoMessage() {}

func (x *LoginLogPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLogPageReq.ProtoReflect.Descriptor instead.
func (*LoginLogPageReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{24}
}

func (x *LoginLogPageReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *LoginLogPageReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *LoginLogPageReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginLogPageReq) GetIpaddr() string {
	if x != nil {
		return x.Ipaddr
	}
	return ""
}

func (x *LoginLogPageReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LoginLogPageReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *LoginLogPageReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type LoginLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Ipaddr        string                 `protobuf:"bytes,2,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	LoginLocation string                 `protobuf:"bytes,3,opt,name=login_location,json=loginLocation,proto3" json:"login_location,omitempty"`
	Browser       string                 `protobuf:"bytes,4,opt,name=browser,proto3" json:"browser,omitempty"`
	Os            string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
	ClientId      string                 `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLogReq) Reset() {
	*x = LoginLogReq{}
	mi := &file_sys_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLogReq) ProtoMessage() {}

func (x *LoginLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLogReq.ProtoReflect.Descriptor instead.
func (*LoginLogReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{25}
}

func (x *LoginLogReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginLogReq) GetIpaddr() string {
	if x != nil {
		return x.Ipaddr
	}
	return ""
}

func (x *LoginLogReq) GetLoginLocation() string {
	if x != nil {
		return x.LoginLocation
	}
	return ""
}

func (x *LoginLogReq) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *LoginLogReq) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *LoginLogReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LoginLogReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginLogReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type LoginLogUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Ipaddr        string                 `protobuf:"bytes,3,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	LoginLocation string                 `protobuf:"bytes,4,opt,name=login_location,json=loginLocation,proto3" json:"login_location,omitempty"`
	Browser       string                 `protobuf:"bytes,5,opt,name=browser,proto3" json:"browser,omitempty"`
	Os            string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	ClientId      string                 `protobuf:"bytes,9,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLogUpdateReq) Reset() {
	*x = LoginLogUpdateReq{}
	mi := &file_sys_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLogUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLogUpdateReq) ProtoMessage() {}

func (x *LoginLogUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLogUpdateReq.ProtoReflect.Descriptor instead.
func (*LoginLogUpdateReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{26}
}

func (x *LoginLogUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginLogUpdateReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginLogUpdateReq) GetIpaddr() string {
	if x != nil {
		return x.Ipaddr
	}
	return ""
}

func (x *LoginLogUpdateReq) GetLoginLocation() string {
	if x != nil {
		return x.LoginLocation
	}
	return ""
}

func (x *LoginLogUpdateReq) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *LoginLogUpdateReq) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *LoginLogUpdateReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LoginLogUpdateReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginLogUpdateReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type LogCleanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int64                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogCleanReq) Reset() {
	*x = LogCleanReq{}
	mi := &file_sys_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogCleanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCleanReq) ProtoMessage() {}

func (x *LogCleanReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCleanReq.ProtoReflect.Descriptor instead.
func (*LogCleanReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{27}
}

func (x *LogCleanReq) GetDays() int64 {
	if x != nil {
		return x.Days
	}
	return 0
}

type LoginLogPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*LoginLog            `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLogPageResp) Reset() {
	*x = LoginLogPageResp{}
	mi := &file_sys_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLogPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLogPageResp) ProtoMessage() {}

func (x *LoginLogPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLogPageResp.ProtoReflect.Descriptor instead.
func (*LoginLogPageResp) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{28}
}

func (x *LoginLogPageResp) GetRecords() []*LoginLog {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *LoginLogPageResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type OperLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	BusinessType  string                 `protobuf:"bytes,3,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	RequestMethod string                 `protobuf:"bytes,5,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	DeviceType    string                 `protobuf:"bytes,6,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	OperName      string                 `protobuf:"bytes,7,opt,name=oper_name,json=operName,proto3" json:"oper_name,omitempty"`
	OperUrl       string                 `protobuf:"bytes,8,opt,name=oper_url,json=operUrl,proto3" json:"oper_url,omitempty"`
	OperIp        string                 `protobuf:"bytes,9,opt,name=oper_ip,json=operIp,proto3" json:"oper_ip,omitempty"`
	OperLocation  string                 `protobuf:"bytes,10,opt,name=oper_location,json=operLocation,proto3" json:"oper_location,omitempty"`
	OperParam     string                 `protobuf:"bytes,11,opt,name=oper_param,json=operParam,proto3" json:"oper_param,omitempty"`
	JsonResult    string                 `protobuf:"bytes,12,opt,name=json_result,json=jsonResult,proto3" json:"json_result,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,14,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	OperTime      string                 `protobuf:"bytes,15,opt,name=oper_time,json=operTime,proto3" json:"oper_time,omitempty"`
	CostTime      int64                  `protobuf:"varint,16,opt,name=cost_time,json=costTime,proto3" json:"cost_time,omitempty"`
	UserAgent     string                 `protobuf:"bytes,17,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperLog) Reset() {
	*x = OperLog{}
	mi := &file_sys_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperLog) ProtoMessage() {}

func (x *OperLog) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperLog.ProtoReflect.Descriptor instead.
func (*OperLog) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{29}
}

func (x *OperLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperLog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OperLog) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *OperLog) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OperLog) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *OperLog) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *OperLog) GetOperName() string {
	if x != nil {
		return x.OperName
	}
	return ""
}

func (x *OperLog) GetOperUrl() string {
	if x != nil {
		return x.OperUrl
	}
	return ""
}

func (x *OperLog) GetOperIp() string {
	if x != nil {
		return x.OperIp
	}
	return ""
}

func (x *OperLog) GetOperLocation() string {
	if x != nil {
		return x.OperLocation
	}
	return ""
}

func (x *OperLog) GetOperParam() string {
	if x != nil {
		return x.OperParam
	}
	return ""
}

func (x *OperLog) GetJsonResult() string {
	if x != nil {
		return x.JsonResult
	}
	return ""
}

func (x *OperLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperLog) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *OperLog) GetOperTime() string {
	if x != nil {
		return x.OperTime
	}
	return ""
}

func (x *OperLog) GetCostTime() int64 {
	if x != nil {
		return x.CostTime
	}
	return 0
}

func (x *OperLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type OperLogPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OperName      string                 `protobuf:"bytes,4,opt,name=oper_name,json=operName,proto3" json:"oper_name,omitempty"`
	BusinessType  string                 `protobuf:"bytes,5,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	StartTime     string                 `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperLogPageReq) Reset() {
	*x = OperLogPageReq{}
	mi := &file_sys_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperLogPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperLogPageReq) ProtoMessage() {}

func (x *OperLogPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperLogPageReq.ProtoReflect.Descriptor instead.
func (*OperLogPageReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{30}
}

func (x *OperLogPageReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *OperLogPageReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OperLogPageReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OperLogPageReq) GetOperName() string {
	if x != nil {
		return x.OperName
	}
	return ""
}

func (x *OperLogPageReq) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *OperLogPageReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperLogPageReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *OperLogPageReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type OperLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	BusinessType  string                 `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	RequestMethod string                 `protobuf:"bytes,4,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	DeviceType    string                 `protobuf:"bytes,5,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	OperName      string                 `protobuf:"bytes,6,opt,name=oper_name,json=operName,proto3" json:"oper_name,omitempty"`
	OperUrl       string                 `protobuf:"bytes,7,opt,name=oper_url,json=operUrl,proto3" json:"oper_url,omitempty"`
	OperIp        string                 `protobuf:"bytes,8,opt,name=oper_ip,json=operIp,proto3" json:"oper_ip,omitempty"`
	OperLocation  string                 `protobuf:"bytes,9,opt,name=oper_location,json=operLocation,proto3" json:"oper_location,omitempty"`
	OperParam     string                 `protobuf:"bytes,10,opt,name=oper_param,json=operParam,proto3" json:"oper_param,omitempty"`
	JsonResult    string                 `protobuf:"bytes,11,opt,name=json_result,json=jsonResult,proto3" json:"json_result,omitempty"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,13,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	CostTime      int64                  `protobuf:"varint,14,opt,name=cost_time,json=costTime,proto3" json:"cost_time,omitempty"`
	UserAgent     string                 `protobuf:"bytes,15,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperLogReq) Reset() {
	*x = OperLogReq{}
	mi := &file_sys_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperLogReq) ProtoMessage() {}

func (x *OperLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperLogReq.ProtoReflect.Descriptor instead.
func (*OperLogReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{31}
}

func (x *OperLogReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OperLogReq) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *OperLogReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OperLogReq) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *OperLogReq) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *OperLogReq) GetOperName() string {
	if x != nil {
		return x.OperName
	}
	return ""
}

func (x *OperLogReq) GetOperUrl() string {
	if x != nil {
		return x.OperUrl
	}
	return ""
}

func (x *OperLogReq) GetOperIp() string {
	if x != nil {
		return x.OperIp
	}
	return ""
}

func (x *OperLogReq) GetOperLocation() string {
	if x != nil {
		return x.OperLocation
	}
	return ""
}

func (x *OperLogReq) GetOperParam() string {
	if x != nil {
		return x.OperParam
	}
	return ""
}

func (x *OperLogReq) GetJsonResult() string {
	if x != nil {
		return x.JsonResult
	}
	return ""
}

func (x *OperLogReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperLogReq) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *OperLogReq) GetCostTime() int64 {
	if x != nil {
		return x.CostTime
	}
	return 0
}

func (x *OperLogReq) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type OperLogUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	BusinessType  string                 `protobuf:"bytes,3,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	RequestMethod string                 `protobuf:"bytes,5,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	DeviceType    string                 `protobuf:"bytes,6,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	OperName      string                 `protobuf:"bytes,7,opt,name=oper_name,json=operName,proto3" json:"oper_name,omitempty"`
	OperUrl       string                 `protobuf:"bytes,8,opt,name=oper_url,json=operUrl,proto3" json:"oper_url,omitempty"`
	OperIp        string                 `protobuf:"bytes,9,opt,name=oper_ip,json=operIp,proto3" json:"oper_ip,omitempty"`
	OperLocation  string                 `protobuf:"bytes,10,opt,name=oper_location,json=operLocation,proto3" json:"oper_location,omitempty"`
	OperParam     string                 `protobuf:"bytes,11,opt,name=oper_param,json=operParam,proto3" json:"oper_param,omitempty"`
	JsonResult    string                 `protobuf:"bytes,12,opt,name=json_result,json=jsonResult,proto3" json:"json_result,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,14,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	CostTime      int64                  `protobuf:"varint,15,opt,name=cost_time,json=costTime,proto3" json:"cost_time,omitempty"`
	UserAgent     string                 `protobuf:"bytes,16,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperLogUpdateReq) Reset() {
	*x = OperLogUpdateReq{}
	mi := &file_sys_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperLogUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperLogUpdateReq) ProtoMessage() {}

func (x *OperLogUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperLogUpdateReq.ProtoReflect.Descriptor instead.
func (*OperLogUpdateReq) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{32}
}

func (x *OperLogUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperLogUpdateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OperLogUpdateReq) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *OperLogUpdateReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OperLogUpdateReq) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *OperLogUpdateReq) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *OperLogUpdateReq) GetOperName() string {
	if x != nil {
		return x.OperName
	}
	return ""
}

func (x *OperLogUpdateReq) GetOperUrl() string {
	if x != nil {
		return x.OperUrl
	}
	return ""
}

func (x *OperLogUpdateReq) GetOperIp() string {
	if x != nil {
		return x.OperIp
	}
	return ""
}

func (x *OperLogUpdateReq) GetOperLocation() string {
	if x != nil {
		return x.OperLocation
	}
	return ""
}

func (x *OperLogUpdateReq) GetOperParam() string {
	if x != nil {
		return x.OperParam
	}
	return ""
}

func (x *OperLogUpdateReq) GetJsonResult() string {
	if x != nil {
		return x.JsonResult
	}
	return ""
}

func (x *OperLogUpdateReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperLogUpdateReq) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *OperLogUpdateReq) GetCostTime() int64 {
	if x != nil {
		return x.CostTime
	}
	return 0
}

func (x *OperLogUpdateReq) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type OperLogPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*OperLog             `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperLogPageResp) Reset() {
	*x = OperLogPageResp{}
	mi := &file_sys_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperLogPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperLogPageResp) ProtoMessage() {}

func (x *OperLogPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperLogPageResp.ProtoReflect.Descriptor instead.
func (*OperLogPageResp) Descriptor() ([]byte, []int) {
	return file_sys_proto_rawDescGZIP(), []int{33}
}

func (x *OperLogPageResp) GetRecords() []*OperLog {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *OperLogPageResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_sys_proto protoreflect.FileDescriptor

const file_sys_proto_rawDesc = "" +
	"\n" +
	"\tsys.proto\x12\x02pb\"\t\n" +
	"\aPingReq\"$\n" +
	"\bPingResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x17\n" +
	"\x03Ack\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x17\n" +
	"\x05IdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1f\n" +
	"\vBatchIdsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"d\n" +
	"\bPageInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\x03R\acurrent\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x03R\x05pages\"\xf1\x02\n" +
	"\x04Dict\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x1b\n" +
	"\tdict_type\x18\x03 \x01(\tR\bdictType\x12\x1d\n" +
	"\n" +
	"dict_label\x18\x04 \x01(\tR\tdictLabel\x12\x1d\n" +
	"\n" +
	"dict_value\x18\x05 \x01(\tR\tdictValue\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x03R\x04sort\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x1b\n" +
	"\tcreate_by\x18\n" +
	" \x01(\x03R\bcreateBy\x12\x1b\n" +
	"\tupdate_by\x18\v \x01(\x03R\bupdateBy\x12!\n" +
	"\fcreated_time\x18\f \x01(\tR\vcreatedTime\x12!\n" +
	"\fupdated_time\x18\r \x01(\tR\vupdatedTime\"\x99\x01\n" +
	"\vDictPageReq\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1b\n" +
	"\tdict_type\x18\x03 \x01(\tR\bdictType\x12\x1d\n" +
	"\n" +
	"dict_label\x18\x04 \x01(\tR\tdictLabel\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"\xa4\x02\n" +
	"\rDictCreateReq\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\x03R\bparentId\x12\x1b\n" +
	"\tdict_type\x18\x02 \x01(\tR\bdictType\x12\x1d\n" +
	"\n" +
	"dict_label\x18\x03 \x01(\tR\tdictLabel\x12\x1d\n" +
	"\n" +
	"dict_value\x18\x04 \x01(\tR\tdictValue\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x03R\x04sort\x12\x1d\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bR\tisDefault\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\x12\x1b\n" +
	"\tcreate_by\x18\t \x01(\x03R\bcreateBy\x12\x1b\n" +
	"\tupdate_by\x18\n" +
	" \x01(\x03R\bupdateBy\"\x97\x02\n" +
	"\rDictUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x1b\n" +
	"\tdict_type\x18\x03 \x01(\tR\bdictType\x12\x1d\n" +
	"\n" +
	"dict_label\x18\x04 \x01(\tR\tdictLabel\x12\x1d\n" +
	"\n" +
	"dict_value\x18\x05 \x01(\tR\tdictValue\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x03R\x04sort\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x1b\n" +
	"\tupdate_by\x18\n" +
	" \x01(\x03R\bupdateBy\"L\n" +
	"\x10DictTypeQueryReq\x12\x1b\n" +
	"\tdict_type\x18\x01 \x01(\tR\bdictType\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\"O\n" +
	"\x11DictLabelQueryReq\x12\x1b\n" +
	"\tdict_type\x18\x01 \x01(\tR\bdictType\x12\x1d\n" +
	"\n" +
	"dict_value\x18\x02 \x01(\tR\tdictValue\"%\n" +
	"\rDictLabelResp\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"T\n" +
	"\fDictPageResp\x12\"\n" +
	"\arecords\x18\x01 \x03(\v2\b.pb.DictR\arecords\x12 \n" +
	"\x04page\x18\x02 \x01(\v2\f.pb.PageInfoR\x04page\"2\n" +
	"\fDictListResp\x12\"\n" +
	"\arecords\x18\x01 \x03(\v2\b.pb.DictR\arecords\"\xf5\x01\n" +
	"\x06Config\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\tR\bdataJson\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x1b\n" +
	"\tcreate_by\x18\x06 \x01(\x03R\bcreateBy\x12!\n" +
	"\fcreated_time\x18\a \x01(\tR\vcreatedTime\x12\x1b\n" +
	"\tupdate_by\x18\b \x01(\x03R\bupdateBy\x12!\n" +
	"\fupdated_time\x18\t \x01(\tR\vupdatedTime\"o\n" +
	"\rConfigPageReq\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"\xa8\x01\n" +
	"\x0fConfigCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\tR\bdataJson\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x1b\n" +
	"\tcreate_by\x18\x05 \x01(\x03R\bcreateBy\x12\x1b\n" +
	"\tupdate_by\x18\x06 \x01(\x03R\bupdateBy\"\x9b\x01\n" +
	"\x0fConfigUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\tR\bdataJson\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x1b\n" +
	"\tupdate_by\x18\x06 \x01(\x03R\bupdateBy\"(\n" +
	"\x12ConfigCodeQueryReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"A\n" +
	"\x0eConfigDataResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\tR\bdataJson\"X\n" +
	"\x0eConfigPageResp\x12$\n" +
	"\arecords\x18\x01 \x03(\v2\n" +
	".pb.ConfigR\arecords\x12 \n" +
	"\x04page\x18\x02 \x01(\v2\f.pb.PageInfoR\x04page\"6\n" +
	"\x0eConfigListResp\x12$\n" +
	"\arecords\x18\x01 \x03(\v2\n" +
	".pb.ConfigR\arecords\"\x86\x02\n" +
	"\bLoginLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x16\n" +
	"\x06ipaddr\x18\x03 \x01(\tR\x06ipaddr\x12%\n" +
	"\x0elogin_location\x18\x04 \x01(\tR\rloginLocation\x12\x18\n" +
	"\abrowser\x18\x05 \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\b \x01(\tR\x03msg\x12\x1d\n" +
	"\n" +
	"login_time\x18\t \x01(\tR\tloginTime\x12\x1b\n" +
	"\tclient_id\x18\n" +
	" \x01(\tR\bclientId\"\xd0\x01\n" +
	"\x0fLoginLogPageReq\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x16\n" +
	"\x06ipaddr\x18\x04 \x01(\tR\x06ipaddr\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\"\xda\x01\n" +
	"\vLoginLogReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x16\n" +
	"\x06ipaddr\x18\x02 \x01(\tR\x06ipaddr\x12%\n" +
	"\x0elogin_location\x18\x03 \x01(\tR\rloginLocation\x12\x18\n" +
	"\abrowser\x18\x04 \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\a \x01(\tR\x03msg\x12\x1b\n" +
	"\tclient_id\x18\b \x01(\tR\bclientId\"\xf0\x01\n" +
	"\x11LoginLogUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x16\n" +
	"\x06ipaddr\x18\x03 \x01(\tR\x06ipaddr\x12%\n" +
	"\x0elogin_location\x18\x04 \x01(\tR\rloginLocation\x12\x18\n" +
	"\abrowser\x18\x05 \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x10\n" +
	"\x03msg\x18\b \x01(\tR\x03msg\x12\x1b\n" +
	"\tclient_id\x18\t \x01(\tR\bclientId\"!\n" +
	"\vLogCleanReq\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x03R\x04days\"\\\n" +
	"\x10LoginLogPageResp\x12&\n" +
	"\arecords\x18\x01 \x03(\v2\f.pb.LoginLogR\arecords\x12 \n" +
	"\x04page\x18\x02 \x01(\v2\f.pb.PageInfoR\x04page\"\xf8\x03\n" +
	"\aOperLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rbusiness_type\x18\x03 \x01(\tR\fbusinessType\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12%\n" +
	"\x0erequest_method\x18\x05 \x01(\tR\rrequestMethod\x12\x1f\n" +
	"\vdevice_type\x18\x06 \x01(\tR\n" +
	"deviceType\x12\x1b\n" +
	"\toper_name\x18\a \x01(\tR\boperName\x12\x19\n" +
	"\boper_url\x18\b \x01(\tR\aoperUrl\x12\x17\n" +
	"\aoper_ip\x18\t \x01(\tR\x06operIp\x12#\n" +
	"\roper_location\x18\n" +
	" \x01(\tR\foperLocation\x12\x1d\n" +
	"\n" +
	"oper_param\x18\v \x01(\tR\toperParam\x12\x1f\n" +
	"\vjson_result\x18\f \x01(\tR\n" +
	"jsonResult\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x0e \x01(\tR\berrorMsg\x12\x1b\n" +
	"\toper_time\x18\x0f \x01(\tR\boperTime\x12\x1b\n" +
	"\tcost_time\x18\x10 \x01(\x03R\bcostTime\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x11 \x01(\tR\tuserAgent\"\xf2\x01\n" +
	"\x0eOperLogPageReq\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\toper_name\x18\x04 \x01(\tR\boperName\x12#\n" +
	"\rbusiness_type\x18\x05 \x01(\tR\fbusinessType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\tR\aendTime\"\xce\x03\n" +
	"\n" +
	"OperLogReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12#\n" +
	"\rbusiness_type\x18\x02 \x01(\tR\fbusinessType\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12%\n" +
	"\x0erequest_method\x18\x04 \x01(\tR\rrequestMethod\x12\x1f\n" +
	"\vdevice_type\x18\x05 \x01(\tR\n" +
	"deviceType\x12\x1b\n" +
	"\toper_name\x18\x06 \x01(\tR\boperName\x12\x19\n" +
	"\boper_url\x18\a \x01(\tR\aoperUrl\x12\x17\n" +
	"\aoper_ip\x18\b \x01(\tR\x06operIp\x12#\n" +
	"\roper_location\x18\t \x01(\tR\foperLocation\x12\x1d\n" +
	"\n" +
	"oper_param\x18\n" +
	" \x01(\tR\toperParam\x12\x1f\n" +
	"\vjson_result\x18\v \x01(\tR\n" +
	"jsonResult\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\r \x01(\tR\berrorMsg\x12\x1b\n" +
	"\tcost_time\x18\x0e \x01(\x03R\bcostTime\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x0f \x01(\tR\tuserAgent\"\xe4\x03\n" +
	"\x10OperLogUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rbusiness_type\x18\x03 \x01(\tR\fbusinessType\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12%\n" +
	"\x0erequest_method\x18\x05 \x01(\tR\rrequestMethod\x12\x1f\n" +
	"\vdevice_type\x18\x06 \x01(\tR\n" +
	"deviceType\x12\x1b\n" +
	"\toper_name\x18\a \x01(\tR\boperName\x12\x19\n" +
	"\boper_url\x18\b \x01(\tR\aoperUrl\x12\x17\n" +
	"\aoper_ip\x18\t \x01(\tR\x06operIp\x12#\n" +
	"\roper_location\x18\n" +
	" \x01(\tR\foperLocation\x12\x1d\n" +
	"\n" +
	"oper_param\x18\v \x01(\tR\toperParam\x12\x1f\n" +
	"\vjson_result\x18\f \x01(\tR\n" +
	"jsonResult\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x0e \x01(\tR\berrorMsg\x12\x1b\n" +
	"\tcost_time\x18\x0f \x01(\x03R\bcostTime\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x10 \x01(\tR\tuserAgent\"Z\n" +
	"\x0fOperLogPageResp\x12%\n" +
	"\arecords\x18\x01 \x03(\v2\v.pb.OperLogR\arecords\x12 \n" +
	"\x04page\x18\x02 \x01(\v2\f.pb.PageInfoR\x04page2\x8e\v\n" +
	"\n" +
	"SysService\x12!\n" +
	"\x04Ping\x12\v.pb.PingReq\x1a\f.pb.PingResp\x12(\n" +
	"\n" +
	"DictCreate\x12\x11.pb.DictCreateReq\x1a\a.pb.Ack\x12-\n" +
	"\bDictPage\x12\x0f.pb.DictPageReq\x1a\x10.pb.DictPageResp\x12+\n" +
	"\x0fDictBatchDelete\x12\x0f.pb.BatchIdsReq\x1a\a.pb.Ack\x122\n" +
	"\bDictType\x12\x14.pb.DictTypeQueryReq\x1a\x10.pb.DictListResp\x125\n" +
	"\tDictLabel\x12\x15.pb.DictLabelQueryReq\x1a\x11.pb.DictLabelResp\x12(\n" +
	"\n" +
	"DictUpdate\x12\x11.pb.DictUpdateReq\x1a\a.pb.Ack\x12!\n" +
	"\n" +
	"DictDetail\x12\t.pb.IdReq\x1a\b.pb.Dict\x12 \n" +
	"\n" +
	"DictDelete\x12\t.pb.IdReq\x1a\a.pb.Ack\x12,\n" +
	"\fConfigCreate\x12\x13.pb.ConfigCreateReq\x1a\a.pb.Ack\x123\n" +
	"\n" +
	"ConfigPage\x12\x11.pb.ConfigPageReq\x1a\x12.pb.ConfigPageResp\x12-\n" +
	"\x11ConfigBatchDelete\x12\x0f.pb.BatchIdsReq\x1a\a.pb.Ack\x128\n" +
	"\n" +
	"ConfigCode\x12\x16.pb.ConfigCodeQueryReq\x1a\x12.pb.ConfigListResp\x128\n" +
	"\n" +
	"ConfigData\x12\x16.pb.ConfigCodeQueryReq\x1a\x12.pb.ConfigDataResp\x12,\n" +
	"\fConfigUpdate\x12\x13.pb.ConfigUpdateReq\x1a\a.pb.Ack\x12%\n" +
	"\fConfigDetail\x12\t.pb.IdReq\x1a\n" +
	".pb.Config\x12\"\n" +
	"\fConfigDelete\x12\t.pb.IdReq\x1a\a.pb.Ack\x12*\n" +
	"\x0eLoginLogCreate\x12\x0f.pb.LoginLogReq\x1a\a.pb.Ack\x129\n" +
	"\fLoginLogPage\x12\x13.pb.LoginLogPageReq\x1a\x14.pb.LoginLogPageResp\x12/\n" +
	"\x13LoginLogBatchDelete\x12\x0f.pb.BatchIdsReq\x1a\a.pb.Ack\x12)\n" +
	"\rLoginLogClean\x12\x0f.pb.LogCleanReq\x1a\a.pb.Ack\x120\n" +
	"\x0eLoginLogUpdate\x12\x15.pb.LoginLogUpdateReq\x1a\a.pb.Ack\x12)\n" +
	"\x0eLoginLogDetail\x12\t.pb.IdReq\x1a\f.pb.LoginLog\x12$\n" +
	"\x0eLoginLogDelete\x12\t.pb.IdReq\x1a\a.pb.Ack\x12(\n" +
	"\rOperLogCreate\x12\x0e.pb.OperLogReq\x1a\a.pb.Ack\x126\n" +
	"\vOperLogPage\x12\x12.pb.OperLogPageReq\x1a\x13.pb.OperLogPageResp\x12.\n" +
	"\x12OperLogBatchDelete\x12\x0f.pb.BatchIdsReq\x1a\a.pb.Ack\x12(\n" +
	"\fOperLogClean\x12\x0f.pb.LogCleanReq\x1a\a.pb.Ack\x12.\n" +
	"\rOperLogUpdate\x12\x14.pb.OperLogUpdateReq\x1a\a.pb.Ack\x12'\n" +
	"\rOperLogDetail\x12\t.pb.IdReq\x1a\v.pb.OperLog\x12#\n" +
	"\rOperLogDelete\x12\t.pb.IdReq\x1a\a.pb.AckB;Z9github.com/gcc798/microservice-kit/application/sys-rpc/pbb\x06proto3"

var (
	file_sys_proto_rawDescOnce sync.Once
	file_sys_proto_rawDescData []byte
)

func file_sys_proto_rawDescGZIP() []byte {
	file_sys_proto_rawDescOnce.Do(func() {
		file_sys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_proto_rawDesc), len(file_sys_proto_rawDesc)))
	})
	return file_sys_proto_rawDescData
}

var file_sys_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_sys_proto_goTypes = []any{
	(*PingReq)(nil),            // 0: pb.PingReq
	(*PingResp)(nil),           // 1: pb.PingResp
	(*Ack)(nil),                // 2: pb.Ack
	(*IdReq)(nil),              // 3: pb.IdReq
	(*BatchIdsReq)(nil),        // 4: pb.BatchIdsReq
	(*PageInfo)(nil),           // 5: pb.PageInfo
	(*Dict)(nil),               // 6: pb.Dict
	(*DictPageReq)(nil),        // 7: pb.DictPageReq
	(*DictCreateReq)(nil),      // 8: pb.DictCreateReq
	(*DictUpdateReq)(nil),      // 9: pb.DictUpdateReq
	(*DictTypeQueryReq)(nil),   // 10: pb.DictTypeQueryReq
	(*DictLabelQueryReq)(nil),  // 11: pb.DictLabelQueryReq
	(*DictLabelResp)(nil),      // 12: pb.DictLabelResp
	(*DictPageResp)(nil),       // 13: pb.DictPageResp
	(*DictListResp)(nil),       // 14: pb.DictListResp
	(*Config)(nil),             // 15: pb.Config
	(*ConfigPageReq)(nil),      // 16: pb.ConfigPageReq
	(*ConfigCreateReq)(nil),    // 17: pb.ConfigCreateReq
	(*ConfigUpdateReq)(nil),    // 18: pb.ConfigUpdateReq
	(*ConfigCodeQueryReq)(nil), // 19: pb.ConfigCodeQueryReq
	(*ConfigDataResp)(nil),     // 20: pb.ConfigDataResp
	(*ConfigPageResp)(nil),     // 21: pb.ConfigPageResp
	(*ConfigListResp)(nil),     // 22: pb.ConfigListResp
	(*LoginLog)(nil),           // 23: pb.LoginLog
	(*LoginLogPageReq)(nil),    // 24: pb.LoginLogPageReq
	(*LoginLogReq)(nil),        // 25: pb.LoginLogReq
	(*LoginLogUpdateReq)(nil),  // 26: pb.LoginLogUpdateReq
	(*LogCleanReq)(nil),        // 27: pb.LogCleanReq
	(*LoginLogPageResp)(nil),   // 28: pb.LoginLogPageResp
	(*OperLog)(nil),            // 29: pb.OperLog
	(*OperLogPageReq)(nil),     // 30: pb.OperLogPageReq
	(*OperLogReq)(nil),         // 31: pb.OperLogReq
	(*OperLogUpdateReq)(nil),   // 32: pb.OperLogUpdateReq
	(*OperLogPageResp)(nil),    // 33: pb.OperLogPageResp
}
var file_sys_proto_depIdxs = []int32{
	6,  // 0: pb.DictPageResp.records:type_name -> pb.Dict
	5,  // 1: pb.DictPageResp.page:type_name -> pb.PageInfo
	6,  // 2: pb.DictListResp.records:type_name -> pb.Dict
	15, // 3: pb.ConfigPageResp.records:type_name -> pb.Config
	5,  // 4: pb.ConfigPageResp.page:type_name -> pb.PageInfo
	15, // 5: pb.ConfigListResp.records:type_name -> pb.Config
	23, // 6: pb.LoginLogPageResp.records:type_name -> pb.LoginLog
	5,  // 7: pb.LoginLogPageResp.page:type_name -> pb.PageInfo
	29, // 8: pb.OperLogPageResp.records:type_name -> pb.OperLog
	5,  // 9: pb.OperLogPageResp.page:type_name -> pb.PageInfo
	0,  // 10: pb.SysService.Ping:input_type -> pb.PingReq
	8,  // 11: pb.SysService.DictCreate:input_type -> pb.DictCreateReq
	7,  // 12: pb.SysService.DictPage:input_type -> pb.DictPageReq
	4,  // 13: pb.SysService.DictBatchDelete:input_type -> pb.BatchIdsReq
	10, // 14: pb.SysService.DictType:input_type -> pb.DictTypeQueryReq
	11, // 15: pb.SysService.DictLabel:input_type -> pb.DictLabelQueryReq
	9,  // 16: pb.SysService.DictUpdate:input_type -> pb.DictUpdateReq
	3,  // 17: pb.SysService.DictDetail:input_type -> pb.IdReq
	3,  // 18: pb.SysService.DictDelete:input_type -> pb.IdReq
	17, // 19: pb.SysService.ConfigCreate:input_type -> pb.ConfigCreateReq
	16, // 20: pb.SysService.ConfigPage:input_type -> pb.ConfigPageReq
	4,  // 21: pb.SysService.ConfigBatchDelete:input_type -> pb.BatchIdsReq
	19, // 22: pb.SysService.ConfigCode:input_type -> pb.ConfigCodeQueryReq
	19, // 23: pb.SysService.ConfigData:input_type -> pb.ConfigCodeQueryReq
	18, // 24: pb.SysService.ConfigUpdate:input_type -> pb.ConfigUpdateReq
	3,  // 25: pb.SysService.ConfigDetail:input_type -> pb.IdReq
	3,  // 26: pb.SysService.ConfigDelete:input_type -> pb.IdReq
	25, // 27: pb.SysService.LoginLogCreate:input_type -> pb.LoginLogReq
	24, // 28: pb.SysService.LoginLogPage:input_type -> pb.LoginLogPageReq
	4,  // 29: pb.SysService.LoginLogBatchDelete:input_type -> pb.BatchIdsReq
	27, // 30: pb.SysService.LoginLogClean:input_type -> pb.LogCleanReq
	26, // 31: pb.SysService.LoginLogUpdate:input_type -> pb.LoginLogUpdateReq
	3,  // 32: pb.SysService.LoginLogDetail:input_type -> pb.IdReq
	3,  // 33: pb.SysService.LoginLogDelete:input_type -> pb.IdReq
	31, // 34: pb.SysService.OperLogCreate:input_type -> pb.OperLogReq
	30, // 35: pb.SysService.OperLogPage:input_type -> pb.OperLogPageReq
	4,  // 36: pb.SysService.OperLogBatchDelete:input_type -> pb.BatchIdsReq
	27, // 37: pb.SysService.OperLogClean:input_type -> pb.LogCleanReq
	32, // 38: pb.SysService.OperLogUpdate:input_type -> pb.OperLogUpdateReq
	3,  // 39: pb.SysService.OperLogDetail:input_type -> pb.IdReq
	3,  // 40: pb.SysService.OperLogDelete:input_type -> pb.IdReq
	1,  // 41: pb.SysService.Ping:output_type -> pb.PingResp
	2,  // 42: pb.SysService.DictCreate:output_type -> pb.Ack
	13, // 43: pb.SysService.DictPage:output_type -> pb.DictPageResp
	2,  // 44: pb.SysService.DictBatchDelete:output_type -> pb.Ack
	14, // 45: pb.SysService.DictType:output_type -> pb.DictListResp
	12, // 46: pb.SysService.DictLabel:output_type -> pb.DictLabelResp
	2,  // 47: pb.SysService.DictUpdate:output_type -> pb.Ack
	6,  // 48: pb.SysService.DictDetail:output_type -> pb.Dict
	2,  // 49: pb.SysService.DictDelete:output_type -> pb.Ack
	2,  // 50: pb.SysService.ConfigCreate:output_type -> pb.Ack
	21, // 51: pb.SysService.ConfigPage:output_type -> pb.ConfigPageResp
	2,  // 52: pb.SysService.ConfigBatchDelete:output_type -> pb.Ack
	22, // 53: pb.SysService.ConfigCode:output_type -> pb.ConfigListResp
	20, // 54: pb.SysService.ConfigData:output_type -> pb.ConfigDataResp
	2,  // 55: pb.SysService.ConfigUpdate:output_type -> pb.Ack
	15, // 56: pb.SysService.ConfigDetail:output_type -> pb.Config
	2,  // 57: pb.SysService.ConfigDelete:output_type -> pb.Ack
	2,  // 58: pb.SysService.LoginLogCreate:output_type -> pb.Ack
	28, // 59: pb.SysService.LoginLogPage:output_type -> pb.LoginLogPageResp
	2,  // 60: pb.SysService.LoginLogBatchDelete:output_type -> pb.Ack
	2,  // 61: pb.SysService.LoginLogClean:output_type -> pb.Ack
	2,  // 62: pb.SysService.LoginLogUpdate:output_type -> pb.Ack
	23, // 63: pb.SysService.LoginLogDetail:output_type -> pb.LoginLog
	2,  // 64: pb.SysService.LoginLogDelete:output_type -> pb.Ack
	2,  // 65: pb.SysService.OperLogCreate:output_type -> pb.Ack
	33, // 66: pb.SysService.OperLogPage:output_type -> pb.OperLogPageResp
	2,  // 67: pb.SysService.OperLogBatchDelete:output_type -> pb.Ack
	2,  // 68: pb.SysService.OperLogClean:output_type -> pb.Ack
	2,  // 69: pb.SysService.OperLogUpdate:output_type -> pb.Ack
	29, // 70: pb.SysService.OperLogDetail:output_type -> pb.OperLog
	2,  // 71: pb.SysService.OperLogDelete:output_type -> pb.Ack
	41, // [41:72] is the sub-list for method output_type
	10, // [10:41] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sys_proto_init() }
func file_sys_proto_init() {
	if File_sys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_proto_rawDesc), len(file_sys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sys_proto_goTypes,
		DependencyIndexes: file_sys_proto_depIdxs,
		MessageInfos:      file_sys_proto_msgTypes,
	}.Build()
	File_sys_proto = out.File
	file_sys_proto_goTypes = nil
	file_sys_proto_depIdxs = nil
}
