// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: sys.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysService_Ping_FullMethodName                = "/pb.SysService/Ping"
	SysService_DictCreate_FullMethodName          = "/pb.SysService/DictCreate"
	SysService_DictPage_FullMethodName            = "/pb.SysService/DictPage"
	SysService_DictBatchDelete_FullMethodName     = "/pb.SysService/DictBatchDelete"
	SysService_DictType_FullMethodName            = "/pb.SysService/DictType"
	SysService_DictLabel_FullMethodName           = "/pb.SysService/DictLabel"
	SysService_DictUpdate_FullMethodName          = "/pb.SysService/DictUpdate"
	SysService_DictDetail_FullMethodName          = "/pb.SysService/DictDetail"
	SysService_DictDelete_FullMethodName          = "/pb.SysService/DictDelete"
	SysService_ConfigCreate_FullMethodName        = "/pb.SysService/ConfigCreate"
	SysService_ConfigPage_FullMethodName          = "/pb.SysService/ConfigPage"
	SysService_ConfigBatchDelete_FullMethodName   = "/pb.SysService/ConfigBatchDelete"
	SysService_ConfigCode_FullMethodName          = "/pb.SysService/ConfigCode"
	SysService_ConfigData_FullMethodName          = "/pb.SysService/ConfigData"
	SysService_ConfigUpdate_FullMethodName        = "/pb.SysService/ConfigUpdate"
	SysService_ConfigDetail_FullMethodName        = "/pb.SysService/ConfigDetail"
	SysService_ConfigDelete_FullMethodName        = "/pb.SysService/ConfigDelete"
	SysService_LoginLogCreate_FullMethodName      = "/pb.SysService/LoginLogCreate"
	SysService_LoginLogPage_FullMethodName        = "/pb.SysService/LoginLogPage"
	SysService_LoginLogBatchDelete_FullMethodName = "/pb.SysService/LoginLogBatchDelete"
	SysService_LoginLogClean_FullMethodName       = "/pb.SysService/LoginLogClean"
	SysService_LoginLogUpdate_FullMethodName      = "/pb.SysService/LoginLogUpdate"
	SysService_LoginLogDetail_FullMethodName      = "/pb.SysService/LoginLogDetail"
	SysService_LoginLogDelete_FullMethodName      = "/pb.SysService/LoginLogDelete"
	SysService_OperLogCreate_FullMethodName       = "/pb.SysService/OperLogCreate"
	SysService_OperLogPage_FullMethodName         = "/pb.SysService/OperLogPage"
	SysService_OperLogBatchDelete_FullMethodName  = "/pb.SysService/OperLogBatchDelete"
	SysService_OperLogClean_FullMethodName        = "/pb.SysService/OperLogClean"
	SysService_OperLogUpdate_FullMethodName       = "/pb.SysService/OperLogUpdate"
	SysService_OperLogDetail_FullMethodName       = "/pb.SysService/OperLogDetail"
	SysService_OperLogDelete_FullMethodName       = "/pb.SysService/OperLogDelete"
)

// SysServiceClient is the client API for SysService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysServiceClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	DictCreate(ctx context.Context, in *DictCreateReq, opts ...grpc.CallOption) (*Ack, error)
	DictPage(ctx context.Context, in *DictPageReq, opts ...grpc.CallOption) (*DictPageResp, error)
	DictBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
	DictType(ctx context.Context, in *DictTypeQueryReq, opts ...grpc.CallOption) (*DictListResp, error)
	DictLabel(ctx context.Context, in *DictLabelQueryReq, opts ...grpc.CallOption) (*DictLabelResp, error)
	DictUpdate(ctx context.Context, in *DictUpdateReq, opts ...grpc.CallOption) (*Ack, error)
	DictDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Dict, error)
	DictDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
	ConfigCreate(ctx context.Context, in *ConfigCreateReq, opts ...grpc.CallOption) (*Ack, error)
	ConfigPage(ctx context.Context, in *ConfigPageReq, opts ...grpc.CallOption) (*ConfigPageResp, error)
	ConfigBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
	ConfigCode(ctx context.Context, in *ConfigCodeQueryReq, opts ...grpc.CallOption) (*ConfigListResp, error)
	ConfigData(ctx context.Context, in *ConfigCodeQueryReq, opts ...grpc.CallOption) (*ConfigDataResp, error)
	ConfigUpdate(ctx context.Context, in *ConfigUpdateReq, opts ...grpc.CallOption) (*Ack, error)
	ConfigDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Config, error)
	ConfigDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
	LoginLogCreate(ctx context.Context, in *LoginLogReq, opts ...grpc.CallOption) (*Ack, error)
	LoginLogPage(ctx context.Context, in *LoginLogPageReq, opts ...grpc.CallOption) (*LoginLogPageResp, error)
	LoginLogBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
	LoginLogClean(ctx context.Context, in *LogCleanReq, opts ...grpc.CallOption) (*Ack, error)
	LoginLogUpdate(ctx context.Context, in *LoginLogUpdateReq, opts ...grpc.CallOption) (*Ack, error)
	LoginLogDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*LoginLog, error)
	LoginLogDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
	OperLogCreate(ctx context.Context, in *OperLogReq, opts ...grpc.CallOption) (*Ack, error)
	OperLogPage(ctx context.Context, in *OperLogPageReq, opts ...grpc.CallOption) (*OperLogPageResp, error)
	OperLogBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error)
	OperLogClean(ctx context.Context, in *LogCleanReq, opts ...grpc.CallOption) (*Ack, error)
	OperLogUpdate(ctx context.Context, in *OperLogUpdateReq, opts ...grpc.CallOption) (*Ack, error)
	OperLogDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*OperLog, error)
	OperLogDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error)
}

type sysServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysServiceClient(cc grpc.ClientConnInterface) SysServiceClient {
	return &sysServiceClient{cc}
}

func (c *sysServiceClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, SysService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) DictCreate(ctx context.Context, in *DictCreateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_DictCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) DictPage(ctx context.Context, in *DictPageReq, opts ...grpc.CallOption) (*DictPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictPageResp)
	err := c.cc.Invoke(ctx, SysService_DictPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) DictBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_DictBatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) DictType(ctx context.Context, in *DictTypeQueryReq, opts ...grpc.CallOption) (*DictListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictListResp)
	err := c.cc.Invoke(ctx, SysService_DictType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) DictLabel(ctx context.Context, in *DictLabelQueryReq, opts ...grpc.CallOption) (*DictLabelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictLabelResp)
	err := c.cc.Invoke(ctx, SysService_DictLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) DictUpdate(ctx context.Context, in *DictUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_DictUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) DictDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Dict, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dict)
	err := c.cc.Invoke(ctx, SysService_DictDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) DictDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_DictDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) ConfigCreate(ctx context.Context, in *ConfigCreateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_ConfigCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) ConfigPage(ctx context.Context, in *ConfigPageReq, opts ...grpc.CallOption) (*ConfigPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigPageResp)
	err := c.cc.Invoke(ctx, SysService_ConfigPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) ConfigBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_ConfigBatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) ConfigCode(ctx context.Context, in *ConfigCodeQueryReq, opts ...grpc.CallOption) (*ConfigListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigListResp)
	err := c.cc.Invoke(ctx, SysService_ConfigCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) ConfigData(ctx context.Context, in *ConfigCodeQueryReq, opts ...grpc.CallOption) (*ConfigDataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigDataResp)
	err := c.cc.Invoke(ctx, SysService_ConfigData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) ConfigUpdate(ctx context.Context, in *ConfigUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_ConfigUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) ConfigDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Config, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Config)
	err := c.cc.Invoke(ctx, SysService_ConfigDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) ConfigDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_ConfigDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) LoginLogCreate(ctx context.Context, in *LoginLogReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_LoginLogCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) LoginLogPage(ctx context.Context, in *LoginLogPageReq, opts ...grpc.CallOption) (*LoginLogPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginLogPageResp)
	err := c.cc.Invoke(ctx, SysService_LoginLogPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) LoginLogBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_LoginLogBatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) LoginLogClean(ctx context.Context, in *LogCleanReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_LoginLogClean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) LoginLogUpdate(ctx context.Context, in *LoginLogUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_LoginLogUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) LoginLogDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*LoginLog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginLog)
	err := c.cc.Invoke(ctx, SysService_LoginLogDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) LoginLogDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_LoginLogDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) OperLogCreate(ctx context.Context, in *OperLogReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_OperLogCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) OperLogPage(ctx context.Context, in *OperLogPageReq, opts ...grpc.CallOption) (*OperLogPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperLogPageResp)
	err := c.cc.Invoke(ctx, SysService_OperLogPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) OperLogBatchDelete(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_OperLogBatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) OperLogClean(ctx context.Context, in *LogCleanReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_OperLogClean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) OperLogUpdate(ctx context.Context, in *OperLogUpdateReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_OperLogUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) OperLogDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*OperLog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperLog)
	err := c.cc.Invoke(ctx, SysService_OperLogDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysServiceClient) OperLogDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SysService_OperLogDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysServiceServer is the server API for SysService service.
// All implementations must embed UnimplementedSysServiceServer
// for forward compatibility.
type SysServiceServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	DictCreate(context.Context, *DictCreateReq) (*Ack, error)
	DictPage(context.Context, *DictPageReq) (*DictPageResp, error)
	DictBatchDelete(context.Context, *BatchIdsReq) (*Ack, error)
	DictType(context.Context, *DictTypeQueryReq) (*DictListResp, error)
	DictLabel(context.Context, *DictLabelQueryReq) (*DictLabelResp, error)
	DictUpdate(context.Context, *DictUpdateReq) (*Ack, error)
	DictDetail(context.Context, *IdReq) (*Dict, error)
	DictDelete(context.Context, *IdReq) (*Ack, error)
	ConfigCreate(context.Context, *ConfigCreateReq) (*Ack, error)
	ConfigPage(context.Context, *ConfigPageReq) (*ConfigPageResp, error)
	ConfigBatchDelete(context.Context, *BatchIdsReq) (*Ack, error)
	ConfigCode(context.Context, *ConfigCodeQueryReq) (*ConfigListResp, error)
	ConfigData(context.Context, *ConfigCodeQueryReq) (*ConfigDataResp, error)
	ConfigUpdate(context.Context, *ConfigUpdateReq) (*Ack, error)
	ConfigDetail(context.Context, *IdReq) (*Config, error)
	ConfigDelete(context.Context, *IdReq) (*Ack, error)
	LoginLogCreate(context.Context, *LoginLogReq) (*Ack, error)
	LoginLogPage(context.Context, *LoginLogPageReq) (*LoginLogPageResp, error)
	LoginLogBatchDelete(context.Context, *BatchIdsReq) (*Ack, error)
	LoginLogClean(context.Context, *LogCleanReq) (*Ack, error)
	LoginLogUpdate(context.Context, *LoginLogUpdateReq) (*Ack, error)
	LoginLogDetail(context.Context, *IdReq) (*LoginLog, error)
	LoginLogDelete(context.Context, *IdReq) (*Ack, error)
	OperLogCreate(context.Context, *OperLogReq) (*Ack, error)
	OperLogPage(context.Context, *OperLogPageReq) (*OperLogPageResp, error)
	OperLogBatchDelete(context.Context, *BatchIdsReq) (*Ack, error)
	OperLogClean(context.Context, *LogCleanReq) (*Ack, error)
	OperLogUpdate(context.Context, *OperLogUpdateReq) (*Ack, error)
	OperLogDetail(context.Context, *IdReq) (*OperLog, error)
	OperLogDelete(context.Context, *IdReq) (*Ack, error)
	mustEmbedUnimplementedSysServiceServer()
}

// UnimplementedSysServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysServiceServer struct{}

func (UnimplementedSysServiceServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSysServiceServer) DictCreate(context.Context, *DictCreateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method DictCreate not implemented")
}
func (UnimplementedSysServiceServer) DictPage(context.Context, *DictPageReq) (*DictPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DictPage not implemented")
}
func (UnimplementedSysServiceServer) DictBatchDelete(context.Context, *BatchIdsReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method DictBatchDelete not implemented")
}
func (UnimplementedSysServiceServer) DictType(context.Context, *DictTypeQueryReq) (*DictListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DictType not implemented")
}
func (UnimplementedSysServiceServer) DictLabel(context.Context, *DictLabelQueryReq) (*DictLabelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DictLabel not implemented")
}
func (UnimplementedSysServiceServer) DictUpdate(context.Context, *DictUpdateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method DictUpdate not implemented")
}
func (UnimplementedSysServiceServer) DictDetail(context.Context, *IdReq) (*Dict, error) {
	return nil, status.Error(codes.Unimplemented, "method DictDetail not implemented")
}
func (UnimplementedSysServiceServer) DictDelete(context.Context, *IdReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method DictDelete not implemented")
}
func (UnimplementedSysServiceServer) ConfigCreate(context.Context, *ConfigCreateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigCreate not implemented")
}
func (UnimplementedSysServiceServer) ConfigPage(context.Context, *ConfigPageReq) (*ConfigPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigPage not implemented")
}
func (UnimplementedSysServiceServer) ConfigBatchDelete(context.Context, *BatchIdsReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigBatchDelete not implemented")
}
func (UnimplementedSysServiceServer) ConfigCode(context.Context, *ConfigCodeQueryReq) (*ConfigListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigCode not implemented")
}
func (UnimplementedSysServiceServer) ConfigData(context.Context, *ConfigCodeQueryReq) (*ConfigDataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigData not implemented")
}
func (UnimplementedSysServiceServer) ConfigUpdate(context.Context, *ConfigUpdateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigUpdate not implemented")
}
func (UnimplementedSysServiceServer) ConfigDetail(context.Context, *IdReq) (*Config, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigDetail not implemented")
}
func (UnimplementedSysServiceServer) ConfigDelete(context.Context, *IdReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigDelete not implemented")
}
func (UnimplementedSysServiceServer) LoginLogCreate(context.Context, *LoginLogReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginLogCreate not implemented")
}
func (UnimplementedSysServiceServer) LoginLogPage(context.Context, *LoginLogPageReq) (*LoginLogPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginLogPage not implemented")
}
func (UnimplementedSysServiceServer) LoginLogBatchDelete(context.Context, *BatchIdsReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginLogBatchDelete not implemented")
}
func (UnimplementedSysServiceServer) LoginLogClean(context.Context, *LogCleanReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginLogClean not implemented")
}
func (UnimplementedSysServiceServer) LoginLogUpdate(context.Context, *LoginLogUpdateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginLogUpdate not implemented")
}
func (UnimplementedSysServiceServer) LoginLogDetail(context.Context, *IdReq) (*LoginLog, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginLogDetail not implemented")
}
func (UnimplementedSysServiceServer) LoginLogDelete(context.Context, *IdReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginLogDelete not implemented")
}
func (UnimplementedSysServiceServer) OperLogCreate(context.Context, *OperLogReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method OperLogCreate not implemented")
}
func (UnimplementedSysServiceServer) OperLogPage(context.Context, *OperLogPageReq) (*OperLogPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OperLogPage not implemented")
}
func (UnimplementedSysServiceServer) OperLogBatchDelete(context.Context, *BatchIdsReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method OperLogBatchDelete not implemented")
}
func (UnimplementedSysServiceServer) OperLogClean(context.Context, *LogCleanReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method OperLogClean not implemented")
}
func (UnimplementedSysServiceServer) OperLogUpdate(context.Context, *OperLogUpdateReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method OperLogUpdate not implemented")
}
func (UnimplementedSysServiceServer) OperLogDetail(context.Context, *IdReq) (*OperLog, error) {
	return nil, status.Error(codes.Unimplemented, "method OperLogDetail not implemented")
}
func (UnimplementedSysServiceServer) OperLogDelete(context.Context, *IdReq) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method OperLogDelete not implemented")
}
func (UnimplementedSysServiceServer) mustEmbedUnimplementedSysServiceServer() {}
func (UnimplementedSysServiceServer) testEmbeddedByValue()                    {}

// UnsafeSysServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysServiceServer will
// result in compilation errors.
type UnsafeSysServiceServer interface {
	mustEmbedUnimplementedSysServiceServer()
}

func RegisterSysServiceServer(s grpc.ServiceRegistrar, srv SysServiceServer) {
	// If the following call panics, it indicates UnimplementedSysServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysService_ServiceDesc, srv)
}

func _SysService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_DictCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).DictCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_DictCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).DictCreate(ctx, req.(*DictCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_DictPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).DictPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_DictPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).DictPage(ctx, req.(*DictPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_DictBatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).DictBatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_DictBatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).DictBatchDelete(ctx, req.(*BatchIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_DictType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictTypeQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).DictType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_DictType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).DictType(ctx, req.(*DictTypeQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_DictLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictLabelQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).DictLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_DictLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).DictLabel(ctx, req.(*DictLabelQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_DictUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).DictUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_DictUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).DictUpdate(ctx, req.(*DictUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_DictDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).DictDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_DictDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).DictDetail(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_DictDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).DictDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_DictDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).DictDelete(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_ConfigCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).ConfigCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_ConfigCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).ConfigCreate(ctx, req.(*ConfigCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_ConfigPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).ConfigPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_ConfigPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).ConfigPage(ctx, req.(*ConfigPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_ConfigBatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).ConfigBatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_ConfigBatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).ConfigBatchDelete(ctx, req.(*BatchIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_ConfigCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigCodeQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).ConfigCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_ConfigCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).ConfigCode(ctx, req.(*ConfigCodeQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_ConfigData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigCodeQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).ConfigData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_ConfigData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).ConfigData(ctx, req.(*ConfigCodeQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_ConfigUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).ConfigUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_ConfigUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).ConfigUpdate(ctx, req.(*ConfigUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_ConfigDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).ConfigDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_ConfigDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).ConfigDetail(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_ConfigDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).ConfigDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_ConfigDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).ConfigDelete(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_LoginLogCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).LoginLogCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_LoginLogCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).LoginLogCreate(ctx, req.(*LoginLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_LoginLogPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginLogPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).LoginLogPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_LoginLogPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).LoginLogPage(ctx, req.(*LoginLogPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_LoginLogBatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).LoginLogBatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_LoginLogBatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).LoginLogBatchDelete(ctx, req.(*BatchIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_LoginLogClean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogCleanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).LoginLogClean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_LoginLogClean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).LoginLogClean(ctx, req.(*LogCleanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_LoginLogUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginLogUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).LoginLogUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_LoginLogUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).LoginLogUpdate(ctx, req.(*LoginLogUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_LoginLogDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).LoginLogDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_LoginLogDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).LoginLogDetail(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_LoginLogDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).LoginLogDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_LoginLogDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).LoginLogDelete(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_OperLogCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).OperLogCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_OperLogCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).OperLogCreate(ctx, req.(*OperLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_OperLogPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperLogPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).OperLogPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_OperLogPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).OperLogPage(ctx, req.(*OperLogPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_OperLogBatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).OperLogBatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_OperLogBatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).OperLogBatchDelete(ctx, req.(*BatchIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_OperLogClean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogCleanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).OperLogClean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_OperLogClean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).OperLogClean(ctx, req.(*LogCleanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_OperLogUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperLogUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).OperLogUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_OperLogUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).OperLogUpdate(ctx, req.(*OperLogUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_OperLogDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).OperLogDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_OperLogDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).OperLogDetail(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysService_OperLogDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysServiceServer).OperLogDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysService_OperLogDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysServiceServer).OperLogDelete(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SysService_ServiceDesc is the grpc.ServiceDesc for SysService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SysService",
	HandlerType: (*SysServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SysService_Ping_Handler,
		},
		{
			MethodName: "DictCreate",
			Handler:    _SysService_DictCreate_Handler,
		},
		{
			MethodName: "DictPage",
			Handler:    _SysService_DictPage_Handler,
		},
		{
			MethodName: "DictBatchDelete",
			Handler:    _SysService_DictBatchDelete_Handler,
		},
		{
			MethodName: "DictType",
			Handler:    _SysService_DictType_Handler,
		},
		{
			MethodName: "DictLabel",
			Handler:    _SysService_DictLabel_Handler,
		},
		{
			MethodName: "DictUpdate",
			Handler:    _SysService_DictUpdate_Handler,
		},
		{
			MethodName: "DictDetail",
			Handler:    _SysService_DictDetail_Handler,
		},
		{
			MethodName: "DictDelete",
			Handler:    _SysService_DictDelete_Handler,
		},
		{
			MethodName: "ConfigCreate",
			Handler:    _SysService_ConfigCreate_Handler,
		},
		{
			MethodName: "ConfigPage",
			Handler:    _SysService_ConfigPage_Handler,
		},
		{
			MethodName: "ConfigBatchDelete",
			Handler:    _SysService_ConfigBatchDelete_Handler,
		},
		{
			MethodName: "ConfigCode",
			Handler:    _SysService_ConfigCode_Handler,
		},
		{
			MethodName: "ConfigData",
			Handler:    _SysService_ConfigData_Handler,
		},
		{
			MethodName: "ConfigUpdate",
			Handler:    _SysService_ConfigUpdate_Handler,
		},
		{
			MethodName: "ConfigDetail",
			Handler:    _SysService_ConfigDetail_Handler,
		},
		{
			MethodName: "ConfigDelete",
			Handler:    _SysService_ConfigDelete_Handler,
		},
		{
			MethodName: "LoginLogCreate",
			Handler:    _SysService_LoginLogCreate_Handler,
		},
		{
			MethodName: "LoginLogPage",
			Handler:    _SysService_LoginLogPage_Handler,
		},
		{
			MethodName: "LoginLogBatchDelete",
			Handler:    _SysService_LoginLogBatchDelete_Handler,
		},
		{
			MethodName: "LoginLogClean",
			Handler:    _SysService_LoginLogClean_Handler,
		},
		{
			MethodName: "LoginLogUpdate",
			Handler:    _SysService_LoginLogUpdate_Handler,
		},
		{
			MethodName: "LoginLogDetail",
			Handler:    _SysService_LoginLogDetail_Handler,
		},
		{
			MethodName: "LoginLogDelete",
			Handler:    _SysService_LoginLogDelete_Handler,
		},
		{
			MethodName: "OperLogCreate",
			Handler:    _SysService_OperLogCreate_Handler,
		},
		{
			MethodName: "OperLogPage",
			Handler:    _SysService_OperLogPage_Handler,
		},
		{
			MethodName: "OperLogBatchDelete",
			Handler:    _SysService_OperLogBatchDelete_Handler,
		},
		{
			MethodName: "OperLogClean",
			Handler:    _SysService_OperLogClean_Handler,
		},
		{
			MethodName: "OperLogUpdate",
			Handler:    _SysService_OperLogUpdate_Handler,
		},
		{
			MethodName: "OperLogDetail",
			Handler:    _SysService_OperLogDetail_Handler,
		},
		{
			MethodName: "OperLogDelete",
			Handler:    _SysService_OperLogDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sys.proto",
}
