// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/realtime/v1/realtime.proto

package realtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishToUsersRequest 是批量用户消息发布请求。
type PublishToUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_ids 是目标用户 ID 列表，服务端会去重并校验正数。
	UserIds []int64 `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	// type 是客户端识别的消息类型。
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// data_json 是业务数据的 JSON 编码。
	DataJson      []byte `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishToUsersRequest) Reset() {
	*x = PublishToUsersRequest{}
	mi := &file_api_realtime_v1_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishToUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishToUsersRequest) ProtoMessage() {}

func (x *PublishToUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_realtime_v1_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishToUsersRequest.ProtoReflect.Descriptor instead.
func (*PublishToUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_realtime_v1_realtime_proto_rawDescGZIP(), []int{0}
}

func (x *PublishToUsersRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *PublishToUsersRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PublishToUsersRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

// PublishToUsersResponse 表示消息已接受并发布到 Realtime 集群。
type PublishToUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishToUsersResponse) Reset() {
	*x = PublishToUsersResponse{}
	mi := &file_api_realtime_v1_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishToUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishToUsersResponse) ProtoMessage() {}

func (x *PublishToUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_realtime_v1_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishToUsersResponse.ProtoReflect.Descriptor instead.
func (*PublishToUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_realtime_v1_realtime_proto_rawDescGZIP(), []int{1}
}

var File_api_realtime_v1_realtime_proto protoreflect.FileDescriptor

const file_api_realtime_v1_realtime_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/realtime/v1/realtime.proto\x12\x1cmicroservice_kit.realtime.v1\"c\n" +
	"\x15PublishToUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\fR\bdataJson\"\x18\n" +
	"\x16PublishToUsersResponse2\x8e\x01\n" +
	"\x0fRealtimeService\x12{\n" +
	"\x0ePublishToUsers\x123.microservice_kit.realtime.v1.PublishToUsersRequest\x1a4.microservice_kit.realtime.v1.PublishToUsersResponseBHZFgithub.com/gcc798/microservice-kit/internal/api/realtime/v1;realtimev1b\x06proto3"

var (
	file_api_realtime_v1_realtime_proto_rawDescOnce sync.Once
	file_api_realtime_v1_realtime_proto_rawDescData []byte
)

func file_api_realtime_v1_realtime_proto_rawDescGZIP() []byte {
	file_api_realtime_v1_realtime_proto_rawDescOnce.Do(func() {
		file_api_realtime_v1_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_realtime_v1_realtime_proto_rawDesc), len(file_api_realtime_v1_realtime_proto_rawDesc)))
	})
	return file_api_realtime_v1_realtime_proto_rawDescData
}

var file_api_realtime_v1_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_realtime_v1_realtime_proto_goTypes = []any{
	(*PublishToUsersRequest)(nil),  // 0: microservice_kit.realtime.v1.PublishToUsersRequest
	(*PublishToUsersResponse)(nil), // 1: microservice_kit.realtime.v1.PublishToUsersResponse
}
var file_api_realtime_v1_realtime_proto_depIdxs = []int32{
	0, // 0: microservice_kit.realtime.v1.RealtimeService.PublishToUsers:input_type -> microservice_kit.realtime.v1.PublishToUsersRequest
	1, // 1: microservice_kit.realtime.v1.RealtimeService.PublishToUsers:output_type -> microservice_kit.realtime.v1.PublishToUsersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_realtime_v1_realtime_proto_init() }
func file_api_realtime_v1_realtime_proto_init() {
	if File_api_realtime_v1_realtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_realtime_v1_realtime_proto_rawDesc), len(file_api_realtime_v1_realtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_realtime_v1_realtime_proto_goTypes,
		DependencyIndexes: file_api_realtime_v1_realtime_proto_depIdxs,
		MessageInfos:      file_api_realtime_v1_realtime_proto_msgTypes,
	}.Build()
	File_api_realtime_v1_realtime_proto = out.File
	file_api_realtime_v1_realtime_proto_goTypes = nil
	file_api_realtime_v1_realtime_proto_depIdxs = nil
}
